/*
 * C4 Context Diagram - kf-poc-rhods-operator (RHODS Operator)
 * Generated by: Claude Opus 4.6
 * Source: architecture/rhoai-2.6/kf-poc-rhods-operator.md
 *
 * View with: https://structurizr.com/dsl or
 *   docker run -p 8080:8080 -v .:/usr/local/structurizr structurizr/lite
 */

workspace {
    model {
        admin = person "Cluster Admin" "Manages the RHOAI platform on OpenShift"
        dataScientist = person "Data Scientist" "Uses deployed data science components"

        rhodsOperator = softwareSystem "RHODS Operator (kf-poc-rhods-operator)" "Central platform operator for Red Hat OpenShift AI - deploys and manages all data science components" {
            dscController = container "DataScienceCluster Controller" "Reconciles DataScienceCluster CR, deploys/removes all data science components via kustomize manifests" "Go Controller (controller-runtime)"
            dsciController = container "DSCInitialization Controller" "Initializes platform: namespaces, monitoring stack, Service Mesh, network policies" "Go Controller (controller-runtime)"
            secretGenerator = container "SecretGenerator Controller" "Watches annotated Secrets, generates random values, creates OAuthClient CRs" "Go Controller"
            featureAPI = container "Feature API" "Template-based feature deployment for Service Mesh and Serverless configurations" "Go Framework"
            platformDetection = container "Platform Detection" "Detects platform type (ODH, Self-Managed, Managed addon) from OLM CSVs" "Go Utility"
            monitoringStack = container "Monitoring Stack" "Prometheus, Alertmanager, Blackbox Exporter for managed RHOAI clusters" "Prometheus/Alertmanager"
        }

        # External Dependencies
        k8sAPI = softwareSystem "Kubernetes API Server" "OpenShift cluster API server" "External"
        serviceMesh = softwareSystem "OpenShift Service Mesh" "Istio/Maistra for traffic management and mTLS" "External"
        serverless = softwareSystem "OpenShift Serverless" "KNative Serving for serverless autoscaling" "External"
        olm = softwareSystem "Operator Lifecycle Manager" "Manages operator installation and upgrades" "External"
        certManager = softwareSystem "cert-manager" "Certificate management for service mesh" "External"

        # OpenShift Platform
        openshiftOAuth = softwareSystem "OpenShift OAuth" "Platform authentication server" "External"
        openshiftConsole = softwareSystem "OpenShift Console" "Platform web console" "External"
        openshiftMonitoring = softwareSystem "OpenShift Monitoring" "Cluster monitoring (Prometheus federation)" "External"

        # Deployed Components (managed by operator)
        dashboard = softwareSystem "ODH/RHOAI Dashboard" "Web UI for data science platform" "Internal RHOAI"
        workbenches = softwareSystem "Workbenches" "Notebook controller and workbench tooling" "Internal RHOAI"
        kserve = softwareSystem "KServe" "Single-model serving with serverless" "Internal RHOAI"
        modelMesh = softwareSystem "ModelMesh Serving" "Multi-model serving" "Internal RHOAI"
        dsPipelines = softwareSystem "Data Science Pipelines" "ML pipeline orchestration" "Internal RHOAI"
        codeFlare = softwareSystem "CodeFlare" "Distributed computing" "Internal RHOAI"
        ray = softwareSystem "Ray (KubeRay)" "Ray cluster management" "Internal RHOAI"
        trustyAI = softwareSystem "TrustyAI" "AI model explainability and fairness" "Internal RHOAI"

        # Internal Dependencies
        odhManifests = softwareSystem "odh-manifests" "Kustomize manifests for component deployment" "Internal RHOAI"
        odhModelController = softwareSystem "odh-model-controller" "Model serving controller" "Internal RHOAI"

        # Relationships - Admin
        admin -> rhodsOperator "Creates DataScienceCluster and DSCInitialization CRs via kubectl"
        admin -> monitoringStack "Accesses Prometheus/Alertmanager via OpenShift Routes (OAuth)"
        dataScientist -> dashboard "Accesses RHOAI Dashboard"

        # Relationships - Operator to Platform
        rhodsOperator -> k8sAPI "Manages all cluster resources" "HTTPS/6443 TLS 1.2+ SA Token"
        rhodsOperator -> serviceMesh "Configures ServiceMeshControlPlane, Gateways" "HTTPS/6443 CRD Management"
        rhodsOperator -> serverless "Configures KnativeServing" "HTTPS/6443 CRD Management"
        rhodsOperator -> olm "Queries CSVs and Subscriptions for platform detection" "HTTPS/6443"
        rhodsOperator -> certManager "Optional certificate management" "HTTPS/6443"
        rhodsOperator -> openshiftOAuth "Creates OAuthClient CRs for dashboard auth" "HTTPS/6443"
        rhodsOperator -> openshiftConsole "Creates ConsoleLink CR" "HTTPS/6443"
        rhodsOperator -> openshiftMonitoring "Creates ServiceMonitor, PrometheusRule CRs" "HTTPS/6443"

        # Relationships - Operator deploys components
        rhodsOperator -> dashboard "Deploys via kustomize manifests"
        rhodsOperator -> workbenches "Deploys via kustomize manifests"
        rhodsOperator -> kserve "Deploys via kustomize manifests"
        rhodsOperator -> modelMesh "Deploys via kustomize manifests"
        rhodsOperator -> dsPipelines "Deploys via kustomize manifests"
        rhodsOperator -> codeFlare "Deploys via kustomize manifests"
        rhodsOperator -> ray "Deploys via kustomize manifests"
        rhodsOperator -> trustyAI "Deploys via kustomize manifests"
        rhodsOperator -> odhModelController "Deploys alongside KServe/ModelMesh"

        # Internal container relationships
        dscController -> featureAPI "Uses for KServe Service Mesh/Serverless setup"
        dscController -> platformDetection "Queries platform type"
        dsciController -> monitoringStack "Deploys monitoring for managed clusters"
        secretGenerator -> dscController "Provides generated secrets for OAuth flows"
    }

    views {
        systemContext rhodsOperator "SystemContext" {
            include *
            autoLayout
        }

        container rhodsOperator "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Person" {
                shape Person
                background #08427B
                color #ffffff
            }
            element "Software System" {
                background #1168bd
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
