/*
 * Kubeflow Notebook Controller - C4 Context Diagram (Structurizr DSL)
 * Generated by: Claude Opus 4.6
 */

workspace {
    model {
        user = person "Data Scientist" "Creates and uses Jupyter Notebook servers via ODH Dashboard or kubectl"
        admin = person "Platform Admin" "Manages RHOAI platform and configures notebook settings"

        kubeflow = softwareSystem "Kubeflow Notebook Controller" "Manages lifecycle of Jupyter Notebook servers on OpenShift, reconciling Notebook CRs into StatefulSets, Routes, and OAuth-protected endpoints" {
            kfController = container "KF Notebook Controller" "Reconciles Notebook CRs into StatefulSets and Services; manages notebook status" "Go Operator (controller-runtime)"
            cullingController = container "Culling Controller" "Monitors notebook idleness via Jupyter API; stops idle notebooks" "Go Controller"
            odhController = container "ODH Notebook Controller" "Creates OpenShift Routes, OAuth proxy resources, NetworkPolicies, trusted-ca ConfigMaps" "Go Operator (controller-runtime)"
            webhook = container "Notebook Mutating Webhook" "Injects oauth-proxy sidecar, reconciliation lock, and proxy env vars" "Admission Webhook (8443/TCP)"
        }

        odhDashboard = softwareSystem "ODH Dashboard" "Web UI for creating and managing notebook servers" "Internal RHOAI"
        openshiftOAuth = softwareSystem "OpenShift OAuth Server" "Authenticates users via OpenShift identity providers" "OpenShift Platform"
        openshiftRouter = softwareSystem "OpenShift Router" "Serves Routes for external access to notebooks" "OpenShift Platform"
        openshiftServiceCA = softwareSystem "OpenShift service-ca" "Auto-provisions TLS certificates for services" "OpenShift Platform"
        openshiftProxy = softwareSystem "OpenShift Cluster Proxy" "Provides cluster-wide HTTP/HTTPS proxy configuration" "OpenShift Platform"
        k8sAPI = softwareSystem "Kubernetes API Server" "Cluster API for managing all Kubernetes resources" "Kubernetes"

        # Relationships
        user -> odhDashboard "Creates notebooks via UI" "HTTPS/443"
        user -> kubeflow "Creates Notebook CR via kubectl" "HTTPS/443"
        admin -> kubeflow "Configures notebook settings"

        odhDashboard -> k8sAPI "Creates Notebook CRs" "HTTPS/443"

        kfController -> k8sAPI "Creates StatefulSets, Services; updates Notebook status" "HTTPS/443"
        odhController -> k8sAPI "Creates Routes, Services, Secrets, ServiceAccounts, NetworkPolicies, ConfigMaps" "HTTPS/443"
        cullingController -> k8sAPI "Updates Notebook annotations (stop idle)" "HTTPS/443"

        kubeflow -> openshiftOAuth "Authenticates notebook users via oauth-proxy sidecar" "HTTPS/443"
        kubeflow -> openshiftRouter "Exposes notebooks via OpenShift Routes" "HTTPS/443"
        kubeflow -> openshiftServiceCA "Auto-provisions TLS certs for oauth-proxy and webhook"
        kubeflow -> openshiftProxy "Reads cluster proxy config (HTTP_PROXY, HTTPS_PROXY)" "HTTPS/443"
        kubeflow -> k8sAPI "Controller CRUD operations and SAR checks" "HTTPS/443"

        k8sAPI -> webhook "Calls mutating webhook on Notebook create/update" "HTTPS/8443"
    }

    views {
        systemContext kubeflow "SystemContext" {
            include *
            autoLayout
        }

        container kubeflow "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438DD5
                color #ffffff
            }
            element "Person" {
                background #08427B
                color #ffffff
                shape person
            }
            element "Container" {
                background #438DD5
                color #ffffff
            }
            element "OpenShift Platform" {
                background #999999
                color #ffffff
            }
            element "Kubernetes" {
                background #326CE5
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
        }
    }
}
