/* ModelMesh Serving - C4 Context Diagram (Structurizr DSL)
 * Generated by: Claude Opus 4.6
 * Source: architecture/rhoai-2.6/modelmesh-serving.md
 */

workspace {
    model {
        user = person "Data Scientist" "Creates ServingRuntime and Predictor resources to deploy ML models for multi-model serving"

        modelMeshServing = softwareSystem "ModelMesh Serving" "Kubernetes operator managing the lifecycle of ModelMesh model serving runtimes and predictors for multi-model serving" {
            controller = container "modelmesh-controller" "Main Go operator managing ServingRuntime, Predictor, InferenceService, and Service reconciliation" "Go Operator (controller-runtime)"
            srReconciler = container "ServingRuntimeReconciler" "Watches ServingRuntime/ClusterServingRuntime CRs; creates Deployments with ModelMesh + runtime containers" "Controller"
            predReconciler = container "PredictorReconciler" "Watches Predictor/InferenceService CRs; registers VModels with ModelMesh via gRPC" "Controller"
            svcReconciler = container "ServiceReconciler" "Creates/manages Kubernetes Services for inference endpoint routing and ServiceMonitor for Prometheus" "Controller"
            autoscalerReconciler = container "AutoscalerReconciler" "Manages HorizontalPodAutoscaler resources for runtime Deployments" "Sub-controller"
            webhook = container "ServingRuntime Webhook" "Validates ServingRuntime/ClusterServingRuntime specs on CREATE/UPDATE" "Validating Webhook" "9443/TCP"
            modelMeshSidecar = container "ModelMesh Sidecar" "Java-based intelligent model routing, caching, and load balancing across runtime pods" "Java Container" "8033/TCP gRPC"
            oauthProxy = container "oauth-proxy" "OpenShift oauth-proxy sidecar for authentication on HTTPS port 8443" "Sidecar Container" "8443/TCP"
            restProxy = container "REST Proxy" "gRPC-to-REST translation proxy enabling HTTP inference endpoints" "Optional Sidecar Container"
            storageHelper = container "Storage Helper (puller)" "Downloads model artifacts from object storage to local volume" "Optional Sidecar Container"
        }

        etcd = softwareSystem "etcd" "Distributed coordination backend for ModelMesh (model placement, state tracking)" "External"
        k8sApi = softwareSystem "Kubernetes API Server" "Cluster API for managing resources" "External"
        objectStorage = softwareSystem "Object Storage (S3/GCS/Azure)" "Model artifact storage" "External"
        prometheus = softwareSystem "Prometheus" "Metrics collection and monitoring" "External"
        certManager = softwareSystem "cert-manager" "TLS certificate management for webhook server" "External"
        openshiftServiceCA = softwareSystem "OpenShift Service CA" "Auto-provisions TLS certificates via annotations" "External"
        prometheusOperator = softwareSystem "Prometheus Operator" "ServiceMonitor CRD for metrics collection" "External"

        modelMeshRuntime = softwareSystem "ModelMesh (Java Runtime)" "Core model routing and caching engine" "Internal ODH"
        runtimeAdapter = softwareSystem "modelmesh-runtime-adapter" "Storage helper/puller and built-in adapter for model loading" "Internal ODH"
        openshiftOAuthProxy = softwareSystem "OpenShift oauth-proxy" "Authentication proxy for runtime inference endpoints" "Internal ODH"

        # User interactions
        user -> modelMeshServing "Creates ServingRuntime, Predictor, InferenceService CRs via kubectl"
        user -> modelMeshServing "Sends inference requests via gRPC (8033) or HTTPS (8443)"

        # Internal container relationships
        controller -> srReconciler "Delegates ServingRuntime reconciliation"
        controller -> predReconciler "Delegates Predictor reconciliation"
        controller -> svcReconciler "Delegates Service reconciliation"
        controller -> autoscalerReconciler "Delegates HPA management"
        controller -> webhook "Handles admission requests"
        predReconciler -> modelMeshSidecar "SetVModel/DeleteVModel via gRPC/8033"
        oauthProxy -> restProxy "Forwards authenticated requests (plaintext in-pod)"
        restProxy -> modelMeshSidecar "gRPC translation (in-pod)"
        modelMeshSidecar -> storageHelper "Model load requests via gRPC/8086"

        # External dependencies
        modelMeshSidecar -> etcd "Model placement and state tracking" "gRPC/2379 TLS"
        controller -> k8sApi "Watch/manage CRDs, Deployments, Services, Secrets" "HTTPS/443"
        storageHelper -> objectStorage "Download model artifacts" "HTTPS/443 TLS 1.2+"
        prometheus -> modelMeshServing "Scrape metrics" "HTTPS/2112, HTTP/8080"
        openshiftServiceCA -> oauthProxy "Auto-provision TLS certs" "Annotation-based"
        svcReconciler -> prometheusOperator "Creates ServiceMonitor"

        # Internal ODH relationships
        modelMeshServing -> modelMeshRuntime "Injected as sidecar container in runtime Deployments"
        modelMeshServing -> runtimeAdapter "Used as storage helper container image"
        modelMeshServing -> openshiftOAuthProxy "Injected as auth sidecar in runtime Deployments"
    }

    views {
        systemContext modelMeshServing "SystemContext" {
            include *
            autoLayout
        }

        container modelMeshServing "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438dd5
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal ODH" {
                background #7ed321
                color #ffffff
            }
            element "Person" {
                shape person
                background #08427b
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
