/*
 * C4 Context Diagram for KServe V2 REST Proxy
 * Generated by: Claude Opus 4.6
 * Source: architecture/rhoai-2.6/rest-proxy.md
 */

workspace {
    model {
        client = person "API Client" "Sends inference requests via KServe V2 REST Predict Protocol"

        restProxy = softwareSystem "KServe V2 REST Proxy" "Reverse-proxy translating KServe V2 REST requests into gRPC calls for model serving backends" {
            server = container "REST Proxy Server" "Accepts HTTP/HTTPS REST requests on port 8008" "Go HTTP Server"
            grpcGateway = container "gRPC-Gateway" "Auto-generated reverse proxy stubs from protobuf definitions" "Generated Go Code"
            jsonMarshaler = container "Custom JSON Marshaler" "Handles KServe V2 tensor data serialization including multi-dimensional tensors, base64 BYTES, and all V2 data types" "Go Library"
            requestTransformer = container "Request Transformer" "Converts REST JSON to gRPC ModelInferRequest" "Go Library"
            responseTransformer = container "Response Transformer" "Converts gRPC ModelInferResponse to REST JSON" "Go Library"
        }

        modelMeshServing = softwareSystem "ModelMesh Serving" "Model serving platform with gRPC inference interface" "Internal RHOAI" {
            modelServer = container "Model Server" "Handles gRPC inference requests" "GRPCInferenceService"
            servingController = container "ModelMesh Serving Controller" "Manages model serving deployments and injects rest-proxy sidecar" "Go Operator"
        }

        modelServingConfig = softwareSystem "Model Serving Config" "ConfigMap (model-serving-config) configuring rest-proxy image" "Kubernetes ConfigMap"

        # Relationships
        client -> restProxy "Sends REST inference requests" "HTTP/HTTPS 8008/TCP"
        restProxy -> modelMeshServing "Forwards translated gRPC inference requests" "gRPC 8033/TCP (localhost)"

        server -> grpcGateway "Routes requests"
        grpcGateway -> requestTransformer "Transforms requests"
        requestTransformer -> jsonMarshaler "Serializes/deserializes"
        grpcGateway -> responseTransformer "Transforms responses"
        responseTransformer -> jsonMarshaler "Serializes/deserializes"

        servingController -> restProxy "Injects as sidecar container"
        modelServingConfig -> servingController "Provides restProxy.image config"
    }

    views {
        systemContext restProxy "SystemContext" {
            include *
            autoLayout
            description "KServe V2 REST Proxy in the context of ModelMesh Serving"
        }

        container restProxy "Containers" {
            include *
            autoLayout
            description "Internal structure of the REST Proxy"
        }

        styles {
            element "Person" {
                shape Person
                background #08427B
                color #ffffff
            }
            element "Software System" {
                background #1168BD
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Kubernetes ConfigMap" {
                background #f5a623
                color #ffffff
            }
            element "Container" {
                background #438DD5
                color #ffffff
            }
        }
    }
}
