/*
 * C4 Context Diagram - Text Generation Inference Server (TGIS)
 * Generated by: Claude Opus 4.6
 * Source: architecture/rhoai-2.6/text-generation-inference.md
 */

workspace {
    model {
        user = person "ML Application / Client" "Sends text generation inference requests via gRPC"

        tgis = softwareSystem "Text Generation Inference Server (TGIS)" "High-performance LLM inference server with gRPC API, dynamic batching, and tensor parallelism" {
            launcher = container "text-generation-launcher" "Process orchestrator managing model shards and router lifecycle" "Rust Binary"
            router = container "text-generation-router" "gRPC/HTTP server: request validation, dynamic batching, token decoding, Prometheus metrics" "Rust Binary" {
                tags "Primary"
            }
            modelShard = container "text-generation-server" "Model loading and GPU inference using PyTorch with pluggable inference engines" "Python gRPC Service"
            cudaKernels = container "CUDA Kernels" "Custom GPU kernels, ExLlama GPTQ, Flash Attention for optimized inference" "CUDA C++ Extensions"
        }

        kserve = softwareSystem "KServe ServingRuntime" "Orchestrates TGIS container as a model serving runtime" "Internal RHOAI"
        modelStorage = softwareSystem "Model Storage (PVC)" "PersistentVolumeClaim for model weight storage" "Internal"
        prometheus = softwareSystem "Prometheus" "Metrics collection and monitoring" "Internal"
        hfHub = softwareSystem "HuggingFace Hub" "Model weight repository (build-time only, offline at runtime)" "External"

        // Relationships - External
        user -> tgis "Sends inference requests" "gRPC/8033 Optional TLS/mTLS"
        kserve -> tgis "Orchestrates container lifecycle" "Container orchestration"
        prometheus -> tgis "Scrapes metrics" "HTTP/3000 GET /metrics"
        tgis -> modelStorage "Loads model weights" "Volume mount /shared_model_storage"
        tgis -> hfHub "Downloads model weights (build-time)" "HTTPS/443 Optional HF Token"

        // Relationships - Internal
        launcher -> router "Manages lifecycle" "Process management"
        launcher -> modelShard "Manages lifecycle" "Process management"
        router -> modelShard "Inference requests" "Unix Socket gRPC"
        modelShard -> cudaKernels "GPU computation" "In-process CUDA calls"

        // User interactions
        user -> router "Generate / GenerateStream / Tokenize / ModelInfo" "gRPC/8033"
    }

    views {
        systemContext tgis "SystemContext" {
            include *
            autoLayout
            description "System context showing TGIS in the RHOAI ecosystem"
        }

        container tgis "Containers" {
            include *
            autoLayout
            description "Internal container architecture of TGIS"
        }

        styles {
            element "Software System" {
                background #438dd5
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #000000
            }
            element "Internal" {
                background #7ed321
                color #000000
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Person" {
                background #08427b
                color #ffffff
                shape person
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
            element "Primary" {
                background #1168bd
                color #ffffff
            }
        }
    }
}
