// TrustyAI Service Operator - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6
// Source: architecture/rhoai-2.6/trustyai-service-operator.md

workspace {
    model {
        user = person "Data Scientist / ML Engineer" "Creates TrustyAIService CRs and accesses fairness/explainability dashboards"

        trustyaiOperator = softwareSystem "TrustyAI Service Operator" "Kubernetes operator managing TrustyAI service instances for AI model explainability, fairness monitoring, and bias detection" {
            controllerManager = container "Controller Manager" "Main operator process with leader election, health probes (8081), and metrics (8080)" "Go / controller-runtime v0.14.6"
            reconciler = container "TrustyAIServiceReconciler" "Watches TrustyAIService CRs and reconciles Deployments, Services, Routes, PVCs, ServiceMonitors" "Go Controller"
            trustyaiService = container "TrustyAI Service" "AI explainability and fairness service exposing HTTP API on port 8080 with /q/metrics and /consumer/kserve/v2" "Java/Quarkus Container"
            oauthProxy = container "OAuth Proxy Sidecar" "OpenShift OAuth proxy providing authentication on port 8443, proxying to TrustyAI on localhost:8080" "ose-oauth-proxy"
        }

        modelMesh = softwareSystem "ModelMesh Serving" "Model serving platform for multi-model inference" "Internal ODH"
        kserve = softwareSystem "KServe" "Standardized serverless ML inference platform" "Internal ODH"
        prometheus = softwareSystem "Prometheus / OpenShift Monitoring" "Metrics collection and monitoring" "External"
        openshiftOAuth = softwareSystem "OpenShift OAuth" "OpenShift authentication and authorization" "External"
        openshiftRouting = softwareSystem "OpenShift Router" "Ingress routing via OpenShift Routes" "External"
        kubernetesAPI = softwareSystem "Kubernetes API Server" "Kubernetes control plane API" "External"
        certSigner = softwareSystem "OpenShift Service Serving Cert Signer" "Auto-provisions TLS certificates for services" "External"

        // User interactions
        user -> trustyaiOperator "Creates TrustyAIService CR via kubectl/oc"
        user -> trustyaiService "Accesses TrustyAI API via OpenShift Route" "HTTPS/443"

        // Operator interactions
        controllerManager -> reconciler "Runs reconciliation loop"
        reconciler -> kubernetesAPI "CRUD resources (Deployments, Services, Routes, PVCs, ServiceMonitors)" "HTTPS/6443 TLS 1.2+ SA Token"
        reconciler -> modelMesh "Patches MM_PAYLOAD_PROCESSORS env var on ModelMesh deployments" "HTTPS/6443 Kubernetes API"
        reconciler -> kserve "Sets InferenceLogger on InferenceService predictor specs" "HTTPS/6443 Kubernetes API"

        // Data flow interactions
        modelMesh -> trustyaiService "Sends inference data for payload processing" "HTTP/80 /consumer/kserve/v2"
        kserve -> trustyaiService "Sends inference data via InferenceLogger" "HTTP/80"
        prometheus -> trustyaiService "Scrapes fairness metrics (SPD, DIR)" "HTTP/80 /q/metrics"
        prometheus -> controllerManager "Scrapes operator metrics" "HTTPS/8443 Bearer Token"

        // Auth & TLS
        oauthProxy -> openshiftOAuth "Validates OAuth tokens, SAR checks" "HTTPS/443"
        oauthProxy -> trustyaiService "Forwards authenticated requests" "HTTP/8080 localhost"
        openshiftRouting -> oauthProxy "Routes external traffic (TLS Passthrough)" "HTTPS/8443"
        certSigner -> oauthProxy "Auto-provisions TLS serving certificates" "Annotation-based"
    }

    views {
        systemContext trustyaiOperator "SystemContext" {
            include *
            autoLayout
        }

        container trustyaiOperator "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438DD5
                color #ffffff
            }
            element "Internal ODH" {
                background #7ed321
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Person" {
                background #08427B
                color #ffffff
                shape person
            }
            element "Container" {
                background #438DD5
                color #ffffff
            }
        }
    }
}
