/*
 * TrustyAI Explainability - C4 Context Diagram (Structurizr DSL)
 * Generated by: Claude Opus 4.6
 */

workspace {
    model {
        user = person "Data Scientist / ML Engineer" "Requests fairness metrics, drift analysis, and model explanations"

        trustyai = softwareSystem "TrustyAI Explainability" "AI fairness metrics, bias tracking, data drift detection, and model explainability service" {
            service = container "explainability-service" "Quarkus REST service exposing metrics, explainability, data management, and inference payload consumption endpoints" "Java/Quarkus 3.2.7"
            core = container "explainability-core" "Core XAI algorithms: fairness (SPD, DIR), explainers (LIME, SHAP, CF, PDP, TSSaliency), drift detectors (KS, Meanshift, Fourier MMD)" "Java Library"
            connectors = container "explainability-connectors" "KServe v2 gRPC client for model inference with protobuf stubs" "Java Library"
            arrow = container "explainability-arrow" "Apache Arrow-based data interchange between TrustyAI Java and Python" "Java Library"
            scheduler = container "PrometheusScheduler" "Periodically calculates registered metrics and publishes to Prometheus via Micrometer" "Quarkus Scheduler"
            mmReconciler = container "ModelMesh Payload Reconciler" "Reconciles partial input/output inference payloads from ModelMesh into complete prediction records" "Java Component"
            ksReconciler = container "KServe Payload Reconciler" "Reconciles KServe CloudEvent-based inference payloads into complete prediction records" "Java Component"
        }

        modelmesh = softwareSystem "ModelMesh Serving" "Model serving platform that sends inference payloads to TrustyAI" "Internal RHOAI"
        kserve = softwareSystem "KServe" "Model serving platform with inference logging and gRPC model endpoints" "Internal RHOAI"
        trustyaiOperator = softwareSystem "TrustyAI Service Operator" "Manages TrustyAI service deployments via TrustyAIService CR" "Internal RHOAI"
        prometheus = softwareSystem "Prometheus / User Workload Monitoring" "Scrapes and stores TrustyAI fairness and drift metrics" "Internal RHOAI"
        minio = softwareSystem "MinIO" "Optional object storage backend for inference data" "External"
        pvc = softwareSystem "PVC Storage" "Persistent volume for inference data at /inputs mount" "Infrastructure"
        optaplanner = softwareSystem "OptaPlanner" "Constraint solver used for counterfactual explanations" "External Library"

        # User interactions
        user -> trustyai "Requests fairness metrics, explanations, data management" "HTTP REST/8080"

        # Internal container relationships
        service -> core "Uses for metric calculation and explanations" "in-process"
        service -> connectors "Uses for model inference calls" "in-process"
        service -> arrow "Uses for Java-Python data interop" "in-process"
        service -> scheduler "Runs scheduled metric calculations" "in-process"
        service -> mmReconciler "Delegates ModelMesh payload reconciliation" "in-process"
        service -> ksReconciler "Delegates KServe payload reconciliation" "in-process"
        core -> optaplanner "Uses for counterfactual explanations" "in-process"

        # External interactions
        modelmesh -> trustyai "Sends inference payloads via payload processor webhook" "HTTP/80"
        kserve -> trustyai "Sends inference CloudEvents; provides gRPC model endpoints" "HTTP/80 + gRPC"
        trustyaiOperator -> trustyai "Manages deployments via TrustyAIService CR" "Kubernetes API"
        prometheus -> trustyai "Scrapes /q/metrics endpoint" "HTTP/80 Bearer Token"
        trustyai -> kserve "Calls model endpoints for explanations" "gRPC/plaintext"
        trustyai -> minio "Stores/retrieves inference data (optional)" "HTTP/9000"
        trustyai -> pvc "Persists inference data" "File I/O"
    }

    views {
        systemContext trustyai "SystemContext" {
            include *
            autoLayout
        }

        container trustyai "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438dd5
                color #ffffff
            }
            element "Person" {
                shape person
                background #08427b
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "External Library" {
                background #999999
                color #ffffff
            }
            element "Infrastructure" {
                background #f5a623
                color #ffffff
            }
        }
    }
}
