// Argo Workflows - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6
// Source: architecture/rhoai-3.4/argo-workflows.md

workspace {
    model {
        user = person "Data Scientist / ML Engineer" "Creates and runs ML pipeline workflows"
        dspUser = person "DSP API Consumer" "Submits workflows via Data Science Pipelines API"

        argoWorkflows = softwareSystem "Argo Workflows" "Container-native workflow engine for orchestrating parallel jobs on Kubernetes" {
            workflowController = container "workflow-controller" "Watches Workflow/CronWorkflow CRDs, creates pods for workflow steps, manages lifecycle, leader election, metrics, artifact GC" "Go Binary (Deployment)"
            argoServer = container "argo-server" "REST/gRPC API server and web UI for workflow management; supports SSO, OIDC, Bearer token auth" "Go Binary (Deployment)"
            argoExec = container "argoexec" "Executor sidecar/init container injected into step pods; handles artifact collection, output parameters, resource management" "Go Binary (Sidecar)"
            controllerConfigMap = container "workflow-controller-configmap" "Central configuration for controller behavior, artifact repos, persistence, metrics, parallelism" "ConfigMap"
        }

        k8sAPI = softwareSystem "Kubernetes API Server" "Core platform for CRD management and pod execution" "External"
        s3Store = softwareSystem "S3-compatible Object Store" "Artifact storage (MinIO, AWS S3, GCS, Azure Blob)" "External"
        database = softwareSystem "PostgreSQL / MySQL" "Workflow archival and node status offloading" "External"
        oidcProvider = softwareSystem "OIDC Provider" "SSO authentication for Argo Server" "External"
        containerRegistry = softwareSystem "Container Registry" "Stores executor and step container images" "External"
        prometheus = softwareSystem "Prometheus" "Metrics collection and monitoring" "External"

        dspOperator = softwareSystem "Data Science Pipelines Operator" "Deploys and configures Argo Workflows as part of DSP stack" "Internal RHOAI"
        dspAPIServer = softwareSystem "Data Science Pipelines API Server" "Submits Workflow CRs and tracks status" "Internal RHOAI"

        // User interactions
        user -> argoWorkflows "Creates Workflow/CronWorkflow CRs via kubectl or UI"
        dspUser -> dspAPIServer "Submits pipeline runs"

        // Internal container interactions
        workflowController -> controllerConfigMap "Reads configuration"
        workflowController -> argoExec "Injects into step pods"

        // External dependencies
        workflowController -> k8sAPI "CRD CRUD, pod management, leader election" "HTTPS/443"
        argoExec -> k8sAPI "Reports step status" "HTTPS/443"
        argoServer -> k8sAPI "CRUD operations on CRDs" "HTTPS/443"
        argoExec -> s3Store "Uploads/downloads artifacts" "HTTPS/443 or HTTP/9000"
        workflowController -> database "Archives completed workflows" "TCP/5432 or 3306"
        argoServer -> database "Queries archived workflows" "TCP/5432 or 3306"
        argoServer -> oidcProvider "SSO authentication" "HTTPS/443"
        k8sAPI -> containerRegistry "Pulls container images" "HTTPS/443"
        prometheus -> workflowController "Scrapes metrics" "HTTP/9090"

        // Internal RHOAI integrations
        dspOperator -> argoWorkflows "Deploys and configures"
        dspAPIServer -> argoWorkflows "Submits Workflow CRs" "HTTPS/443"
    }

    views {
        systemContext argoWorkflows "SystemContext" {
            include *
            autoLayout
        }

        container argoWorkflows "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Person" {
                shape Person
                background #08427b
                color #ffffff
            }
            element "Software System" {
                background #1168bd
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
