// Feast Operator - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6

workspace {
    model {
        user = person "Data Scientist" "Creates and manages Feast feature stores for ML workflows"

        feastOperator = softwareSystem "Feast Operator" "Kubernetes operator managing Feast feature store lifecycle - online/offline stores, registry, UI, CronJobs" {
            controller = container "FeatureStore Controller" "Reconciles FeatureStore CRs; creates Deployments, Services, PVCs, ConfigMaps, RBAC, Routes, CronJobs, HPAs, PDBs" "Go Operator (controller-runtime)"
            nbController = container "NotebookConfigMap Controller" "Watches Kubeflow Notebook CRs; creates per-notebook ConfigMaps with feast project configurations" "Go Operator (controller-runtime)"
            authzPkg = container "FeastAuthorization" "Deploys Kubernetes RBAC (Roles, RoleBindings, ClusterRoles) for feature store authorization" "Go Package"
            onlineServer = container "Online Store Server" "Serves features online via HTTP/HTTPS with optional RBAC/OIDC auth" "Python/gunicorn, 6566-6567/TCP"
            offlineServer = container "Offline Store Server" "Serves batch feature retrieval via HTTP/HTTPS" "Python/gunicorn, 8815-8816/TCP"
            registryServer = container "Registry Server" "Feature store metadata management via gRPC and REST" "Python, 6570-6573/TCP"
            uiServer = container "Feast UI" "Web UI for browsing feature store metadata" "Python, 8888-8443/TCP"
            cronJobRunner = container "CronJob Runner" "Executes scheduled feast apply and materialize-incremental commands" "ose-cli container"
            nsRegistry = container "Namespace Registry" "Tracks all deployed FeatureStore client configs across namespaces" "ConfigMap-based"
        }

        rhodsOperator = softwareSystem "RHODS Operator" "Deploys feast-operator via kustomize overlays; injects RELATED_IMAGE_* env vars" "Internal RHOAI"
        kubeflowNotebooks = softwareSystem "Kubeflow Notebooks" "Notebook environments for data scientists" "Internal RHOAI"
        openshiftCerts = softwareSystem "OpenShift Service Serving Certs" "Auto-provisions TLS certificates for services" "OpenShift Platform"
        odhTrustedCA = softwareSystem "ODH Trusted CA Bundle" "Custom CA certificate bundle for TLS trust" "Internal RHOAI"
        prometheus = softwareSystem "Prometheus" "Metrics collection and monitoring" "OpenShift Platform"
        k8sAPI = softwareSystem "Kubernetes API" "Kubernetes control plane" "Platform"
        externalDB = softwareSystem "External Database" "Postgres, Redis, MongoDB, Snowflake, ClickHouse for persistence" "External"
        s3Storage = softwareSystem "S3/GCS Object Storage" "Registry file persistence on object stores" "External"

        // User interactions
        user -> feastOperator "Creates FeatureStore CR via kubectl"
        user -> uiServer "Browses feature store metadata via OpenShift Route"
        user -> kubeflowNotebooks "Uses notebooks with feast integration labels"

        // Internal component interactions
        controller -> authzPkg "Delegates RBAC creation"
        controller -> onlineServer "Creates and manages"
        controller -> offlineServer "Creates and manages"
        controller -> registryServer "Creates and manages"
        controller -> uiServer "Creates and manages"
        controller -> cronJobRunner "Creates and manages"
        controller -> nsRegistry "Updates registry ConfigMap"
        nbController -> kubeflowNotebooks "Watches Notebook CRs"
        cronJobRunner -> onlineServer "kubectl exec: feast apply/materialize"

        // External dependencies
        rhodsOperator -> feastOperator "Deploys via kustomize" "Kustomize"
        feastOperator -> k8sAPI "CRUD operations on managed resources" "HTTPS/443"
        feastOperator -> openshiftCerts "Auto TLS via service annotations" "Annotation-driven"
        feastOperator -> odhTrustedCA "Mounts CA bundle ConfigMap" "ConfigMap"
        prometheus -> feastOperator "Scrapes operator metrics" "HTTPS/8443"
        prometheus -> onlineServer "Scrapes feature server metrics" "HTTP/8000"

        // Egress
        onlineServer -> externalDB "Read/write features" "Various protocols"
        offlineServer -> externalDB "Read/write features" "Various protocols"
        registryServer -> s3Storage "Registry file persistence" "HTTPS/443"
        registryServer -> externalDB "Registry DB persistence" "Various protocols"
    }

    views {
        systemContext feastOperator "SystemContext" {
            include *
            autoLayout
        }

        container feastOperator "Containers" {
            include *
            autoLayout
        }

        styles {
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "OpenShift Platform" {
                background #ee0000
                color #ffffff
            }
            element "Platform" {
                background #326ce5
                color #ffffff
            }
            element "Person" {
                background #08427b
                color #ffffff
                shape Person
            }
            element "Software System" {
                background #1168bd
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
