/*
 * C4 Context Diagram: FMS Guardrails Orchestrator
 * Generated by: Claude Opus 4.6
 * Source: architecture/rhoai-3.4/fms-guardrails-orchestrator.md
 *
 * View with: https://structurizr.com/dsl or
 *   docker run -p 8080:8080 -v .:/usr/local/structurizr structurizr/lite
 */

workspace {
    model {
        client = person "Client Application" "Sends text generation and detection requests to the orchestrator"

        orchestrator = softwareSystem "FMS Guardrails Orchestrator" "REST API orchestrator that coordinates AI text generation with content safety guardrails" {
            apiServer = container "Guardrails API Server" "Main HTTP/HTTPS API server handling guardrails requests" "Rust/Axum, Port 8033/TCP"
            healthServer = container "Health Server" "Dedicated health check server" "Rust/Axum, Port 8034/TCP"
            generationClient = container "GenerationClient" "gRPC client for TGIS/caikit-nlp backends" "Rust/Tonic"
            openaiClient = container "OpenAiClient" "HTTP client for OpenAI-compatible backends" "Rust/reqwest"
            detectorClient = container "DetectorClient" "HTTP client for content safety detectors" "Rust/reqwest"
            chunkerClient = container "ChunkerClient" "gRPC client for text chunking/tokenization" "Rust/Tonic"
            tlsModule = container "TLS Module" "Configures TLS/mTLS for server and client connections" "Rust/rustls"
            otelIntegration = container "OpenTelemetry Integration" "Exports traces and metrics via OTLP" "Rust/opentelemetry SDK"
        }

        tgis = softwareSystem "TGIS" "Text Generation Inference Server - gRPC generation backend" "Internal ODH"
        caikitNlp = softwareSystem "caikit-nlp" "Alternative gRPC text generation backend" "Internal ODH"
        openaiApi = softwareSystem "OpenAI-compatible API" "vLLM or llm-d chat/completions backend" "Internal ODH"
        detectors = softwareSystem "Detector Services" "Content safety detection services (HAP, etc.)" "Internal ODH"
        chunkers = softwareSystem "Chunker Services" "Text segmentation/tokenization services" "Internal ODH"
        otlpCollector = softwareSystem "OTLP Collector" "OpenTelemetry traces and metrics collector" "External"
        rhoaiOperator = softwareSystem "RHOAI rhods-operator" "Platform operator managing deployment and ingress" "Internal RHOAI"

        # Relationships
        client -> orchestrator "Sends generation/detection requests" "HTTP/HTTPS 8033/TCP, Optional TLS 1.2+"
        orchestrator -> tgis "Text generation requests" "gRPC/HTTP2, Optional TLS/mTLS"
        orchestrator -> caikitNlp "Alternative text generation" "gRPC/HTTP2, Optional TLS/mTLS"
        orchestrator -> openaiApi "Chat/text completions" "HTTP/HTTPS, Bearer API token"
        orchestrator -> detectors "Content safety detection" "HTTP/HTTPS, Optional TLS/mTLS"
        orchestrator -> chunkers "Text chunking/tokenization" "gRPC/HTTP2, Optional TLS/mTLS"
        orchestrator -> otlpCollector "Export traces and metrics" "OTLP gRPC 4317/TCP or HTTP 4318/TCP"
        rhoaiOperator -> orchestrator "Deploys and manages" "Kubernetes API, Gateway API/HTTPRoute"

        # Container-level relationships
        apiServer -> generationClient "Delegates generation"
        apiServer -> openaiClient "Delegates OpenAI calls"
        apiServer -> detectorClient "Delegates detection"
        apiServer -> chunkerClient "Delegates chunking"
        apiServer -> tlsModule "TLS/mTLS config"
        apiServer -> otelIntegration "Telemetry"
        generationClient -> tgis "Generate, GenerateStream RPCs" "gRPC/HTTP2"
        generationClient -> caikitNlp "NlpService RPCs" "gRPC/HTTP2"
        openaiClient -> openaiApi "POST /chat/completions" "HTTP/HTTPS"
        detectorClient -> detectors "POST /api/v1/text/contents" "HTTP/HTTPS"
        chunkerClient -> chunkers "ChunkersService RPCs" "gRPC/HTTP2"
        otelIntegration -> otlpCollector "OTLP export" "gRPC/HTTP"
    }

    views {
        systemContext orchestrator "SystemContext" {
            include *
            autoLayout
        }

        container orchestrator "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438dd5
                color #ffffff
            }
            element "Internal ODH" {
                background #7ed321
                color #000000
            }
            element "Internal RHOAI" {
                background #7ed321
                color #000000
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Person" {
                shape person
                background #08427b
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
