/*
 * KServe C4 Context Diagram (Structurizr DSL)
 * Generated by: Claude Opus 4.6
 * Source: architecture/rhoai-3.4/kserve.md
 */

workspace {
    model {
        user = person "Data Scientist" "Creates and deploys ML models via InferenceService CRs"
        client = person "Inference Client" "Sends prediction requests to deployed models"

        kserve = softwareSystem "KServe" "Kubernetes-native platform for deploying, managing, and serving ML models and LLM inference services" {
            controller = container "kserve-controller-manager" "Reconciles InferenceService, InferenceGraph, TrainedModel CRs; creates Deployments, Services, HTTPRoutes, VirtualServices, kube-rbac-proxy sidecars" "Go Operator (controller-runtime)"
            llmController = container "llmisvc-controller-manager" "Reconciles LLMInferenceService CRs; creates LeaderWorkerSets, InferencePools, InferenceModels, scheduler components" "Go Operator (controller-runtime)"
            webhookServer = container "Webhook Server" "Validates and mutates InferenceService, ServingRuntime, and Pod resources" "HTTPS/9443"
            storageInitializer = container "Storage Initializer" "Downloads model artifacts from cloud storage (S3, GCS, Azure) into model serving containers" "Go Init Container"
            kserveAgent = container "KServe Agent" "Sidecar for logging, batching, and multi-model serving" "Go Sidecar"
            kserveRouter = container "KServe Router" "InferenceGraph router for DAG-based inference pipelines" "Go Sidecar"
            kubeRbacProxy = container "kube-rbac-proxy" "Authentication/authorization sidecar proxy for inference pods" "Sidecar (8443/TCP)"
        }

        gatewayAPI = softwareSystem "OpenShift Gateway (Gateway API)" "Envoy-based gateway for external ingress via HTTPRoute CRs" "External"
        istio = softwareSystem "Istio" "Service mesh for optional VirtualService-based routing" "External (Optional)"
        knative = softwareSystem "Knative Serving" "Serverless autoscaling platform (optional mode)" "External (Optional)"
        keda = softwareSystem "KEDA" "Event-driven autoscaling via ScaledObject CRs" "External (Optional)"
        certManager = softwareSystem "OpenShift service-ca" "Automatic TLS certificate provisioning for webhooks and serving certs" "External"
        gatewayInfExt = softwareSystem "Gateway API Inference Extensions" "InferencePool/InferenceModel CRDs for LLM-specific routing" "External"
        leaderWorkerSet = softwareSystem "LeaderWorkerSet" "Multi-node inference workload management" "External (Optional)"

        rhodsOperator = softwareSystem "rhods-operator" "Deploys KServe manifests via kustomize overlays; manages Gateway" "Internal RHOAI"
        odhDashboard = softwareSystem "ODH Dashboard" "UI for managing inference services and serving runtimes" "Internal RHOAI"
        kubeAuthProxy = softwareSystem "ODH kube-auth-proxy" "Provides kube-rbac-proxy image for sidecar injection" "Internal RHOAI"

        s3Storage = softwareSystem "S3-compatible Storage" "Model artifact storage (AWS S3, MinIO)" "External Service"
        gcsStorage = softwareSystem "Google Cloud Storage" "Model artifact storage" "External Service"
        azureStorage = softwareSystem "Azure Blob Storage" "Model artifact storage" "External Service"
        k8sAPI = softwareSystem "Kubernetes API Server" "Cluster API for CR watch/reconcile and resource management" "Infrastructure"

        llmdScheduler = softwareSystem "llm-d Inference Scheduler" "LLM inference request scheduling and load balancing" "External"
        wva = softwareSystem "Workload Variant Autoscaler" "VariantAutoscaling for LLM workloads" "External (Optional)"

        # Relationships
        user -> kserve "Creates InferenceService / LLMInferenceService CRs via kubectl/dashboard"
        client -> gatewayAPI "Sends prediction requests" "HTTPS/443"
        gatewayAPI -> kserve "Routes to inference pods via HTTPRoute" "HTTP/8443 or HTTP/80"

        kserve -> k8sAPI "Watches CRs, creates resources" "HTTPS/443"
        kserve -> gatewayAPI "Creates HTTPRoute CRs referencing parent Gateway"
        kserve -> istio "Creates VirtualService CRs (optional)" "N/A"
        kserve -> knative "Creates Knative Service CRs (optional)" "N/A"
        kserve -> keda "Creates ScaledObject CRs" "N/A"
        kserve -> certManager "Uses for webhook and serving TLS certs"
        kserve -> gatewayInfExt "Creates InferencePool/InferenceModel CRs" "N/A"
        kserve -> leaderWorkerSet "Creates LeaderWorkerSet CRs for multi-node inference" "N/A"
        kserve -> s3Storage "Downloads model artifacts" "HTTPS/443"
        kserve -> gcsStorage "Downloads model artifacts" "HTTPS/443"
        kserve -> azureStorage "Downloads model artifacts" "HTTPS/443"
        kserve -> llmdScheduler "Integrates for LLM request scheduling" "HTTP/8080"
        kserve -> wva "Creates VariantAutoscaling CRs" "N/A"

        rhodsOperator -> kserve "Deploys via kustomize overlays; injects RELATED_IMAGE_* env vars"
        odhDashboard -> kserve "UI management of InferenceServices"
        kubeAuthProxy -> kserve "Provides kube-rbac-proxy image"
    }

    views {
        systemContext kserve "SystemContext" {
            include *
            autoLayout
        }

        container kserve "Containers" {
            include *
            autoLayout
        }

        styles {
            element "External" {
                background #999999
                color #ffffff
            }
            element "External (Optional)" {
                background #bbbbbb
                color #ffffff
                border dashed
            }
            element "External Service" {
                background #f5a623
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Infrastructure" {
                background #4a90e2
                color #ffffff
            }
            element "Software System" {
                background #4a90e2
                color #ffffff
            }
            element "Person" {
                background #08427b
                color #ffffff
                shape person
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
