// C4 Context Diagram: llama-stack-provider-trustyai-garak
// Generated by: Claude Opus 4.6
// Source: architecture/rhoai-3.4/llama-stack-provider-trustyai-garak.md

workspace {
    model {
        user = person "Data Scientist / ML Engineer" "Submits LLM vulnerability scans and reviews compliance reports"

        garakProvider = softwareSystem "TrustyAI Garak Llama Stack Provider" "Automated LLM red-teaming and vulnerability assessment via Garak framework" {
            remoteAdapter = container "GarakRemoteEvalAdapter" "Orchestrates Garak scans via Kubeflow Pipelines; submits 6-step pipeline DAGs" "Python Provider"
            inlineAdapter = container "GarakInlineEvalAdapter" "Runs Garak scans as local subprocesses within Llama Stack server" "Python Provider"
            evalBase = container "GarakEvalBase" "Shared evaluation logic: benchmark registration, config merge, command building, result parsing" "Python Base Class"
            shieldOrchestrator = container "SimpleShieldOrchestrator" "Orchestrates input/output shield checks around LLM inference" "Python Callable"
            kfpPipeline = container "KFP Pipeline" "6-step DAG: validate, resolve_taxonomy, sdg_generate, prepare_prompts, garak_scan, parse_results" "Kubeflow Pipeline"
            scanConfig = container "GarakScanConfig" "Predefined benchmark profiles: OWASP, AVID, CWE, quality, intents" "Pydantic Model"
            evalHubAdapter = container "EvalHub Garak Adapter" "Integrates Garak with eval-hub platform; simple and KFP execution modes" "Python Adapter"
            containerImage = container "Container Image" "UBI9/Python 3.12 with Garak pre-installed; base image for KFP pods" "OCI Container"
        }

        llamaStack = softwareSystem "Llama Stack Distribution" "Hosts provider plugins, exposes Llama Stack server APIs" "Internal RHOAI"
        dspa = softwareSystem "Data Science Pipelines Application (DSPA)" "Kubeflow Pipelines on OpenShift AI" "Internal RHOAI"
        vllm = softwareSystem "vLLM / Model Serving" "Target LLM inference endpoint under evaluation" "Internal RHOAI"
        trustyaiOp = softwareSystem "TrustyAI Service Operator" "Provides garak-provider-image ConfigMap" "Internal RHOAI"
        llamaStackOp = softwareSystem "Llama Stack Operator" "Manages LlamaStackDistribution CR deployments" "Internal RHOAI"
        postgresql = softwareSystem "PostgreSQL" "Persistent storage for Llama Stack Files API" "Internal"
        s3 = softwareSystem "S3 / MinIO Object Storage" "KFP artifact storage" "External"
        garak = softwareSystem "NVIDIA Garak" "LLM vulnerability scanning framework" "External Library"
        evalHub = softwareSystem "eval-hub" "Evaluation platform for ML model assessments" "Internal RHOAI"

        // User interactions
        user -> garakProvider "Submits vulnerability scans via Llama Stack Eval API"
        user -> llamaStack "Accesses Llama Stack APIs" "HTTP/8321"

        // Provider interactions
        garakProvider -> llamaStack "Hosted as provider plugin" "HTTP/8321"
        garakProvider -> dspa "Submits and monitors KFP pipeline runs" "HTTPS/443 Bearer Token"
        garakProvider -> vllm "Target model for vulnerability scanning" "HTTPS/443 API Key"
        garakProvider -> postgresql "Files API persistent storage" "TCP/5432 Password"
        garakProvider -> s3 "KFP artifact storage (evalhub mode)" "HTTPS/443 AWS Keys"
        garakProvider -> evalHub "Framework adapter integration" "ConfigMap/sidecar"

        // Internal relationships
        remoteAdapter -> evalBase "extends"
        inlineAdapter -> evalBase "extends"
        remoteAdapter -> kfpPipeline "submits pipeline DAGs"
        kfpPipeline -> shieldOrchestrator "shield-augmented scans"
        evalBase -> scanConfig "uses benchmark profiles"

        // External references
        trustyaiOp -> garakProvider "Provides container image reference" "ConfigMap"
        llamaStackOp -> llamaStack "Manages deployment" "LlamaStackDistribution CR"
    }

    views {
        systemContext garakProvider "SystemContext" {
            include *
            autoLayout
        }

        container garakProvider "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438dd5
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "External Library" {
                background #999999
                color #ffffff
            }
            element "Internal" {
                background #7ed321
                color #ffffff
            }
            element "Person" {
                background #08427b
                color #ffffff
                shape person
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
