// C4 Context Diagram: llm-d Inference Scheduler
// Generated by: Claude Opus 4.6

workspace {
    model {
        client = person "Client Application" "Sends LLM inference requests (chat completions, completions)"

        llmdScheduler = softwareSystem "llm-d Inference Scheduler" "Inference request routing scheduler for LLM workloads via Gateway API Inference Extension" {
            epp = container "EPP (Endpoint Picker)" "Receives inference requests from Envoy via gRPC ext-proc, selects optimal backend pods using pluggable filter/scorer plugins" "Go Service (ext-proc)" "Component"
            pdSidecar = container "P/D Routing Sidecar" "Runs alongside vLLM engines; orchestrates disaggregated prefill/decode by proxying requests between workers" "Go Reverse Proxy" "Component"
            udsTokenizer = container "UDS Tokenizer Sidecar" "Handles tokenization via gRPC over Unix Domain Socket for precise prefix cache scoring" "Container (sidecar)" "Component"
            filterPlugins = container "Filter Plugins" "Exclude candidate pods based on labels, roles, selectors (by-label, by-label-selector, decode-filter, prefill-filter)" "Go Plugin Framework" "Component"
            scorerPlugins = container "Scorer Plugins" "Score candidate pods (precise-prefix-cache, load-aware, active-request, session-affinity, no-hit-lru)" "Go Plugin Framework" "Component"
            profileHandlers = container "Profile Handlers" "Determine scheduling profiles per request (single, P/D disaggregated, data-parallel)" "Go Plugin Framework" "Component"
            ssrfValidator = container "SSRF Allowlist Validator" "Watches InferencePool/Pod resources to maintain allowlist of valid prefill targets" "Go Component" "Security"
        }

        envoyGateway = softwareSystem "Envoy Gateway" "Data plane proxy with ext-proc support for routing decisions" "External"
        gatewayAPI = softwareSystem "Gateway API" "Kubernetes Gateway API (Gateway, HTTPRoute, InferencePool resources)" "External"
        gie = softwareSystem "Gateway API Inference Extension (GIE)" "Core scheduling framework providing InferencePool, EPP runner, plugin interface" "External"
        vllm = softwareSystem "vLLM" "LLM inference engine for model serving" "External"
        kvCache = softwareSystem "llm-d-kv-cache" "KV-cache indexing for precise prefix cache scorer" "Internal"
        zeromq = softwareSystem "ZeroMQ (KV-Events)" "Real-time KV-cache state update subscription" "External"
        k8sAPI = softwareSystem "Kubernetes API Server" "Kubernetes control plane for resource watching" "External"
        prometheus = softwareSystem "Prometheus" "Metrics collection and monitoring" "External"

        // Relationships
        client -> envoyGateway "Sends inference requests" "HTTP/80"
        envoyGateway -> epp "Sends ext-proc routing requests" "gRPC/9002"
        epp -> envoyGateway "Returns routing decisions" "gRPC/9002"
        envoyGateway -> pdSidecar "Forwards requests to decode worker" "HTTP(S)/8000"
        envoyGateway -> vllm "Forwards requests (non-disaggregated)" "HTTP/8000"

        epp -> filterPlugins "Applies filters"
        epp -> scorerPlugins "Applies scorers"
        epp -> profileHandlers "Selects profile"
        epp -> udsTokenizer "Tokenization requests" "gRPC/UDS"
        epp -> k8sAPI "Watches InferencePool, Pods" "HTTPS/443"

        pdSidecar -> ssrfValidator "Validates prefill targets"
        pdSidecar -> vllm "Sends prefill/decode requests" "HTTP(S)/8001"
        ssrfValidator -> k8sAPI "Watches InferencePool, Pods" "HTTPS/443"

        zeromq -> epp "KV-cache event stream" "ZMQ/5556"
        kvCache -> epp "KV-cache index data"
        prometheus -> epp "Scrapes metrics" "HTTP/9090"
    }

    views {
        systemContext llmdScheduler "SystemContext" {
            include *
            autoLayout
        }

        container llmdScheduler "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438dd5
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal" {
                background #7ed321
                color #ffffff
            }
            element "Person" {
                background #08427b
                color #ffffff
                shape person
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
            element "Component" {
                background #4a90e2
                color #ffffff
            }
            element "Security" {
                background #e74c3c
                color #ffffff
            }
        }
    }
}
