/*
 * C4 Context Diagram - Model Metadata Collection
 * Generated by: Claude Opus 4.6
 *
 * View with Structurizr:
 *   docker run -p 8080:8080 -v .:/usr/local/structurizr structurizr/lite
 *   OR: https://structurizr.com/dsl
 */

workspace {
    model {
        ciEngineer = person "CI/CD Engineer" "Maintains build pipelines and model catalog updates"
        dataScientist = person "Data Scientist" "Browses available models via RHOAI Dashboard"

        modelMetadataCollection = softwareSystem "Model Metadata Collection" "Build-time Go CLI that extracts, enriches, and catalogs metadata from Red Hat AI container images, producing static YAML catalogs shipped as a data-only container" {
            modelExtractor = container "model-extractor" "Main CLI tool: discovers HuggingFace collections, fetches OCI layers, extracts model cards, enriches metadata, generates catalogs" "Go CLI"
            metadataReport = container "metadata-report" "Analyzes metadata completeness and quality metrics across generated catalogs" "Go CLI"
            dataContainer = container "Data Container Image" "Minimal ubi9-based container packaging pre-generated YAML catalog files at /app/data; runs sleep infinity" "OCI Container (ubi9-minimal)"
        }

        huggingFace = softwareSystem "HuggingFace" "ML model hub providing collection discovery, model metadata, and README files" "External"
        redHatRegistry = softwareSystem "Red Hat Container Registry" "Source of OCI modelcar container images with embedded model card layers" "External"
        quayRegistry = softwareSystem "Quay.io" "Container image registry for storing built data container images" "External"

        dashboard = softwareSystem "RHOAI Dashboard" "Web UI for managing and browsing AI/ML resources" "Internal RHOAI"
        modelRegistry = softwareSystem "Model Registry" "Stores and serves model metadata" "Internal RHOAI"
        konflux = softwareSystem "Konflux CI" "Tekton-based CI/CD pipeline for RHOAI releases" "External"
        githubActions = softwareSystem "GitHub Actions" "CI/CD for development builds" "External"

        # Build-time relationships
        ciEngineer -> modelMetadataCollection "Triggers builds and reviews catalog output"
        modelExtractor -> huggingFace "Fetches model collections and README files" "HTTPS/443, TLS 1.2+, No auth"
        modelExtractor -> redHatRegistry "Fetches OCI manifests and model card layers" "HTTPS/443, TLS 1.2+, Docker auth"
        modelExtractor -> dataContainer "Generates catalog YAML files packaged into container" "File I/O"
        metadataReport -> dataContainer "Analyzes catalog completeness" "File I/O"

        githubActions -> modelMetadataCollection "Builds on push to main" "CI/CD trigger"
        konflux -> modelMetadataCollection "Builds on push to rhoai-3.4" "Tekton PipelineRun"
        modelMetadataCollection -> quayRegistry "Pushes built data container images" "HTTPS/443, TLS 1.2+, Username/Password"

        # Runtime relationships
        dashboard -> dataContainer "Mounts catalog data via volume mount at /app/data" "Volume mount, File I/O"
        dataScientist -> dashboard "Browses available models"
        modelMetadataCollection -> modelRegistry "Catalog format compatible with Model Registry" "MetadataStringValue format"
    }

    views {
        systemContext modelMetadataCollection "SystemContext" {
            include *
            autoLayout
        }

        container modelMetadataCollection "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438dd5
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Person" {
                shape person
                background #08427b
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
