// C4 Context Diagram - Notebooks (Workbench Images)
// Generated by: Claude Opus 4.6
// Source: architecture/rhoai-3.4/notebooks.md

workspace {
    model {
        dataScientist = person "Data Scientist" "Uses interactive workbenches for ML development and experimentation"

        notebooks = softwareSystem "Notebooks (Workbench Images)" "Builds and ships container images for interactive data science workbenches (JupyterLab, Code-Server, RStudio) and Elyra pipeline runtime images" {
            jupyterImages = container "Jupyter Workbench Images" "JupyterLab variants: Minimal, Data Science, PyTorch, TensorFlow, TrustyAI, LLMCompressor" "Container Images (UBI9, Python 3.12/3.11)"
            codeServerImage = container "Code-Server Image" "VS Code in browser with nginx+httpd idle culling proxy chain" "Container Image (UBI9, Python 3.12)"
            rstudioImage = container "RStudio Image" "RStudio Server IDE with R and Python, nginx+httpd idle culling" "Container Image (UBI9, Python 3.12)"
            runtimeImages = container "Pipeline Runtime Images" "Elyra pipeline execution runtimes: Minimal, DataScience, PyTorch, TensorFlow, LLMCompressor" "Container Images (UBI9)"
            gpuBaseImages = container "GPU Base Images" "CUDA 12.6-13.0 and ROCm 6.2-6.4 base images for GPU workbenches" "Container Images"
            kustomizeManifests = container "Kustomize ImageStream Manifests" "OpenShift ImageStream definitions with version tags (N through N-7)" "YAML/Kustomize"
        }

        // Internal ODH Systems
        rhodsOperator = softwareSystem "rhods-operator" "Deploys ImageStream manifests to cluster, injects RELATED_IMAGE refs" "Internal ODH"
        notebookController = softwareSystem "odh-notebook-controller" "Pod mutation webhook: injects kube-rbac-proxy sidecar, CA certs, runtime ConfigMap" "Internal ODH"
        odhDashboard = softwareSystem "ODH Dashboard" "Discovers workbench images via ImageStream annotations for user selection" "Internal ODH"
        dsPipelines = softwareSystem "Data Science Pipelines" "Executes notebook pipeline nodes using runtime images" "Internal ODH"
        elyra = softwareSystem "Elyra" "Visual pipeline editor JupyterLab extension (ODH fork)" "Internal ODH"

        // External Systems
        openshift = softwareSystem "OpenShift Container Platform" "Target platform for workbench pods (v4.19-v4.21)" "External"
        kubernetesAPI = softwareSystem "Kubernetes API" "Cluster API server for resource management" "External"
        registryRHI = softwareSystem "registry.redhat.io" "Current release image registry (22 images)" "External"
        quayModh = softwareSystem "quay.io/modh" "Legacy release image registry (34 images)" "External"
        s3Storage = softwareSystem "S3-compatible Storage" "Model and data artifact storage" "External"
        konflux = softwareSystem "Tekton/Konflux" "CI/CD pipeline for building container images" "External"
        nvidiaGPU = softwareSystem "NVIDIA CUDA" "GPU acceleration runtime (12.6-13.0)" "External"
        amdROCm = softwareSystem "AMD ROCm" "GPU acceleration runtime (6.2-6.4)" "External"

        // Relationships - User
        dataScientist -> notebooks "Uses workbenches for ML development"
        dataScientist -> odhDashboard "Selects workbench image"

        // Relationships - Internal
        rhodsOperator -> notebooks "Deploys ImageStream manifests via kustomize"
        notebookController -> notebooks "Injects sidecars, creates Services/HTTPRoutes"
        odhDashboard -> notebooks "Discovers images via annotations" "HTTPS/6443"
        dsPipelines -> notebooks "Uses pipeline runtime images for node execution" "HTTPS/8443"
        elyra -> notebooks "Embedded as JupyterLab extension"
        notebooks -> rhodsOperator "Provides kustomize manifests"

        // Relationships - External
        notebooks -> openshift "Runs on" "Pods"
        notebooks -> kubernetesAPI "API interactions from workbenches" "HTTPS/6443"
        notebooks -> s3Storage "Data access via Boto3" "HTTPS/443"
        rhodsOperator -> registryRHI "Imports current images" "HTTPS/443"
        rhodsOperator -> quayModh "Imports legacy images" "HTTPS/443"
        konflux -> notebooks "Builds container images" "CI/CD"
        notebooks -> nvidiaGPU "CUDA GPU acceleration"
        notebooks -> amdROCm "ROCm GPU acceleration"
    }

    views {
        systemContext notebooks "SystemContext" {
            include *
            autoLayout
        }

        container notebooks "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438dd5
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal ODH" {
                background #7ed321
                color #ffffff
            }
            element "Person" {
                background #08427b
                color #ffffff
                shape person
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
