// C4 Context Diagram: pipelines-components
// Generated by: Claude Opus 4.6

workspace {
    model {
        dataScientist = person "Data Scientist" "Creates and runs ML training pipelines"
        mlEngineer = person "ML Engineer" "Builds and maintains pipeline components"

        pipelinesComponents = softwareSystem "Pipelines Components" "Reusable KFP component library for LLM fine-tuning, AutoML, evaluation, and model registration" {
            dataProcessing = container "Data Processing Components" "dataset_download, automl_data_loader, tabular_train_test_split, yoda_data_processor" "KFP Python Components"
            trainingComponents = container "Training Components" "train_model (OSFT/SFT/LoRA/finetuning)" "KFP Python Components"
            evaluationComponents = container "Evaluation Components" "universal_llm_evaluator, models_selection, autogluon_models_full_refit, leaderboard_evaluation" "KFP Python Components"
            deploymentComponents = container "Deployment Components" "kubeflow_model_registry" "KFP Python Component"
            prebuiltPipelines = container "Pre-built Pipelines" "OSFT, SFT, LoRA, AutoGluon pipelines" "KFP Pipeline Definitions"
            automlContainer = container "odh-automl-rhel9" "Container with AutoGluon, PyTorch CPU, ML libs" "Container Image"
        }

        kubeflowPipelines = softwareSystem "Kubeflow Pipelines" "Pipeline orchestration and task scheduling" "Internal ODH"
        kubeflowTrainer = softwareSystem "Kubeflow Trainer" "Distributed training job management (TrainingHub)" "Internal ODH"
        modelRegistry = softwareSystem "Kubeflow Model Registry" "Model metadata and version storage" "Internal ODH"
        odhTrainingImages = softwareSystem "ODH Training Hub Base Images" "Pre-built ML framework images" "Internal ODH"

        huggingfaceHub = softwareSystem "HuggingFace Hub" "Dataset and model repository" "External"
        s3Storage = softwareSystem "AWS S3 / MinIO" "Object storage for training data" "External"
        ociRegistry = softwareSystem "OCI Container Registry" "OCI model image storage" "External"
        kubernetesAPI = softwareSystem "Kubernetes API Server" "Cluster API for job submission" "External"

        // User interactions
        dataScientist -> pipelinesComponents "Runs pipelines via KFP UI/SDK"
        mlEngineer -> pipelinesComponents "Develops and maintains components"

        // Internal pipeline flow
        prebuiltPipelines -> dataProcessing "Step 1: Download/load data"
        prebuiltPipelines -> trainingComponents "Step 2: Train model"
        prebuiltPipelines -> evaluationComponents "Step 3: Evaluate model"
        prebuiltPipelines -> deploymentComponents "Step 4: Register model"

        // Platform dependencies
        pipelinesComponents -> kubeflowPipelines "Executes as KFP tasks" "KFP SDK"
        trainingComponents -> kubeflowTrainer "Submits distributed training jobs" "HTTPS/6443 + Bearer Token"
        deploymentComponents -> modelRegistry "Registers models with provenance" "HTTP/8080 (plaintext)"
        trainingComponents -> odhTrainingImages "Uses as base container images"

        // External dependencies
        dataProcessing -> huggingfaceHub "Downloads datasets and models" "HTTPS/443 + HF_TOKEN"
        dataProcessing -> s3Storage "Loads training data" "HTTPS/443 + AWS IAM"
        trainingComponents -> ociRegistry "Pulls OCI model images" "HTTPS/443 + Docker auth"
        trainingComponents -> kubernetesAPI "Submits TrainingJobs" "HTTPS/6443 + Bearer Token"
    }

    views {
        systemContext pipelinesComponents "SystemContext" {
            include *
            autoLayout
        }

        container pipelinesComponents "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Person" {
                shape Person
                background #08427b
                color #ffffff
            }
            element "Software System" {
                background #1168bd
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal ODH" {
                background #7ed321
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
