/*
 * C4 Context Diagram - Red Hat OpenShift AI 3.4
 * Generated by: Claude Opus 4.6
 */

workspace {
    model {
        // Personas
        dataScientist = person "Data Scientist" "Develops, trains, and deploys ML models using workbenches and pipelines"
        mlEngineer = person "ML Engineer" "Manages model serving infrastructure, pipelines, and training jobs"
        platformAdmin = person "Platform Admin" "Installs and manages the RHOAI platform via DataScienceCluster CR"
        securityTeam = person "Security / Compliance" "Reviews security posture, RBAC, and network policies"

        // Core Platform
        rhoai = softwareSystem "Red Hat OpenShift AI 3.4" "Enterprise AI/ML platform on OpenShift providing full ML lifecycle management" {
            rhodsOperator = container "rhods-operator" "Central meta-operator managing all platform components via DataScienceCluster CR" "Go OLM Operator"
            dashboard = container "ODH Dashboard" "Web-based management console with module federation UI architecture" "React/Node.js Web Application"
            notebookController = container "Notebook Controller" "Manages notebook workbench instances with OpenShift integrations" "Go Controller"

            kserve = container "KServe" "Model serving controller for InferenceService and LLMInferenceService" "Go Operator"
            modelController = container "odh-model-controller" "Automates model serving infrastructure (routes, monitoring, auth, certs)" "Go Controller"
            llmdScheduler = container "llm-d Inference Scheduler" "Optimized endpoint selection for LLM inference workloads" "Go Service"
            wva = container "Workload-Variant Autoscaler" "Global autoscaler for inference model servers using KV cache metrics" "Go Operator"

            dspo = container "DSP Operator" "Manages lifecycle of Kubeflow Pipelines v2 infrastructure" "Go Operator"
            dsp = container "Data Science Pipelines" "Pipeline orchestration, scheduling, and management (KFP v2)" "Go/Python Multi-component"
            argo = container "Argo Workflows" "Workflow execution engine for pipeline runs" "Go Workflow Engine"
            mlmd = container "ML Metadata" "Records and retrieves metadata for ML workflows" "C++ gRPC Service"

            modelRegistryOp = container "Model Registry Operator" "Manages Model Registry and Model Catalog instances" "Go Operator"
            modelRegistry = container "Model Registry" "Central metadata repository for ML model versioning" "Go REST Service"
            mlflowOp = container "MLflow Operator" "Manages MLflow tracking server instances" "Go Operator"
            mlflow = container "MLflow" "Experiment tracking, model registry, AI gateway" "Python Application"

            trainingOp = container "Training Operator" "Distributed training jobs (PyTorch, TF, XGBoost, MPI, JAX)" "Go Operator"
            trainer = container "Kubeflow Trainer" "Next-gen training jobs with TrainJob/TrainingRuntime APIs" "Go Operator"
            kuberay = container "KubeRay Operator" "Manages Ray clusters, jobs, and services" "Go Operator"
            sparkOp = container "Spark Operator" "Manages Apache Spark applications" "Go Operator"

            trustyaiOp = container "TrustyAI Operator" "Manages AI trustworthiness, evaluation, and guardrails infrastructure" "Go Operator"
            trustyai = container "TrustyAI Explainability" "AI fairness metrics, bias tracking, model drift detection" "Java Service"
            evalHub = container "EvalHub" "LLM evaluation orchestration control plane" "Go REST API"
            guardrailsOrch = container "FMS Guardrails Orchestrator" "Coordinates AI text generation with content safety guardrails" "Rust Service"
            nemoGuardrails = container "NeMo Guardrails" "Programmable guardrails for LLM-based systems" "Python Service"

            feastOp = container "Feast Operator" "Manages Feast feature store lifecycle" "Go Operator"
            llamaOp = container "Llama Stack Operator" "Manages Llama Stack server distributions" "Go Operator"
            maas = container "Models-as-a-Service" "API key management, subscription-based model access control" "Go Operator + Service"
            batchGateway = container "Batch Gateway" "OpenAI-compatible batch inference API gateway" "Go Service"

            gateway = container "data-science-gateway" "Central Gateway API ingress point for all platform services" "Envoy Gateway"
            kubeAuthProxy = container "kube-auth-proxy" "FIPS-compliant OAuth2/OIDC authentication and RBAC authorization proxy" "Go Proxy"
        }

        // External Dependencies
        ocp = softwareSystem "OpenShift Container Platform" "Base Kubernetes platform (v4.19-v4.21)" "External"
        olm = softwareSystem "OLM" "Operator Lifecycle Manager" "External"
        kueue = softwareSystem "Kueue" "Kubernetes-native job queueing" "External"
        kuadrant = softwareSystem "Kuadrant" "API management (Authorino + Limitador)" "External"

        // External Services
        s3 = softwareSystem "S3/GCS/Azure Blob" "Object storage for model artifacts, pipeline artifacts, checkpoints" "External Service"
        hfHub = softwareSystem "HuggingFace Hub" "Model and dataset repository" "External Service"
        nvidiaApi = softwareSystem "NVIDIA NIM API" "NIM model catalog (integrate.api.nvidia.com)" "External Service"
        extLlmApis = softwareSystem "External LLM APIs" "Upstream LLM inference services" "External Service"
        containerRegistries = softwareSystem "Container Registries" "OCI image registries (disconnected supported)" "External Service"

        // Relationships - Personas
        dataScientist -> rhoai "Develops models, runs pipelines, deploys inference" "HTTPS/443"
        mlEngineer -> rhoai "Manages serving infrastructure, training jobs" "HTTPS/443"
        platformAdmin -> rhoai "Configures platform via DataScienceCluster CR" "kubectl/oc"
        securityTeam -> rhoai "Reviews RBAC, network policies, compliance" "Audit"

        dataScientist -> dashboard "Accesses web UI" "HTTPS/443 via Gateway API"
        dataScientist -> kserve "Creates InferenceService CRs" "kubectl/oc"
        dataScientist -> dsp "Creates and runs ML pipelines" "HTTPS/443"
        dataScientist -> mlflow "Tracks experiments" "HTTPS/443"
        platformAdmin -> rhodsOperator "Creates DataScienceCluster CR" "Kubernetes API"

        // Internal relationships
        rhodsOperator -> kserve "Deploys via kustomize manifests"
        rhodsOperator -> dspo "Deploys via kustomize manifests"
        rhodsOperator -> modelRegistryOp "Deploys via kustomize manifests"
        rhodsOperator -> mlflowOp "Deploys via kustomize manifests"
        rhodsOperator -> trainingOp "Deploys via kustomize manifests"
        rhodsOperator -> trainer "Deploys via kustomize manifests"
        rhodsOperator -> kuberay "Deploys via kustomize manifests"
        rhodsOperator -> trustyaiOp "Deploys via kustomize manifests"
        rhodsOperator -> feastOp "Deploys via kustomize manifests"
        rhodsOperator -> llamaOp "Deploys via kustomize manifests"
        rhodsOperator -> dashboard "Deploys via kustomize manifests"
        rhodsOperator -> notebookController "Deploys via kustomize manifests"
        rhodsOperator -> maas "Deploys via kustomize manifests"
        rhodsOperator -> batchGateway "Deploys via kustomize manifests"

        kserve -> llmdScheduler "LLM routing optimization"
        kserve -> wva "Autoscaling"
        modelController -> kserve "Watches InferenceService CRs"
        modelController -> modelRegistry "REST API integration"
        dspo -> dsp "Manages instances"
        dsp -> argo "Creates Workflow CRs"
        dsp -> mlmd "Lineage tracking"
        modelRegistryOp -> modelRegistry "Manages instances"
        mlflowOp -> mlflow "Manages instances"
        trustyaiOp -> evalHub "Manages instances"
        trustyaiOp -> guardrailsOrch "Manages instances"
        trustyaiOp -> nemoGuardrails "Manages instances"

        gateway -> dashboard "Routes via HTTPRoute"
        gateway -> kserve "Routes via HTTPRoute"
        gateway -> mlflow "Routes via HTTPRoute"
        gateway -> modelRegistry "Routes via HTTPRoute"
        kubeAuthProxy -> gateway "ext_authz authentication"

        // External dependencies
        rhoai -> ocp "Runs on" "Kubernetes API"
        rhodsOperator -> olm "Deployed via" "OLM"
        trainingOp -> kueue "Quota management"
        maas -> kuadrant "Auth + Rate Limiting"

        // External service dependencies
        kserve -> s3 "Downloads model artifacts" "HTTPS/443"
        dsp -> s3 "Pipeline artifact storage" "HTTPS/443"
        modelRegistry -> hfHub "Model metadata retrieval" "HTTPS/443"
        modelController -> nvidiaApi "NIM model catalog" "HTTPS/443"
        nemoGuardrails -> extLlmApis "Upstream LLM inference" "HTTPS/443"
        rhoai -> containerRegistries "Pulls container images" "HTTPS/443"
    }

    views {
        systemContext rhoai "PlatformContext" {
            include *
            autoLayout
        }

        container rhoai "PlatformContainers" {
            include *
            autoLayout
        }

        styles {
            element "Person" {
                shape Person
                background #08427b
                color #ffffff
            }
            element "Software System" {
                background #1168bd
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "External Service" {
                background #f5a623
                color #000000
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
