// TrustyAI Service Operator - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6
// Source: architecture/rhoai-3.4/trustyai-service-operator.md

workspace {
    model {
        dataScientist = person "Data Scientist" "Creates ML models, runs evaluations, configures guardrails"
        mlEngineer = person "ML Engineer" "Deploys inference services, monitors model fairness"
        securityEngineer = person "Security Engineer" "Configures content safety guardrails and policies"

        trustyaiOperator = softwareSystem "TrustyAI Service Operator" "Multi-controller operator managing AI trustworthiness, evaluation, and guardrails infrastructure" {
            operatorManager = container "Operator Manager" "Main entrypoint running all controllers with leader election" "Go Binary"
            tasController = container "TAS Controller" "Reconciles TrustyAIService CRs for model explainability" "Go Controller"
            lmesController = container "LMES Controller" "Reconciles LMEvalJob CRs for LLM evaluation" "Go Controller"
            jobMgrController = container "Job Manager Controller" "Kueue integration for LMEval workload scheduling" "Go Controller"
            gorchController = container "GORCH Controller" "Reconciles GuardrailsOrchestrator CRs for inference protection" "Go Controller"
            nemoController = container "NEMO Controller" "Reconciles NemoGuardrails CRs for NeMo server management" "Go Controller"
            evalhubController = container "EVALHUB Controller" "Reconciles EvalHub CRs for centralized evaluation orchestration" "Go Controller"
        }

        // External Dependencies
        kserve = softwareSystem "KServe" "Standardized serverless ML inference platform" "External"
        kueue = softwareSystem "Kueue" "Job queue management for batch workloads" "External"
        istio = softwareSystem "Istio Service Mesh" "Traffic management, mTLS, and routing" "External"
        prometheus = softwareSystem "Prometheus" "Metrics collection and monitoring" "External"
        openShift = softwareSystem "OpenShift Platform" "Container platform providing Routes, serving certs, RBAC" "External"
        kubeRbacProxy = softwareSystem "kube-rbac-proxy" "Authentication sidecar enforcing RBAC via SubjectAccessReview" "External"

        // Internal ODH Dependencies
        rhodsOperator = softwareSystem "RHODS Operator" "Deploys TrustyAI operator via Kustomize overlays" "Internal ODH"
        odhDashboard = softwareSystem "ODH Dashboard" "Web UI for managing data science projects" "Internal ODH"
        mlflow = softwareSystem "MLFlow" "Experiment tracking for evaluation results" "Internal ODH"
        modelMesh = softwareSystem "ModelMesh Serving" "Multi-model inference serving platform" "Internal ODH"

        // Relationships - Users
        dataScientist -> trustyaiOperator "Creates LMEvalJob, EvalHub CRs via kubectl/dashboard"
        mlEngineer -> trustyaiOperator "Creates TrustyAIService CRs for model monitoring"
        securityEngineer -> trustyaiOperator "Creates GuardrailsOrchestrator, NemoGuardrails CRs"
        odhDashboard -> trustyaiOperator "Manages TrustyAI services via UI"

        // Relationships - Internal containers
        operatorManager -> tasController "Runs"
        operatorManager -> lmesController "Runs"
        operatorManager -> jobMgrController "Runs"
        operatorManager -> gorchController "Runs"
        operatorManager -> nemoController "Runs"
        operatorManager -> evalhubController "Runs"

        // Relationships - External
        trustyaiOperator -> kserve "Watches/patches InferenceService CRs" "K8s API/HTTPS/443"
        trustyaiOperator -> kueue "Creates Workload CRs for job scheduling" "K8s API/HTTPS/443"
        trustyaiOperator -> istio "Creates VirtualServices, DestinationRules" "K8s API/HTTPS/443"
        trustyaiOperator -> prometheus "Exposes metrics via ServiceMonitor" "HTTP/8080, HTTPS/8443"
        trustyaiOperator -> openShift "Creates Routes, uses serving certs" "K8s API/HTTPS/443"
        trustyaiOperator -> kubeRbacProxy "Deploys as sidecar for RBAC enforcement" "HTTPS/8443"
        trustyaiOperator -> modelMesh "Injects payload processor env vars" "K8s API/HTTPS/443"
        trustyaiOperator -> mlflow "Integrates for experiment tracking" "HTTPS"
        rhodsOperator -> trustyaiOperator "Deploys via Kustomize overlays"
    }

    views {
        systemContext trustyaiOperator "SystemContext" {
            include *
            autoLayout
        }

        container trustyaiOperator "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Person" {
                shape Person
                background #08427b
                color #ffffff
            }
            element "Software System" {
                background #1168bd
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal ODH" {
                background #7ed321
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
