/*
 * Argo Workflows - C4 Context Diagram (Structurizr DSL)
 * Generated by: Claude Opus 4.6
 * Source: architecture/rhoai-2.25/argo-workflows.md
 */

workspace {
    model {
        datascientist = person "Data Scientist" "Creates and runs ML pipelines via DSP"

        argoWorkflows = softwareSystem "Argo Workflows" "Workflow execution engine for Kubernetes - orchestrates parallel jobs as DAGs for Data Science Pipelines" {
            workflowController = container "Workflow Controller" "Watches Workflow CRs, creates/manages Pods for workflow steps, handles DAG scheduling, TTL, garbage collection, cron workflows, and leader election" "Go Binary (Deployment), UID 8737"
            argoexec = container "argoexec" "Runs inside workflow Pods as emissary executor; handles artifact collection, script output capture, wait/init container logic" "Go Binary (Init/Sidecar), UID 2000"
            workflowCRDs = container "Workflow CRDs" "8 CRDs: Workflow, WorkflowTemplate, ClusterWorkflowTemplate, CronWorkflow, WorkflowEventBinding, WorkflowTaskSet, WorkflowTaskResult, WorkflowArtifactGCTask" "Kubernetes CRDs"
        }

        dspo = softwareSystem "Data Science Pipelines Operator" "Deploys and configures Argo Workflows controller and executor images" "Internal RHOAI"
        dspApiServer = softwareSystem "DSP API Server" "Data Science Pipelines API server - submits Workflow CRs" "Internal RHOAI"
        mlmd = softwareSystem "ML Metadata (MLMD)" "Pipeline metadata store used alongside workflow artifacts" "Internal RHOAI"

        k8sApi = softwareSystem "Kubernetes API" "Core platform for Pod/ConfigMap/PVC management" "External"
        s3 = softwareSystem "S3/MinIO" "Artifact repository for workflow step outputs" "External"
        postgresql = softwareSystem "PostgreSQL" "Workflow archival and node status offloading" "External"
        prometheus = softwareSystem "Prometheus" "Metrics collection and monitoring" "External"

        # Relationships
        datascientist -> dspApiServer "Submits pipeline runs via UI/API"
        dspApiServer -> argoWorkflows "Submits Workflow CRs" "HTTPS/443"
        dspo -> argoWorkflows "Deploys and configures" "Deployment management"

        argoWorkflows -> k8sApi "Watches CRs, creates/manages Pods" "HTTPS/443, SA Token"
        argoWorkflows -> s3 "Stores and retrieves artifacts" "HTTPS/443 or HTTP/9000, Access Key"
        argoWorkflows -> postgresql "Archives workflow state" "TCP/5432, Username/Password"

        prometheus -> argoWorkflows "Scrapes metrics" "HTTP/9090"

        dspApiServer -> mlmd "Stores pipeline metadata" "gRPC"

        # Container-level relationships
        workflowController -> k8sApi "Watch Workflow CRs, Create Pods" "HTTPS/443, TLS 1.2+, SA Token"
        workflowController -> postgresql "Archive workflows" "TCP/5432, TLS configurable"
        argoexec -> k8sApi "Get Workflow, Patch annotations" "HTTPS/443, TLS 1.2+, SA Token"
        argoexec -> s3 "Upload/download artifacts" "HTTPS/HTTP, TLS configurable, Access Key"
        workflowController -> argoexec "Creates Pods containing argoexec" "Pod specification"
    }

    views {
        systemContext argoWorkflows "SystemContext" {
            include *
            autoLayout
        }

        container argoWorkflows "Containers" {
            include *
            autoLayout
        }

        styles {
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #000000
            }
            element "Person" {
                shape Person
                background #08427b
                color #ffffff
            }
            element "Software System" {
                background #1168bd
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
