// FMS Guardrails Orchestrator - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6

workspace {
    model {
        client = person "Client / Application" "Sends text for generation, detection, or classification with guardrails"

        guardrailsOrchestrator = softwareSystem "FMS Guardrails Orchestrator" "Coordinates AI text generation with content safety guardrails via configurable detector and chunker services" {
            guardrailsServer = container "Guardrails Server" "Serves guardrails API endpoints (classification, detection, generation-detection, chat/text completions)" "Rust/axum, 8033/TCP"
            healthServer = container "Health Server" "Serves health and info endpoints" "Rust/axum, 8034/TCP"
            orchestratorCore = container "Orchestrator Core" "Coordinates requests across generation, detector, and chunker clients" "Rust"
            generationClient = container "GenerationClient" "Connects to TGIS or caikit-nlp generation backends" "gRPC/tonic"
            openaiClient = container "OpenAiClient" "Connects to OpenAI-compatible chat/completion endpoints" "HTTP/reqwest"
            detectorClient = container "DetectorClient" "Sends content to detector services for safety analysis" "HTTP/reqwest"
            chunkerClient = container "ChunkerClient" "Sends text to chunker services for tokenization/segmentation" "gRPC/tonic"
            tlsModule = container "TLS Module" "Configures rustls for server TLS/mTLS and client TLS connections" "rustls"
        }

        tgis = softwareSystem "TGIS" "Text Generation Inference Server - gRPC generation backend" "Internal RHOAI"
        caikitNlp = softwareSystem "caikit-nlp" "caikit NLP text generation provider" "Internal RHOAI"
        vllm = softwareSystem "vLLM / OpenAI-compatible" "OpenAI-compatible chat/text completions server" "Internal RHOAI"
        detectors = softwareSystem "Guardrails Detector Services" "Content safety detection services (text_contents, text_chat, text_context_doc, text_generation)" "Internal RHOAI"
        chunkers = softwareSystem "Chunker Services (caikit)" "Text chunking/tokenization services" "Internal RHOAI"
        otlpCollector = softwareSystem "OTLP Collector" "OpenTelemetry trace and metric collector" "External"

        // System context relationships
        client -> guardrailsOrchestrator "Sends text for classification, detection, and generation" "HTTP/HTTPS 8033/TCP"
        guardrailsOrchestrator -> tgis "Sends generation requests" "gRPC/HTTP2 8033/TCP, TLS (configurable)"
        guardrailsOrchestrator -> caikitNlp "Sends generation requests" "gRPC/HTTP2, TLS (configurable)"
        guardrailsOrchestrator -> vllm "Sends chat/text completion requests" "HTTP/HTTPS 8080/TCP, TLS (configurable)"
        guardrailsOrchestrator -> detectors "Sends content for safety detection" "HTTP/HTTPS 8080/TCP, TLS (configurable)"
        guardrailsOrchestrator -> chunkers "Sends text for chunking/tokenization" "gRPC/HTTP2 8085/TCP, TLS (configurable)"
        guardrailsOrchestrator -> otlpCollector "Exports traces and metrics" "gRPC 4317 or HTTP 4318/TCP"

        // Container relationships
        client -> guardrailsServer "POST /api/v1/*, /api/v2/*" "HTTP/HTTPS 8033/TCP, TLS 1.2+"
        guardrailsServer -> orchestratorCore "Routes API requests"
        orchestratorCore -> generationClient "Dispatches generation requests"
        orchestratorCore -> openaiClient "Dispatches OpenAI-compatible requests"
        orchestratorCore -> detectorClient "Dispatches detection requests"
        orchestratorCore -> chunkerClient "Dispatches chunking requests"
        generationClient -> tgis "Generate, GenerateStream, Tokenize" "gRPC/HTTP2, mTLS (configurable)"
        generationClient -> caikitNlp "NLP text generation" "gRPC/HTTP2, mTLS (configurable)"
        openaiClient -> vllm "Chat completions, text completions" "HTTP/HTTPS, Bearer token"
        detectorClient -> detectors "Content, chat, context, generation detection" "HTTP/HTTPS, mTLS (configurable)"
        chunkerClient -> chunkers "Text chunking/tokenization" "gRPC/HTTP2, mTLS (configurable)"
    }

    views {
        systemContext guardrailsOrchestrator "SystemContext" {
            include *
            autoLayout
        }

        container guardrailsOrchestrator "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #4a90e2
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Person" {
                background #f5a623
                color #ffffff
                shape Person
            }
            element "Container" {
                background #6baed6
                color #ffffff
            }
        }
    }
}
