// C4 Context Diagram: guardrails-detectors
// Generated by: Claude Opus 4.6
// Source: architecture/rhoai-2.25/guardrails-detectors.md

workspace {
    model {
        orchestrator = person "FMS Guardrails Orchestrator" "Orchestrates content safety analysis across multiple detectors"

        guardrailsDetectors = softwareSystem "Guardrails Detectors" "Collection of detector microservices providing content safety analysis via regex, ML models, and LLM-as-Judge" {
            builtInDetector = container "Built-in Detector" "Lightweight regex-based PII detection (email, credit card, SSN, phone, IP, UK post code) and file type validation (JSON, XML, YAML)" "Python FastAPI, port 8080"
            huggingfaceDetector = container "HuggingFace Detector" "ML-based content classification using AutoModelForSequenceClassification and GraniteForCausalLM with GPU/CUDA support" "Python FastAPI, port 8000"
            llmJudgeDetector = container "LLM Judge Detector" "LLM-as-a-judge evaluation using vLLM Judge library with configurable metrics (safety, toxicity, accuracy, helpfulness)" "Python FastAPI, port 8000"
            commonFramework = container "Common Framework" "Shared DetectorBaseAPI, Pydantic schemas, health endpoints, Prometheus instrumentation" "Python Library"
        }

        kserve = softwareSystem "KServe" "Kubernetes inference serving platform" "External Platform"
        vllmServer = softwareSystem "External vLLM Server" "OpenAI-compatible LLM server for Judge evaluation" "External"
        prometheus = softwareSystem "Prometheus" "Metrics collection and monitoring" "External Platform"
        rhodsOperator = softwareSystem "RHODS Operator" "Manages RBAC and deployment configuration" "Internal RHOAI"
        serviceMesh = softwareSystem "Service Mesh (Istio)" "Optional mTLS and network security" "External Platform"

        // Relationships
        orchestrator -> guardrailsDetectors "Invokes detectors for content analysis" "HTTP REST API"
        orchestrator -> builtInDetector "POST /api/v1/text/contents" "HTTP/8080"
        orchestrator -> huggingfaceDetector "POST /api/v1/text/contents" "HTTP/8000"
        orchestrator -> llmJudgeDetector "POST /api/v1/text/contents, /generation" "HTTP/8000"

        llmJudgeDetector -> vllmServer "Evaluates content via external LLM" "HTTP/HTTPS configurable"

        builtInDetector -> commonFramework "Uses shared schemas and base API"
        huggingfaceDetector -> commonFramework "Uses shared schemas and base API"
        llmJudgeDetector -> commonFramework "Uses shared schemas and base API"

        kserve -> huggingfaceDetector "Deploys as InferenceService"
        kserve -> llmJudgeDetector "Deploys as InferenceService"
        prometheus -> guardrailsDetectors "Scrapes /metrics endpoint" "HTTP"
        rhodsOperator -> guardrailsDetectors "Manages RBAC and deployment"
        serviceMesh -> guardrailsDetectors "Provides optional mTLS" "Istio sidecar"
    }

    views {
        systemContext guardrailsDetectors "SystemContext" {
            include *
            autoLayout
        }

        container guardrailsDetectors "Containers" {
            include *
            autoLayout
        }

        styles {
            element "External" {
                background #999999
                color #ffffff
            }
            element "External Platform" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Software System" {
                background #4a90e2
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
            element "Person" {
                background #f5a623
                color #ffffff
                shape Person
            }
        }
    }
}
