// C4 Context Diagram: llm-d-routing-sidecar
// Generated by: Claude Opus 4.6

workspace {
    model {
        client = person "Client / Data Scientist" "Sends inference requests to LLM endpoints"
        scheduler = softwareSystem "llm-d-inference-scheduler" "Upstream scheduler that sets x-prefiller-host-port header for P/D routing" "Internal RHOAI"

        routingSidecar = softwareSystem "llm-d-routing-sidecar" "Go HTTP/HTTPS reverse proxy sidecar orchestrating disaggregated prefill/decode inference routing" {
            proxy = container "Sidecar Proxy" "Main HTTPS listener accepting inference requests" "Go HTTP Server" "8000/TCP"
            nixlv2 = container "NIXL v2 Connector" "Implements NIXL v2 P/D protocol with kv_transfer_params" "Go"
            nixlv1 = container "NIXL v1 Connector (deprecated)" "Legacy NIXL v1 P/D protocol" "Go"
            lmcache = container "LMCache Connector (deprecated)" "LMCache P/D protocol" "Go"
            allowlistValidator = container "Allowlist Validator" "SSRF protection via InferencePool pod IP allowlisting" "Go"
            tlsManager = container "TLS Manager" "Manages TLS certificates for secure proxy" "Go"
        }

        localDecoder = softwareSystem "Local vLLM Decoder" "Co-located vLLM instance for decode phase token generation" "Internal RHOAI"
        remotePrefiller = softwareSystem "Remote Prefiller Pods" "Remote vLLM prefiller pods for KV cache prefill phase" "Internal RHOAI"
        k8sAPI = softwareSystem "Kubernetes API Server" "Kubernetes control plane API" "External"
        inferencePool = softwareSystem "Gateway API Inference Extension" "InferencePool v1alpha2 CRD defining valid prefill pool membership" "External"

        // Relationships
        client -> routingSidecar "Sends inference requests" "HTTPS/8000 TLS 1.2+"
        scheduler -> routingSidecar "Sets x-prefiller-host-port header" "HTTP Header"
        routingSidecar -> localDecoder "Forwards decode-phase requests" "HTTP or HTTPS/8001"
        routingSidecar -> remotePrefiller "Forwards prefill-phase requests" "HTTP or HTTPS/Dynamic"
        routingSidecar -> k8sAPI "Watches InferencePool and Pod resources" "HTTPS/443 SA Token"
        k8sAPI -> inferencePool "Serves InferencePool CRs" "API"

        // Internal relationships
        proxy -> nixlv2 "Uses for NIXL v2 prefill/decode"
        proxy -> nixlv1 "Uses for NIXL v1 prefill/decode"
        proxy -> lmcache "Uses for LMCache prefill/decode"
        proxy -> allowlistValidator "Validates prefiller targets"
        allowlistValidator -> k8sAPI "Watches InferencePool and Pods" "HTTPS/443"
    }

    views {
        systemContext routingSidecar "SystemContext" {
            include *
            autoLayout
        }

        container routingSidecar "Containers" {
            include *
            autoLayout
        }

        styles {
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Software System" {
                background #4a90e2
                color #ffffff
            }
            element "Container" {
                background #4a90e2
                color #ffffff
            }
            element "Person" {
                background #08427b
                color #ffffff
                shape Person
            }
        }
    }
}
