/*
 * ModelMesh C4 Context Diagram (Structurizr DSL)
 * Generated by: Claude Opus 4.6
 * Source: architecture/rhoai-2.25/modelmesh.md
 */

workspace {
    model {
        dataScientist = person "Data Scientist" "Deploys and manages ML models for inference"
        mlEngineer = person "ML Engineer" "Configures model serving infrastructure"

        modelmesh = softwareSystem "ModelMesh" "Distributed LRU cache and routing layer for high-scale, high-density model serving on Kubernetes" {
            modelmeshCore = container "ModelMesh Core" "Distributed model serving mesh - manages model placement, LRU caching, and request routing across cluster pods" "Java 21 Service (Sidecar)"
            modelmeshApi = container "ModelMesh gRPC API" "External-facing gRPC API server for model management and inference request proxying" "gRPC Server (port 8033)"
            sidecarMesh = container "SidecarModelMesh" "Integration layer for external model runtime containers via ModelRuntime gRPC interface" "Java Service"
            vmodelManager = container "VModelManager" "Virtual model indirection layer for model versioning and blue-green transitions" "Java Component"
            litelinks = container "Litelinks Framework" "Internal service discovery and inter-pod RPC framework" "Java Framework (port 8080)"
            prometheusServer = container "Prometheus NettyServer" "Embedded HTTP(S) server exposing Prometheus metrics" "Netty HTTP Server (port 2112)"
            payloadProcessor = container "PayloadProcessor Pipeline" "Extensible pipeline for processing inference payloads with SSRF protection" "Java Component"
        }

        /* Internal ODH Dependencies */
        modelmeshServing = softwareSystem "ModelMesh Serving" "Controller that manages ModelMesh deployment, configuration, and lifecycle" "Internal RHOAI"
        runtimeAdapter = softwareSystem "ModelMesh Runtime Adapter" "Adapts storage backends (S3, PVC) for model loading; implements ModelRuntime interface" "Internal RHOAI"
        kserve = softwareSystem "KServe" "Provides InferenceService CRD that triggers modelmesh-serving to deploy ModelMesh pods" "Internal RHOAI"

        /* External Dependencies */
        etcd = softwareSystem "etcd" "Distributed key-value store for model registry, instance tracking, leader election, and configuration" "External"
        prometheus = softwareSystem "Prometheus" "Metrics collection and monitoring" "External"
        kubernetesApi = softwareSystem "Kubernetes API" "Container orchestration platform" "External"

        /* Optional external */
        datadogStatsD = softwareSystem "DataDog StatsD" "Optional alternative metrics backend" "External Optional"
        remotePayloadTarget = softwareSystem "Remote Payload Processor" "Optional external payload forwarding target" "External Optional"

        /* Relationships */
        dataScientist -> kserve "Creates InferenceService via kubectl"
        mlEngineer -> modelmeshServing "Configures model serving"

        kserve -> modelmeshServing "InferenceService CR triggers deployment"
        modelmeshServing -> modelmesh "Deploys and configures" "Kubernetes API"

        modelmeshApi -> modelmeshCore "Routes inference requests"
        modelmeshCore -> sidecarMesh "Model load/unload/inference"
        modelmeshCore -> vmodelManager "Virtual model resolution"
        modelmeshCore -> litelinks "Inter-pod communication"
        modelmeshApi -> payloadProcessor "Payload processing"

        sidecarMesh -> runtimeAdapter "ModelRuntime gRPC interface" "gRPC/8085 or UDS (plaintext)"
        modelmeshCore -> etcd "Model registry, instance tracking, leader election" "gRPC/2379 (TLS)"
        litelinks -> etcd "Service discovery registration" "gRPC/2379 (TLS)"
        prometheusServer -> prometheus "Metrics exposition" "HTTP(S)/2112"
        modelmesh -> kubernetesApi "Health probes" "HTTP/8089"
        payloadProcessor -> remotePayloadTarget "Optional payload forwarding" "HTTP(S) (SSRF protected)"
        modelmesh -> datadogStatsD "Optional metrics" "UDP/8126 StatsD"
    }

    views {
        systemContext modelmesh "SystemContext" {
            include *
            autoLayout
        }

        container modelmesh "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438dd5
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "External Optional" {
                background #bbbbbb
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Person" {
                background #08427b
                color #ffffff
                shape Person
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
