// ODH Dashboard - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6
// Source: architecture/rhoai-2.25/odh-dashboard.md

workspace {
    model {
        dataScientist = person "Data Scientist" "Creates and manages data science projects, notebooks, model serving, and pipelines"
        admin = person "Platform Admin" "Configures platform settings, accelerator profiles, and cluster resources"

        odhDashboard = softwareSystem "ODH Dashboard" "Red Hat OpenShift AI web dashboard providing unified management interface for data science workloads" {
            oauthProxy = container "oauth-proxy" "OpenShift OAuth authentication proxy, TLS termination on port 8443" "OpenShift oauth-proxy sidecar"
            dashboardBackend = container "Dashboard Backend" "BFF proxy to Kubernetes API, serves static frontend, WebSocket proxy for k8s watch" "Node.js 20 / Fastify"
            dashboardFrontend = container "Dashboard Frontend" "User interface for managing data science projects, notebooks, model serving, pipelines" "React / TypeScript / PatternFly SPA"
            modelRegistryUI = container "Model Registry UI" "Model Registry microfrontend via Module Federation, BFF API for model registry operations" "Go BFF"
        }

        // External Dependencies
        k8sAPI = softwareSystem "Kubernetes API Server" "Cluster resource management and RBAC enforcement" "External"
        openshiftOAuth = softwareSystem "OpenShift OAuth Server" "User authentication and token issuance" "External"
        thanosQuerier = softwareSystem "Thanos Querier" "Prometheus metrics aggregation in openshift-monitoring namespace" "External"
        openshiftConsole = softwareSystem "OpenShift Console" "OpenShift web console with application menu" "External"

        // Internal ODH Dependencies
        notebookController = softwareSystem "Notebook Controller" "Manages Jupyter notebook/workbench instances via kubeflow.org CRDs" "Internal ODH"
        kserve = softwareSystem "KServe" "Model serving inference services (InferenceService, ServingRuntime CRDs)" "Internal ODH"
        modelMesh = softwareSystem "ModelMesh" "Multi-model serving runtime management" "Internal ODH"
        modelRegistry = softwareSystem "Model Registry" "Model metadata management and versioning" "Internal ODH"
        dsPipelines = softwareSystem "Data Science Pipelines" "Pipeline management and execution" "Internal ODH"
        rhodsOperator = softwareSystem "RHODS Operator" "Deploys and configures dashboard via kustomize overlays" "Internal ODH"

        // Relationships - Users
        dataScientist -> odhDashboard "Manages projects, notebooks, models, pipelines via web UI"
        admin -> odhDashboard "Configures platform settings, accelerator profiles, user access"

        // Relationships - Internal container interactions
        oauthProxy -> dashboardBackend "Forwards authenticated requests" "HTTP/8080, x-forwarded-access-token"
        oauthProxy -> modelRegistryUI "Forwards authenticated requests" "HTTPS/8043, x-forwarded-access-token"
        dashboardBackend -> dashboardFrontend "Serves static SPA assets" "HTTP/8080"

        // Relationships - External
        odhDashboard -> k8sAPI "All resource CRUD via pass-through proxy" "HTTPS/6443, Bearer Token"
        odhDashboard -> openshiftOAuth "User authentication" "HTTPS/443, OAuth 2.0"
        odhDashboard -> thanosQuerier "Prometheus metrics queries" "HTTPS/9092, Bearer Token"
        odhDashboard -> openshiftConsole "Adds application menu link" "ConsoleLink CR"

        // Relationships - Internal ODH
        odhDashboard -> notebookController "Creates/manages notebooks" "Notebook CRD"
        odhDashboard -> kserve "Views inference services" "InferenceService CRD"
        odhDashboard -> modelMesh "Manages serving runtimes" "ServingRuntime CRD"
        modelRegistryUI -> modelRegistry "Model metadata management" "HTTPS, REST API"
        odhDashboard -> dsPipelines "Pipeline management" "REST API"
        rhodsOperator -> odhDashboard "Deploys and configures" "Kustomize"
    }

    views {
        systemContext odhDashboard "SystemContext" {
            include *
            autoLayout
        }

        container odhDashboard "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Person" {
                shape Person
                background #08427b
                color #ffffff
            }
            element "Software System" {
                background #1168bd
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal ODH" {
                background #7ed321
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
