/*
 * C4 Context Diagram - OpenVINO Model Server (OVMS)
 * Generated by: Claude Opus 4.6
 * Source: architecture/rhoai-2.25/openvino_model_server.md
 */

workspace {
    model {
        datascientist = person "Data Scientist / ML Engineer" "Sends inference requests and deploys models"
        platformadmin = person "Platform Admin" "Configures and monitors OVMS deployments"

        ovms = softwareSystem "OpenVINO Model Server (OVMS)" "High-performance C++ inference server supporting TFS, KServe v2, and OpenAI-compatible APIs" {
            grpcServer = container "gRPC Server Module" "Hosts TFS PredictionService, TFS ModelService, and KFS GRPCInferenceService" "C++ / gRPC (HTTP/2)"
            httpServer = container "HTTP Server Module" "Hosts REST endpoints for TFS, KServe v2, OpenAI v3 APIs, and Prometheus metrics" "C++ / HTTP/1.1"
            servableManager = container "Servable Manager Module" "Manages model loading, versioning, lifecycle, and inference execution" "C++"
            mediapipe = container "MediaPipe Integration" "Graph-based execution for complex inference pipelines, LLM, embeddings, rerank, image gen" "C++ / MediaPipe"
            openvinoRuntime = container "OpenVINO Runtime" "Intel inference engine backend for CPU/GPU execution" "C++ / OpenVINO 2025.3"
            metricsModule = container "Metrics Module" "Prometheus-compatible metrics collection and reporting" "C++"
            fileSystemFactory = container "FileSystem Factory" "Abstraction layer for local, S3, GCS, and Azure storage backends" "C++"
            pythonInterpreter = container "Python Interpreter Module" "Embedded Python interpreter for custom processing nodes" "C++ / Python 3"
            hfPullModule = container "HuggingFace Pull Module" "Downloads and prepares models from HuggingFace Hub" "C++ / Python"
        }

        kserve = softwareSystem "KServe" "Deploys OVMS as InferenceService runtime container" "Internal RHOAI"
        modelmesh = softwareSystem "ModelMesh" "Deploys OVMS as a ServingRuntime backend" "Internal RHOAI"
        odhModelController = softwareSystem "odh-model-controller" "Manages model serving deployments including OVMS instances" "Internal RHOAI"
        istio = softwareSystem "Istio Service Mesh" "Provides mTLS, traffic management, and authorization" "External"
        prometheus = softwareSystem "Prometheus" "Monitoring and metrics collection" "External"

        s3 = softwareSystem "S3-Compatible Storage" "Model artifact storage (AWS S3 or compatible)" "External"
        gcs = softwareSystem "Google Cloud Storage" "Model artifact storage on GCP" "External"
        azure = softwareSystem "Azure Blob Storage" "Model artifact storage on Azure" "External"
        huggingface = softwareSystem "HuggingFace Hub" "Model repository for downloading pretrained models" "External"

        # User interactions
        datascientist -> ovms "Sends inference requests" "gRPC (HTTP/2), HTTP/1.1 REST"
        platformadmin -> kserve "Deploys InferenceService with OVMS runtime" "kubectl / RHOAI Dashboard"

        # Platform interactions
        kserve -> ovms "Deploys and manages OVMS containers" "Kubernetes API"
        modelmesh -> ovms "Routes inference requests to OVMS pods" "gRPC"
        odhModelController -> ovms "Manages model serving lifecycle" "Kubernetes API"
        istio -> ovms "Provides mTLS sidecar and authorization" "Envoy proxy"
        prometheus -> ovms "Scrapes metrics from /metrics endpoint" "HTTP GET"

        # Egress - model storage
        ovms -> s3 "Downloads model artifacts" "HTTPS/443, AWS IAM"
        ovms -> gcs "Downloads model artifacts" "HTTPS/443, GCP SA"
        ovms -> azure "Downloads model artifacts" "HTTPS/443, Azure creds"
        ovms -> huggingface "Downloads and converts models" "HTTPS/443, HF_TOKEN"

        # Internal container relationships
        grpcServer -> servableManager "Routes inference requests"
        httpServer -> servableManager "Routes inference requests"
        httpServer -> mediapipe "Routes OpenAI v3 requests"
        servableManager -> openvinoRuntime "Executes inference"
        mediapipe -> openvinoRuntime "Executes LLM/embedding/rerank inference"
        servableManager -> fileSystemFactory "Loads models from storage"
        hfPullModule -> fileSystemFactory "Stores downloaded models"
        metricsModule -> httpServer "Exposes /metrics endpoint"
    }

    views {
        systemContext ovms "SystemContext" {
            include *
            autoLayout
        }

        container ovms "Containers" {
            include *
            autoLayout
        }

        styles {
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Person" {
                shape person
                background #4a90e2
                color #ffffff
            }
            element "Software System" {
                background #4a90e2
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
