// TrustyAI Service Operator - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6

workspace {
    model {
        datascientist = person "Data Scientist" "Creates ML models, runs evaluations, configures guardrails"
        mlops = person "MLOps Engineer" "Deploys and manages AI/ML services on OpenShift"

        trustyaiOperator = softwareSystem "TrustyAI Service Operator" "Multi-controller Kubernetes operator managing AI/ML trustworthiness, model evaluation, and guardrails orchestration" {
            tasController = container "TrustyAIService Reconciler" "Manages TrustyAI service deployments for AI explainability and fairness monitoring" "Go Controller"
            lmesController = container "LMEvalJob Reconciler" "Creates and manages language model evaluation pods" "Go Controller"
            gorchController = container "GuardrailsOrchestrator Reconciler" "Deploys guardrails orchestration with auto-config from InferenceServices" "Go Controller"
            jobManager = container "WorkloadManager" "Integrates LMEvalJob with Kueue workload scheduling" "Go Controller"
            lmesDriver = container "LMES Driver" "Sidecar process managing evaluation lifecycle in eval pods" "Go Binary"
        }

        kserve = softwareSystem "KServe" "Model serving platform providing InferenceService and ServingRuntime APIs" "Internal ODH"
        modelmesh = softwareSystem "ModelMesh Serving" "Multi-model serving with payload processing support" "Internal ODH"
        rhodsOperator = softwareSystem "RHODS Operator" "Deploys TrustyAI operator via kustomize overlays" "Internal ODH"
        odhDashboard = softwareSystem "ODH Dashboard" "Web UI for managing data science projects" "Internal ODH"

        istio = softwareSystem "Istio Service Mesh" "Service mesh for mTLS and traffic management" "External"
        kueue = softwareSystem "Kueue" "Workload queuing and scheduling framework" "External"
        prometheus = softwareSystem "Prometheus" "Metrics collection and monitoring" "External"
        certSigner = softwareSystem "OpenShift Service CA" "Automatic TLS certificate provisioning for services" "External"

        database = softwareSystem "External Database" "Stores TrustyAI inference data (Hibernate/JDBC)" "External"
        s3Storage = softwareSystem "S3 Storage" "Offline evaluation datasets for LMES" "External"
        modelEndpoints = softwareSystem "Model Endpoints" "HuggingFace, OpenAI, vLLM for LM evaluation" "External"

        // User interactions
        datascientist -> trustyaiOperator "Creates TrustyAIService, LMEvalJob, GuardrailsOrchestrator CRs via kubectl"
        mlops -> trustyaiOperator "Configures and monitors AI trustworthiness services"

        // Internal ODH interactions
        trustyaiOperator -> kserve "Patches InferenceServices with payload processors; auto-discovers for guardrails config" "Kubernetes API / HTTPS"
        trustyaiOperator -> modelmesh "Patches ModelMesh deployments with payload processor env vars" "Kubernetes API / HTTPS"
        rhodsOperator -> trustyaiOperator "Deploys operator via kustomize overlay" "Kustomize"

        // External interactions
        trustyaiOperator -> istio "Creates DestinationRules and VirtualServices when Istio sidecar present" "Kubernetes API"
        trustyaiOperator -> kueue "Creates Workload CRs for LMEvalJob scheduling" "Kubernetes API"
        prometheus -> trustyaiOperator "Scrapes metrics via ServiceMonitor" "HTTP/80, HTTP/8080"
        certSigner -> trustyaiOperator "Provisions TLS certificates for service-serving-cert annotations" "Automatic"

        trustyaiOperator -> database "Stores inference data (when DATABASE storage mode)" "JDBC / Optional TLS"
        trustyaiOperator -> s3Storage "Downloads offline evaluation datasets" "HTTPS/443"
        trustyaiOperator -> modelEndpoints "Runs LM evaluations against model APIs" "HTTP/HTTPS"
    }

    views {
        systemContext trustyaiOperator "SystemContext" {
            include *
            autoLayout
        }

        container trustyaiOperator "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Person" {
                shape Person
                background #08427b
                color #ffffff
            }
            element "Software System" {
                background #1168bd
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal ODH" {
                background #7ed321
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
