// vllm-cpu C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6
// Source: architecture/rhoai-2.25/vllm-cpu.md

workspace {
    model {
        user = person "Data Scientist / ML Engineer" "Deploys and queries LLM models for inference"

        vllmCpu = softwareSystem "vLLM-CPU" "CPU-optimized LLM inference serving engine with OpenAI-compatible and gRPC APIs" {
            apiServer = container "OpenAI API Server" "OpenAI-compatible REST API for chat completions, embeddings, scoring, reranking" "Python/FastAPI/Uvicorn" "Service"
            tgisAdapter = container "vllm-tgis-adapter" "gRPC adapter for TGIS protocol compatibility with RHOAI model serving" "Python gRPC" "Service"
            engine = container "vLLM Engine V1" "Core inference engine with PagedAttention, continuous batching, speculative decoding" "Python" "Engine"
            cppKernels = container "C++ CPU Kernels" "Native CPU-optimized attention and model execution kernels" "C++/CMake/PyTorch Extensions" "Library"
            metricsExporter = container "Prometheus Metrics" "Prometheus metrics exporter at /metrics endpoint" "Python" "Metrics"
            sslModule = container "SSL/TLS Support" "TLS termination with certificate hot-reload" "Python" "Security"
            otelTracing = container "OpenTelemetry Tracing" "Distributed tracing via OTLP exporter" "Python" "Tracing"
        }

        // Internal ODH Systems
        kserve = softwareSystem "KServe" "Model serving orchestration and scaling" "Internal RHOAI"
        modelMesh = softwareSystem "ModelMesh" "Multi-model serving orchestration" "Internal RHOAI"
        odhModelController = softwareSystem "odh-model-controller" "Manages model deployment lifecycle" "Internal RHOAI"

        // External Systems
        prometheus = softwareSystem "Prometheus" "Monitoring and metrics collection" "External"
        otlpCollector = softwareSystem "OTLP Collector" "OpenTelemetry trace collection (Jaeger)" "External"
        hfHub = softwareSystem "Hugging Face Hub" "Model weights and configs repository" "External"
        s3Storage = softwareSystem "S3-Compatible Storage" "Model weight storage (tensorizer)" "External"

        // Relationships - User
        user -> kserve "Creates InferenceService / ServingRuntime"
        user -> vllmCpu "Sends inference requests via KServe/ModelMesh"

        // Relationships - Deployment
        kserve -> vllmCpu "Deploys as InferenceService serving runtime" "HTTP/8000"
        modelMesh -> vllmCpu "Deploys as ServingRuntime with TGIS adapter" "gRPC/8033"
        odhModelController -> kserve "Creates/manages inference services"

        // Relationships - Internal containers
        apiServer -> engine "Forwards inference requests" "IPC/ZMQ"
        tgisAdapter -> engine "Forwards gRPC requests" "IPC"
        engine -> cppKernels "Executes model operations"
        apiServer -> metricsExporter "Exposes metrics"
        apiServer -> sslModule "TLS termination"
        apiServer -> otelTracing "Trace instrumentation"

        // Relationships - External
        prometheus -> vllmCpu "Scrapes /metrics endpoint" "HTTP/8000"
        otelTracing -> otlpCollector "Exports traces" "gRPC/4317"
        engine -> hfHub "Downloads model weights" "HTTPS/443"
        engine -> s3Storage "Downloads model artifacts" "HTTPS/443"
    }

    views {
        systemContext vllmCpu "SystemContext" {
            include *
            autoLayout
        }

        container vllmCpu "Containers" {
            include *
            autoLayout
        }

        styles {
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Service" {
                background #4a90e2
                color #ffffff
            }
            element "Engine" {
                background #4a90e2
                color #ffffff
            }
            element "Library" {
                background #4a90e2
                color #ffffff
            }
            element "Metrics" {
                background #9b59b6
                color #ffffff
            }
            element "Security" {
                background #e74c3c
                color #ffffff
            }
            element "Tracing" {
                background #f39c12
                color #ffffff
            }
            element "Person" {
                background #08427b
                color #ffffff
                shape Person
            }
            element "Software System" {
                background #1168bd
                color #ffffff
            }
        }
    }
}
