package cmd

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/jctanner/arch-query/internal/loader"
	"github.com/jctanner/arch-query/internal/output"
	"github.com/spf13/cobra"
)

var (
	imageCategoryFilter string
	imageShowRefs       bool
)

var imagesCmd = &cobra.Command{
	Use:   "images [filter]",
	Short: "List container images from build-info.json",
	Long: `Show container images shipped with the platform release. Data comes
from build-info.json (generated by the collect phase from RHOAI-Build-Config).

The optional filter matches case-insensitively against image name, repository,
and source repo fields.

Examples:
  arch-query images
  arch-query images dashboard
  arch-query images --refs
  arch-query images --category infrastructure
  arch-query images --version rhoai-3.4 kserve`,
	Args: cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		version := versionArg
		if version == "" {
			versions, err := loader.DiscoverVersions(archFS, archSymlinks)
			if err != nil {
				return err
			}
			version = loader.DefaultVersion(versions)
		}

		data, err := loader.LoadVersion(archFS, overlayFS, version)
		if err != nil {
			return fmt.Errorf("loading version %s: %w", version, err)
		}

		if data.BuildInfo == nil {
			if outputFormat == OutputJSON {
				return output.JSON(os.Stdout, []any{})
			}
			fmt.Fprintf(os.Stderr, "No build info available for %s.\n", version)
			return nil
		}

		filter := ""
		if len(args) == 1 {
			filter = strings.ToLower(args[0])
		}

		type imageEntry struct {
			Name          string `json:"name"`
			Repository    string `json:"repository"`
			ProductionRef string `json:"production_ref,omitempty"`
			StagingRef    string `json:"staging_ref,omitempty"`
			SourceRepo    string `json:"source_repo,omitempty"`
			SourceCommit  string `json:"source_commit,omitempty"`
			Category      string `json:"category"`
		}

		var results []imageEntry
		for _, img := range data.BuildInfo.Images {
			if imageCategoryFilter != "" && !strings.EqualFold(img.Category, imageCategoryFilter) {
				continue
			}
			if filter != "" {
				lower := strings.ToLower
				if !strings.Contains(lower(img.Name), filter) &&
					!strings.Contains(lower(img.Repository), filter) &&
					!strings.Contains(lower(img.SourceRepo), filter) {
					continue
				}
			}
			results = append(results, imageEntry{
				Name:          img.Name,
				Repository:    img.Repository,
				ProductionRef: img.ProductionRef,
				StagingRef:    img.StagingRef,
				SourceRepo:    img.SourceRepo,
				SourceCommit:  img.SourceCommit,
				Category:      img.Category,
			})
		}

		sort.Slice(results, func(i, j int) bool {
			return results[i].Name < results[j].Name
		})

		if outputFormat == OutputJSON {
			return output.JSON(os.Stdout, results)
		}

		if len(results) == 0 {
			fmt.Fprintf(os.Stderr, "No images found")
			if filter != "" {
				fmt.Fprintf(os.Stderr, " matching %q", filter)
			}
			fmt.Fprintln(os.Stderr, ".")
			return nil
		}

		fmt.Printf("%d image(s) in %s", len(results), version)
		if filter != "" {
			fmt.Printf(" matching %q", filter)
		}
		fmt.Println(":")

		if imageShowRefs {
			for _, img := range results {
				fmt.Printf("\n  %s  [%s]\n", img.Name, img.Category)
				fmt.Printf("    production: %s\n", refOrDash(img.ProductionRef))
				fmt.Printf("    staging:    %s\n", refOrDash(img.StagingRef))
				if img.SourceRepo != "" {
					fmt.Printf("    source:     %s @ %s\n", img.SourceRepo, shortSHA(img.SourceCommit))
				}
			}
		} else {
			tw := output.NewTabWriter(os.Stdout)
			fmt.Fprintf(tw, "  NAME\tREPOSITORY\tPROD DIGEST\tCATEGORY\tSOURCE\n")
			for _, img := range results {
				source := img.SourceRepo
				if source == "" {
					source = "-"
				}
				fmt.Fprintf(tw, "  %s\t%s\t%s\t%s\t%s\n",
					img.Name, img.Repository, shortDigest(img.ProductionRef), img.Category, source)
			}
			tw.Flush()
		}
		return nil
	},
}

func shortDigest(ref string) string {
	idx := strings.Index(ref, "sha256:")
	if idx < 0 {
		return "-"
	}
	digest := ref[idx:]
	if len(digest) > 19 {
		return digest[:19] + "..."
	}
	return digest
}

func shortSHA(sha string) string {
	if len(sha) > 12 {
		return sha[:12]
	}
	if sha == "" {
		return "-"
	}
	return sha
}

func refOrDash(ref string) string {
	if ref == "" {
		return "-"
	}
	return ref
}

func init() {
	imagesCmd.Flags().StringVar(&imageCategoryFilter, "category", "", "Filter by category (component, infrastructure)")
	imagesCmd.Flags().BoolVar(&imageShowRefs, "refs", false, "Show full image references (production, staging, source)")
	addOutputFlag(imagesCmd, OutputText, OutputJSON)
	rootCmd.AddCommand(imagesCmd)
}
