package cmd

import (
	"fmt"
	"io/fs"
	"os"

	"github.com/jctanner/arch-query/internal/loader"
	"github.com/jctanner/arch-query/internal/output"
	"github.com/spf13/cobra"
)

var platformCmd = &cobra.Command{
	Use:   "platform",
	Short: "Show condensed platform summary",
	RunE: func(cmd *cobra.Command, args []string) error {
		version := versionArg
		if version == "" {
			versions, err := loader.DiscoverVersions(archFS, archSymlinks)
			if err != nil {
				return err
			}
			version = loader.DefaultVersion(versions)
		}

		if outputFormat == OutputRaw {
			path := version + "/PLATFORM.md"
			raw, err := fs.ReadFile(archFS, path)
			if err != nil {
				return fmt.Errorf("reading %s: %w", path, err)
			}
			fmt.Print(string(raw))
			return nil
		}

		data, err := loader.LoadVersion(archFS, overlayFS, version)
		if err != nil {
			return fmt.Errorf("loading version %s: %w", version, err)
		}

		if data.Platform == nil {
			fmt.Fprintf(os.Stderr, "No PLATFORM.md found in %s.\n", version)
			fmt.Fprintf(os.Stderr, "Use 'arch-query list' to see components.\n")
			os.Exit(1)
		}

		p := data.Platform

		if outputFormat == OutputJSON {
			return output.JSON(os.Stdout, p)
		}

		fmt.Printf("# Platform: %s\n\n", version)

		if p.Metadata != nil {
			for _, key := range []string{"Distribution", "Version", "Base Platform", "Supported OCP Versions", "Supported CPU Architectures", "Components Analyzed", "Generated By"} {
				if v, ok := p.Metadata[key]; ok {
					output.KeyValue(os.Stdout, key, v)
				}
			}
		}

		if p.Overview != "" {
			fmt.Printf("\n## Overview\n\n%s\n", p.Overview)
		}

		if len(p.Components) > 0 {
			fmt.Printf("\n## Component Inventory (%d components)\n\n", len(p.Components))
			tw := output.NewTabWriter(os.Stdout)
			for _, c := range p.Components {
				purpose := c.Purpose
				if len(purpose) > 60 {
					purpose = purpose[:57] + "..."
				}
				fmt.Fprintf(tw, "  %s\t%s\t%s\n", c.Name, c.Type, purpose)
			}
			tw.Flush()
		}

		return nil
	},
}

func init() {
	addOutputFlag(platformCmd, OutputText, OutputJSON, OutputRaw)
	rootCmd.AddCommand(platformCmd)
}
