// CodeFlare Operator - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6

workspace {
    model {
        user = person "Data Scientist" "Creates and manages distributed computing workloads (RayClusters, AppWrappers)"

        codeflareOperator = softwareSystem "CodeFlare Operator" "Manages RayCluster and AppWrapper lifecycle with OAuth, mTLS, and network policies" {
            rcController = container "RayCluster Controller" "Watches RayCluster CRs, creates Routes, Services, OAuth proxy, NetworkPolicies, mTLS certs" "Go Controller (controller-runtime)"
            awController = container "AppWrapper Controller" "Manages AppWrapper lifecycle, integrates with Kueue for gang scheduling" "Go Controller (optional)"
            rcMutatingWH = container "RayCluster Mutating Webhook" "Injects oauth-proxy sidecar and mTLS init containers into RayCluster pods" "Admission Webhook (9443/TCP)"
            rcValidatingWH = container "RayCluster Validating Webhook" "Validates RayCluster specs for immutable OAuth/TLS fields" "Admission Webhook (9443/TCP)"
            awMutatingWH = container "AppWrapper Mutating Webhook" "Defaults AppWrapper resources" "Admission Webhook (9443/TCP)"
            awValidatingWH = container "AppWrapper Validating Webhook" "Validates AppWrapper with SubjectAccessReview" "Admission Webhook (9443/TCP)"
            certRotator = container "Cert Rotator" "Auto-generates and rotates webhook TLS certificates" "cert-controller"
        }

        kuberay = softwareSystem "KubeRay Operator" "Manages RayCluster CRD lifecycle" "External"
        kueue = softwareSystem "Kueue" "Workload queuing and quota management" "External"
        odhOperator = softwareSystem "OpenDataHub/RHOAI Operator" "Platform operator managing DSCInitialization" "Internal RHOAI"
        openshiftOAuth = softwareSystem "OpenShift OAuth" "OAuth2 authentication server" "External"
        openshiftRouter = softwareSystem "OpenShift Router" "Ingress controller for Routes" "External"
        k8sAPI = softwareSystem "Kubernetes API Server" "Cluster API server" "External"
        prometheus = softwareSystem "Prometheus / OpenShift Monitoring" "Metrics collection and alerting" "External"

        user -> codeflareOperator "Creates RayCluster and AppWrapper CRs via kubectl"
        user -> openshiftRouter "Accesses Ray Dashboard via browser" "HTTPS/443"

        codeflareOperator -> kuberay "Watches RayCluster CRs created by KubeRay" "CRD Watch via API Server"
        codeflareOperator -> kueue "Creates Kueue Workloads for quota management" "CRD via API Server/6443"
        codeflareOperator -> odhOperator "Reads DSCInitialization for namespace config" "CRD Read via API Server/6443"
        codeflareOperator -> openshiftOAuth "oauth-proxy delegates user authentication" "HTTPS/443"
        codeflareOperator -> k8sAPI "Controller-runtime operations, RBAC, resource CRUD" "HTTPS/6443"

        openshiftRouter -> codeflareOperator "Routes to oauth-proxy in RayCluster head pods" "HTTPS/8443 Reencrypt"
        k8sAPI -> codeflareOperator "Webhook calls for RayCluster and AppWrapper admission" "HTTPS/9443"
        prometheus -> codeflareOperator "Scrapes operator metrics" "HTTP/8080"

        rcController -> k8sAPI "Creates Routes, Services, SA, CRB, Secrets, NetworkPolicies" "HTTPS/6443"
        awController -> k8sAPI "Creates Kueue Workloads and wrapped resources" "HTTPS/6443"
    }

    views {
        systemContext codeflareOperator "SystemContext" {
            include *
            autoLayout
        }

        container codeflareOperator "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438DD5
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Person" {
                background #08427B
                color #ffffff
                shape Person
            }
            element "Container" {
                background #438DD5
                color #ffffff
            }
        }
    }
}
