// Data Science Pipelines - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6

workspace {
    model {
        user = person "Data Scientist" "Creates, runs, and monitors ML pipelines"
        admin = person "Platform Admin" "Configures and manages the DSP platform"

        dsp = softwareSystem "Data Science Pipelines" "ML workflow orchestration platform based on Kubeflow Pipelines" {
            apiServer = container "ml-pipeline API Server" "Core API server for pipeline CRUD, run management, experiments, and artifacts" "Go Service" "REST :8888 / gRPC :8887"
            persistenceAgent = container "Persistence Agent" "Watches workflow CRs and syncs execution state to API server database" "Go Agent"
            scheduledWorkflow = container "ScheduledWorkflow Controller" "Reconciles ScheduledWorkflow CRs for recurring pipeline executions" "Go Controller"
            viewerController = container "Viewer CRD Controller" "Creates Deployments/Services for TensorBoard and visualization tools" "Go Controller"
            cacheServer = container "Cache Server" "Mutating admission webhook for step-level pipeline caching" "Go Service" "HTTPS :8443"
            pipelineUI = container "Pipeline UI" "Web UI for viewing pipelines, runs, experiments, and artifacts" "Node.js/React" ":3000"
            vizServer = container "Visualization Server" "Generates pipeline run visualizations" "Python Service" ":8888"
            driver = container "Driver" "V2 pipeline DAG driver for orchestrating step execution" "Go Binary"
            launcher = container "Launcher" "V2 pipeline step launcher for artifact I/O and metadata logging" "Go Binary"
            metadataGRPC = container "ML Metadata gRPC Server" "Stores and retrieves pipeline metadata and artifacts" "gRPC Service" ":8080"
            metadataEnvoy = container "Metadata Envoy" "Envoy sidecar proxying gRPC requests to metadata server" "Envoy Proxy" ":9090"
        }

        // External dependencies
        tekton = softwareSystem "Tekton Pipelines" "Workflow execution engine for pipeline runs" "External"
        argo = softwareSystem "Argo Workflows" "Alternative workflow execution engine" "External"
        kubernetes = softwareSystem "Kubernetes API" "Container orchestration platform" "External"
        database = softwareSystem "MySQL/PostgreSQL" "Relational database for pipeline metadata" "External"
        objectStore = softwareSystem "S3/MinIO Object Store" "Pipeline artifact and definition storage" "External"
        mlmd = softwareSystem "ML Metadata (MLMD)" "Pipeline metadata and lineage tracking" "External"

        // Internal ODH dependencies
        dspo = softwareSystem "Data Science Pipelines Operator" "Deploys and manages all DSP components" "Internal RHOAI"
        dashboard = softwareSystem "RHOAI Dashboard" "Provides pipeline management UI" "Internal RHOAI"

        // User relationships
        user -> dsp "Creates and monitors ML pipelines" "REST/gRPC"
        admin -> dsp "Configures pipeline platform"

        // Container-level relationships
        user -> pipelineUI "Views pipelines, runs, experiments" "HTTP :80"
        user -> apiServer "Creates/manages pipelines and runs" "REST :8888 / gRPC :8887"
        pipelineUI -> apiServer "API calls" "HTTP :8888"
        pipelineUI -> vizServer "Visualization requests" "HTTP :8888"
        persistenceAgent -> apiServer "Reports workflow status" "HTTP/gRPC :8888/:8887"
        scheduledWorkflow -> apiServer "Creates runs" "HTTP/gRPC :8888/:8887"
        metadataEnvoy -> metadataGRPC "Proxies gRPC requests" "gRPC :8080"
        launcher -> metadataGRPC "Logs metadata and lineage" "gRPC :8080"

        // External system relationships
        dsp -> tekton "Creates PipelineRuns for workflow execution" "HTTPS/443 (K8s API)"
        dsp -> argo "Creates Workflows (alternative engine)" "HTTPS/443 (K8s API)"
        dsp -> kubernetes "Manages workflow CRs, pods" "HTTPS/443"
        dsp -> database "Stores pipeline metadata (runs, experiments)" "MySQL :3306 / PostgreSQL :5432"
        dsp -> objectStore "Stores artifacts and pipeline definitions" "HTTPS/HTTP :443/:9000"
        dsp -> mlmd "Stores pipeline metadata and lineage" "gRPC :8080"

        // Internal ODH relationships
        dspo -> dsp "Deploys and manages all components" "CRD: DataSciencePipelinesApplication"
        dashboard -> dsp "Pipeline management UI integration" "REST API"
    }

    views {
        systemContext dsp "SystemContext" {
            include *
            autoLayout
        }

        container dsp "Containers" {
            include *
            autoLayout
        }

        styles {
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Person" {
                shape Person
                background #4a90e2
                color #ffffff
            }
            element "Software System" {
                background #4a90e2
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
