// Data Science Pipelines Operator - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6

workspace {
    model {
        user = person "Data Scientist" "Creates and manages ML pipelines via Dashboard or notebooks"
        admin = person "Platform Admin" "Deploys and configures DSPA instances"

        dspo = softwareSystem "Data Science Pipelines Operator" "Manages lifecycle of DSP applications via DSPA CRs on OpenShift" {
            controller = container "DSPA Controller" "Reconciles DataSciencePipelinesApplication CRs, deploys all sub-components" "Go Operator (controller-runtime)"
            apiServer = container "DSP API Server" "KFP API for pipeline CRUD (REST 8888, gRPC 8887)" "Kubeflow Pipelines Server"
            persistenceAgent = container "Persistence Agent" "Syncs pipeline run status between workflow engine and API server" "Go Service"
            scheduledWorkflow = container "Scheduled Workflow" "Manages cron-based scheduling of recurring pipeline runs" "Go Controller"
            mlmdGrpc = container "MLMD gRPC Server" "ML Metadata for artifact and execution lineage tracking" "gRPC Service (8080)"
            mlmdEnvoy = container "MLMD Envoy Proxy" "Envoy proxy fronting MLMD with OAuth sidecar" "Envoy (9090, 8443)"
            workflowController = container "Argo Workflow Controller" "Pipeline execution orchestration" "Argo Controller"
            mariadb = container "MariaDB" "Pipeline metadata storage (optional managed)" "MariaDB (3306)" "Database"
            minio = container "Minio" "Pipeline artifact storage (optional managed)" "Minio S3 (9000)" "Storage"
            oauthProxy = container "OAuth Proxy" "OpenShift oauth-proxy sidecar for authenticated external access" "oauth-proxy (8443)"
        }

        rhoaiOperator = softwareSystem "RHOAI Operator (rhods-operator)" "Parent operator managing DSPO deployment via DataScienceCluster CR" "Internal RHOAI"
        dashboard = softwareSystem "RHOAI Dashboard" "Pipeline management UI" "Internal RHOAI"
        workbenches = softwareSystem "Jupyter Workbenches" "Notebook environment for pipeline submission" "Internal RHOAI"
        argoWorkflows = softwareSystem "Argo Workflows" "Pipeline execution engine via Workflow CRDs" "Internal"
        openshiftOAuth = softwareSystem "OpenShift OAuth" "Authentication for externally exposed Routes" "Platform"
        openshiftServiceCA = softwareSystem "OpenShift Service CA" "Automatic TLS certificate generation for services" "Platform"
        openshiftMonitoring = softwareSystem "OpenShift Monitoring" "Prometheus metrics scraping via ServiceMonitor" "Platform"
        k8sAPI = softwareSystem "Kubernetes API" "Cluster API server for resource management" "Platform"
        extDB = softwareSystem "External Database" "User-provided MySQL/MariaDB for pipeline metadata" "External"
        extS3 = softwareSystem "External S3 Storage" "User-provided S3-compatible object storage for artifacts" "External"
        ray = softwareSystem "KubeRay" "Distributed compute for pipeline tasks" "Internal RHOAI"
        codeflare = softwareSystem "CodeFlare" "Workload scheduling for pipeline tasks" "Internal RHOAI"
        seldon = softwareSystem "Seldon" "Model serving from pipeline outputs" "External"

        // User interactions
        user -> dspo "Submits pipelines via REST/gRPC API" "HTTPS/443"
        user -> dashboard "Manages pipelines through UI"
        admin -> dspo "Creates DSPA CRs via kubectl"

        // Internal container interactions
        controller -> apiServer "Deploys and configures" "manifestival templates"
        controller -> persistenceAgent "Deploys" "manifestival templates"
        controller -> scheduledWorkflow "Deploys" "manifestival templates"
        controller -> mlmdGrpc "Deploys" "manifestival templates"
        controller -> mlmdEnvoy "Deploys" "manifestival templates"
        controller -> mariadb "Deploys and health-checks" "MySQL/3306"
        controller -> minio "Deploys and health-checks" "S3/9000"
        apiServer -> mariadb "Stores pipeline metadata" "MySQL/3306"
        apiServer -> minio "Stores pipeline artifacts" "S3/9000"
        mlmdGrpc -> mariadb "Stores ML metadata" "MySQL/3306"
        persistenceAgent -> apiServer "Syncs run status" "HTTP(S)/8888"
        oauthProxy -> apiServer "Proxies authenticated requests" "HTTP(S)/8888"
        oauthProxy -> mlmdEnvoy "Proxies authenticated requests" "gRPC/9090"
        mlmdEnvoy -> mlmdGrpc "Forwards gRPC" "gRPC/8080"

        // External interactions
        rhoaiOperator -> dspo "Manages deployment lifecycle" "DataScienceCluster CR"
        dashboard -> dspo "Pipeline management UI integration" "HTTPS/443 via Route"
        workbenches -> dspo "Submit and manage pipelines" "REST/8888, gRPC/8887"
        dspo -> argoWorkflows "Pipeline execution" "Workflow CRDs"
        dspo -> openshiftOAuth "Route authentication" "OAuth"
        dspo -> openshiftServiceCA "TLS certificate generation" "annotation-based"
        dspo -> k8sAPI "Resource management" "HTTPS/443"
        dspo -> extDB "External pipeline metadata" "MySQL/3306"
        dspo -> extS3 "External artifact storage" "HTTPS/443"
        openshiftMonitoring -> dspo "Scrapes metrics" "HTTP/8080, HTTP/8888"
        dspo -> ray "Distributed compute tasks" "RayCluster CRDs"
        dspo -> codeflare "Workload scheduling" "AppWrapper CRDs"
        dspo -> seldon "Model serving" "SeldonDeployment CRDs"
    }

    views {
        systemContext dspo "SystemContext" {
            include *
            autoLayout
        }

        container dspo "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438DD5
                color #ffffff
            }
            element "Person" {
                background #08427B
                color #ffffff
                shape person
            }
            element "Container" {
                background #438DD5
                color #ffffff
            }
            element "Database" {
                shape Cylinder
                background #f5a623
            }
            element "Storage" {
                shape Cylinder
                background #f5a623
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Platform" {
                background #7b7be0
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Internal" {
                background #50c878
                color #ffffff
            }
        }
    }
}
