// C4 Context Diagram - Distributed Workloads
// Generated by: Claude Opus 4.6

workspace {
    model {
        dataScientist = person "Data Scientist" "Runs distributed training jobs and fine-tunes ML models"
        mlEngineer = person "ML Engineer" "Builds and maintains training pipelines and runtime images"

        distributedWorkloads = softwareSystem "Distributed Workloads" "GPU-accelerated runtime container images and integration test suite for RHOAI distributed training stack" {
            runtimeImages = container "Runtime Container Images" "GPU-accelerated Ray and PyTorch training environments" "Container Images (UBI9)"
            rayCudaRuntime = container "Ray CUDA Runtime" "Ray 2.35.0 with CUDA 12.1, Python 3.11" "Container Image"
            rayRocmRuntime = container "Ray ROCm Runtime" "Ray 2.35.0 with ROCm 6.2, Python 3.11" "Container Image"
            trainingCudaRuntime = container "Training CUDA Runtime" "PyTorch 2.4.1 with CUDA 12.1, Flash Attention, RDMA" "Container Image"
            trainingRocmRuntime = container "Training ROCm Runtime" "PyTorch 2.4.1 with ROCm 6.2" "Container Image"
            testSuites = container "Integration Test Suites" "Go-based tests for KFTO, FMS, ODH, VAP validation" "Go Test Framework"
        }

        trainingOperator = softwareSystem "Kubeflow Training Operator" "Orchestrates distributed PyTorch training jobs via PyTorchJob CRD" "Internal RHOAI"
        kuberayOperator = softwareSystem "KubeRay Operator" "Manages Ray cluster lifecycle via RayCluster CRD" "Internal RHOAI"
        kueue = softwareSystem "Kueue" "Job queuing, admission control, and resource quota management" "Internal RHOAI"
        codeflareOperator = softwareSystem "CodeFlare Operator" "Workload fault tolerance via AppWrapper CRD" "Internal RHOAI"
        notebookController = softwareSystem "ODH Notebook Controller" "Manages Jupyter notebook lifecycle" "Internal RHOAI"
        odhDashboard = softwareSystem "ODH Dashboard" "Notebook spawner and management UI" "Internal RHOAI"
        prometheus = softwareSystem "OpenShift Prometheus" "Cluster monitoring and GPU utilization metrics" "Internal OpenShift"

        s3Storage = softwareSystem "S3-Compatible Storage" "Model and dataset storage (MinIO or cloud S3)" "External"
        huggingFaceHub = softwareSystem "HuggingFace Hub" "Pre-trained model repository" "External"
        quayRegistry = softwareSystem "quay.io/modh" "Container image registry for runtime images" "External"
        konfluxCI = softwareSystem "Konflux CI/CD" "Tekton-based build pipelines for container images" "External"
        kubernetesAPI = softwareSystem "Kubernetes API Server" "OpenShift cluster API" "External"

        // User interactions
        dataScientist -> distributedWorkloads "Submits training jobs using runtime images"
        dataScientist -> odhDashboard "Spawns notebooks via UI"
        mlEngineer -> distributedWorkloads "Builds runtime images, runs integration tests"

        // Internal dependencies (CRD-based)
        distributedWorkloads -> trainingOperator "Creates PyTorchJob CRDs" "HTTPS/6443"
        distributedWorkloads -> kuberayOperator "Creates RayCluster CRDs" "HTTPS/6443"
        distributedWorkloads -> kueue "Creates ClusterQueue, LocalQueue, ResourceFlavor CRDs" "HTTPS/6443"
        distributedWorkloads -> codeflareOperator "Creates AppWrapper CRDs" "HTTPS/6443"
        distributedWorkloads -> notebookController "Creates Notebook CRDs" "HTTPS/6443"

        // External dependencies
        distributedWorkloads -> s3Storage "Uploads/downloads models and datasets" "HTTPS/443"
        distributedWorkloads -> huggingFaceHub "Downloads pre-trained models" "HTTPS/443"
        distributedWorkloads -> kubernetesAPI "Manages cluster resources" "HTTPS/6443"
        distributedWorkloads -> prometheus "Queries GPU utilization metrics" "HTTPS/443"

        // Build pipeline
        konfluxCI -> quayRegistry "Pushes built runtime images" "HTTPS/443"
        konfluxCI -> distributedWorkloads "Builds runtime images from Dockerfiles"

        // Integration points (other components using DW)
        odhDashboard -> distributedWorkloads "Spawns notebooks using runtime images"
    }

    views {
        systemContext distributedWorkloads "SystemContext" {
            include *
            autoLayout
        }

        container distributedWorkloads "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438dd5
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Internal OpenShift" {
                background #9b59b6
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Person" {
                shape person
                background #08427b
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
