/*
 * C4 Context Diagram - Notebooks (Workbench Images)
 * Generated by: Claude Opus 4.6
 */

workspace {
    model {
        dataScientist = person "Data Scientist" "Selects and launches workbench environments for ML/DS work"

        notebooks = softwareSystem "Notebooks (Workbench Images)" "Pre-built container images for data science workbenches and pipeline runtimes" {
            jupyterImages = container "Jupyter Workbench Images" "Minimal, Data Science, PyTorch, TensorFlow, TrustyAI variants" "Container Image (UBI9/CUDA/ROCm)"
            ideImages = container "IDE Images" "code-server (VS Code), RStudio Server" "Container Image (UBI9/RHEL9)"
            runtimeImages = container "Elyra Runtime Images" "Minimal, Data Science, PyTorch, TensorFlow runtimes" "Container Image (UBI9/CUDA/ROCm)"
            imageStreams = container "ImageStream Manifests" "Kustomize manifests referencing pinned image digests" "Kustomize / YAML"
        }

        odhNotebookController = softwareSystem "ODH Notebook Controller" "Launches workbench pods, injects auth proxy sidecars" "Internal RHOAI"
        rhoaiDashboard = softwareSystem "RHOAI Dashboard" "Web UI for selecting and managing workbenches" "Internal RHOAI"
        rhodsOperator = softwareSystem "rhods-operator" "Deploys ImageStream manifests to cluster" "Internal RHOAI"
        elyra = softwareSystem "Elyra Pipeline Engine" "Executes data science pipelines using runtime images" "Internal RHOAI"
        kubeflowTraining = softwareSystem "Kubeflow Training Operator" "Distributed training framework" "Internal RHOAI"
        konflux = softwareSystem "Konflux CI/CD" "Tekton-based build pipelines for container images" "External"
        quayRegistry = softwareSystem "quay.io/modh" "Container image registry for published images" "External"
        github = softwareSystem "GitHub" "Source code repository" "External"
        ubi9 = softwareSystem "UBI9 / RHEL9 Base Images" "Red Hat base container images" "External"
        nvidiaCuda = softwareSystem "NVIDIA CUDA Toolkit" "GPU compute libraries (CUDA 12.6.3, cuDNN 9.5)" "External"
        openShiftAPI = softwareSystem "OpenShift API" "Kubernetes API server" "External"
        pypi = softwareSystem "PyPI" "Python package registry" "External"

        /* User interactions */
        dataScientist -> rhoaiDashboard "Selects workbench type" "HTTPS/443"
        rhoaiDashboard -> notebooks "Reads ImageStream annotations" "HTTPS/443"
        dataScientist -> notebooks "Uses workbench for ML development" "HTTPS/443 (via Route)"

        /* Internal RHOAI interactions */
        rhodsOperator -> notebooks "Deploys ImageStream manifests" "Kustomize"
        odhNotebookController -> notebooks "Launches workbench pods from images" "Container Image reference"
        elyra -> notebooks "Executes pipeline nodes using runtime images" "Container Image reference"
        kubeflowTraining -> notebooks "Uses bundled Python SDK" "In-process"

        /* Build pipeline */
        github -> konflux "Webhook triggers build" "HTTPS/443"
        konflux -> github "Clones source" "HTTPS/443"
        konflux -> quayRegistry "Pushes built images" "HTTPS/443"
        notebooks -> quayRegistry "Images published to" "HTTPS/443"

        /* Base image dependencies */
        notebooks -> ubi9 "Built on base images" "Container layer"
        notebooks -> nvidiaCuda "GPU compute layer" "Container layer"

        /* Runtime egress */
        notebooks -> openShiftAPI "oc CLI from workbenches" "HTTPS/443"
        notebooks -> pypi "Package installation" "HTTPS/443"
    }

    views {
        systemContext notebooks "SystemContext" {
            include *
            autoLayout
        }

        container notebooks "Containers" {
            include *
            autoLayout
        }

        styles {
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Person" {
                background #4a90e2
                color #ffffff
                shape Person
            }
            element "Software System" {
                background #4a90e2
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
