/* ODH Dashboard - C4 Context Diagram (Structurizr DSL)
 * Generated by: Claude Opus 4.6
 * Source: architecture/rhoai-2.19/odh-dashboard.md
 */

workspace {
    model {
        datascientist = person "Data Scientist" "Uses the dashboard to manage notebooks, models, and pipelines"
        admin = person "Platform Admin" "Configures dashboard settings, accelerator profiles, and platform features"

        odhDashboard = softwareSystem "ODH Dashboard (rhods-dashboard)" "Web-based management dashboard for Red Hat OpenShift AI providing unified UI for data science workflows" {
            oauthProxy = container "oauth-proxy Sidecar" "OpenShift OAuth authentication proxy, terminates TLS on port 8443" "ose-oauth-proxy"
            backend = container "Dashboard Backend" "Proxies Kubernetes API calls on behalf of authenticated user, serves frontend assets, provides REST API" "Node.js 20 / Fastify"
            frontend = container "Dashboard Frontend" "Single-page application providing web UI for data science workflow management" "React / TypeScript / PatternFly"
        }

        k8sAPI = softwareSystem "Kubernetes API Server" "Cluster API server for all resource operations" "External"
        oauthServer = softwareSystem "OpenShift OAuth Server" "Handles user authentication via OAuth2" "External"
        thanosQuerier = softwareSystem "Thanos Querier" "Prometheus metrics aggregation in openshift-monitoring namespace" "External"
        openshiftRouter = softwareSystem "OpenShift Router" "Ingress controller with TLS reencrypt" "External"
        openshiftConsole = softwareSystem "OpenShift Console" "OpenShift web console with ConsoleLink integration" "External"

        kserve = softwareSystem "KServe" "Model serving platform managing InferenceServices and ServingRuntimes" "Internal ODH"
        kubeflowNotebooks = softwareSystem "Kubeflow Notebook Controller" "Manages Jupyter notebook lifecycle" "Internal ODH"
        modelRegistry = softwareSystem "Model Registry Operator" "Stores and manages model metadata" "Internal ODH"
        dscOperator = softwareSystem "DataScienceCluster Operator" "Manages RHOAI platform components and status" "Internal ODH"
        nimOperator = softwareSystem "NVIDIA NIM Operator" "Manages NVIDIA NIM serving accounts" "Internal ODH"

        # Relationships - Users
        datascientist -> odhDashboard "Manages notebooks, models, pipelines via browser" "HTTPS/443"
        admin -> odhDashboard "Configures platform settings, profiles" "HTTPS/443"

        # Relationships - External
        openshiftRouter -> odhDashboard "Routes external traffic" "HTTPS/8443 TLS reencrypt"
        odhDashboard -> k8sAPI "Proxies all K8s operations on behalf of user" "HTTPS/443 Bearer Token"
        odhDashboard -> oauthServer "Authenticates users via OAuth2" "HTTPS/443"
        odhDashboard -> thanosQuerier "Queries Prometheus metrics" "HTTPS/9092 Bearer Token"
        odhDashboard -> openshiftConsole "Registers ConsoleLink in app menu" "ConsoleLink CR"

        # Relationships - Internal ODH
        odhDashboard -> kserve "Manages InferenceServices and ServingRuntimes" "CRD CRUD via K8s API"
        odhDashboard -> kubeflowNotebooks "Manages notebook lifecycle" "CRD CRUD via K8s API"
        odhDashboard -> modelRegistry "Manages model registries" "CRD CRUD via K8s API"
        odhDashboard -> dscOperator "Watches platform status and feature detection" "CRD watch via K8s API"
        odhDashboard -> nimOperator "Manages NIM accounts" "CRD CRUD via K8s API"

        # Container relationships
        openshiftRouter -> oauthProxy "TLS reencrypt" "HTTPS/8443"
        oauthProxy -> oauthServer "OAuth2 authentication flow" "HTTPS/443"
        oauthProxy -> backend "Forwards authenticated requests" "HTTP/8080 x-forwarded-access-token"
        backend -> frontend "Serves static assets" "filesystem"
        backend -> k8sAPI "Proxied API calls" "HTTPS/443 Bearer Token"
        backend -> thanosQuerier "Metrics queries" "HTTPS/9092 Bearer Token"
    }

    views {
        systemContext odhDashboard "SystemContext" {
            include *
            autoLayout
        }

        container odhDashboard "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Person" {
                shape Person
                background #08427b
                color #ffffff
            }
            element "Software System" {
                background #1168bd
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal ODH" {
                background #7ed321
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
