// TrustyAI Explainability - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6
// Source: architecture/rhoai-2.19/trustyai-explainability.md

workspace {
    model {
        user = person "Data Scientist / ML Engineer" "Monitors model fairness, drift, and requests explanations"

        trustyai = softwareSystem "TrustyAI Explainability" "AI fairness metrics, bias tracking, drift detection, and explainability for ML models" {
            service = container "explainability-service" "Quarkus REST service exposing fairness, drift, explainability, and data management endpoints" "Java 17, Quarkus 3.8.5"
            core = container "explainability-core" "Core XAI library with fairness metrics (SPD, DIR), explainers (LIME, SHAP, CF), and drift detectors" "Java Library"
            connectors = container "explainability-connectors" "KServe/ModelMesh connector with gRPC protobuf definitions for KServe v2 inference protocol" "Java Library, gRPC"
            arrow = container "explainability-arrow" "Apache Arrow bridge for Java-Python communication" "Java Library"
            initContainer = container "config-map-overrider" "Init container that configures ModelMesh to send payloads to TrustyAI" "ose-cli"
        }

        modelmesh = softwareSystem "ModelMesh Serving" "Model serving platform that sends inference payloads" "Internal RHOAI"
        kserve = softwareSystem "KServe" "Model serving platform with inference logger sending CloudEvents" "Internal RHOAI"
        operator = softwareSystem "TrustyAI Service Operator" "Manages TrustyAI deployment lifecycle, TLS, and configuration" "Internal RHOAI"
        prometheus = softwareSystem "Prometheus / OpenShift Monitoring" "Metrics collection and alerting" "External"
        dashboard = softwareSystem "OpenShift AI Dashboard" "Web UI for fairness/drift/explainability" "Internal RHOAI"
        mariadb = softwareSystem "MariaDB/MySQL" "Optional database storage backend" "External"
        minio = softwareSystem "MinIO" "Optional object storage backend" "External"
        pvc = softwareSystem "PVC Storage" "Persistent Volume for CSV flat file storage" "External"
        k8sapi = softwareSystem "Kubernetes API" "Cluster API server" "External"

        // User interactions
        user -> dashboard "Requests fairness metrics, drift analysis, explanations"
        dashboard -> trustyai "REST API calls" "HTTP/80"

        // Internal container relationships
        service -> core "Uses fairness, drift, explainability algorithms"
        service -> connectors "Uses gRPC client for model inference"
        connectors -> arrow "Optional Arrow data bridge"

        // Inbound data flows
        modelmesh -> trustyai "Sends inference payloads" "HTTP/80 POST /consumer/kserve/v2"
        kserve -> trustyai "Sends inference CloudEvents" "HTTP/8080 CloudEvents"

        // Outbound data flows
        trustyai -> kserve "Makes inference calls for explainability" "gRPC, TLS configurable"
        trustyai -> modelmesh "Makes inference calls for explainability" "gRPC, TLS configurable"

        // Monitoring
        prometheus -> trustyai "Scrapes metrics" "HTTP/80 GET /q/metrics, Bearer Token"

        // Storage
        trustyai -> pvc "Stores inference data" "Filesystem I/O"
        trustyai -> mariadb "Optional DB storage" "JDBC/3306, Username/Password"
        trustyai -> minio "Optional object storage" "HTTP(S)/9000 or 443, Access Key"

        // Management
        operator -> trustyai "Manages deployment, provisions TLS certs"
        initContainer -> k8sapi "Creates ConfigMaps" "HTTPS/443, SA Token"
    }

    views {
        systemContext trustyai "SystemContext" {
            include *
            autoLayout
        }

        container trustyai "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438dd5
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Person" {
                shape Person
                background #08427b
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
