// C4 Context Diagram - Distributed Workloads
// Generated by: Claude Opus 4.6

workspace {
    model {
        // Users
        mlEngineer = person "ML Engineer" "Runs distributed ML training jobs on the cluster"
        testEngineer = person "QE / Test Engineer" "Runs E2E integration tests for the distributed workloads stack"

        // Primary system
        distributedWorkloads = softwareSystem "Distributed Workloads" "Container runtime images for distributed ML training and E2E integration test suite" {
            trainingImages = container "Training Runtime Images" "PyTorch training environments with CUDA/ROCm GPU support" "Container Images (UBI9)"
            rayImages = container "Ray Runtime Images" "Ray cluster base images with GPU support" "Container Images (UBI9)"
            universalImages = container "Universal Training Images (TH06)" "Combined Jupyter workbench + ML runtime" "Container Images (UBI9)"
            testSuite = container "E2E Test Suite" "Go-based integration tests for KFTO, Trainer v2, KubeRay, Kueue" "Go Test Framework"
            testLib = container "Test Support Library" "Shared utilities for K8s, OpenShift, Ray, Kueue, Prometheus clients" "Go Library"
            tektonPipelines = container "Tekton Pipelines" "Konflux pipeline definitions for building container images" "Tekton CI/CD"
        }

        // Internal ODH/RHOAI dependencies
        kfto = softwareSystem "Kubeflow Training Operator" "Manages distributed PyTorch training jobs (PyTorchJob v1)" "Internal RHOAI"
        trainerV2 = softwareSystem "Kubeflow Trainer v2" "Manages training jobs (TrainJob, TrainingRuntime, ClusterTrainingRuntime)" "Internal RHOAI"
        kuberay = softwareSystem "KubeRay Operator" "Manages Ray cluster lifecycle (RayCluster, RayJob)" "Internal RHOAI"
        kueue = softwareSystem "Kueue" "Job queuing and resource quota management" "Internal RHOAI"
        jobsetCtrl = softwareSystem "JobSet Controller" "Grouped job management for Trainer v2" "Internal RHOAI"
        rhoaiOperator = softwareSystem "RHOAI Operator" "Platform component lifecycle management (DataScienceCluster)" "Internal RHOAI"
        monitoring = softwareSystem "OpenShift Monitoring" "Prometheus-based metrics collection and querying" "Internal OpenShift"

        // External dependencies
        s3 = softwareSystem "S3/MinIO Storage" "Training data and model artifact storage" "External"
        huggingface = softwareSystem "HuggingFace Hub" "Pre-trained model repository" "External"
        kubeAPI = softwareSystem "Kubernetes API" "Cluster API server for all CRD operations" "External"
        konflux = softwareSystem "Konflux" "CI/CD platform for container image builds" "External"

        // Relationships - Users
        mlEngineer -> distributedWorkloads "Uses training runtime images for ML jobs"
        testEngineer -> distributedWorkloads "Runs E2E integration tests"

        // Relationships - Internal containers
        testSuite -> testLib "Uses shared test utilities"
        tektonPipelines -> trainingImages "Builds" "Konflux Pipeline"
        tektonPipelines -> rayImages "Builds" "Konflux Pipeline"
        tektonPipelines -> universalImages "Builds" "Konflux Pipeline"

        // Relationships - Test suite to operators (via K8s API)
        testSuite -> kfto "Creates PyTorchJob CRs" "HTTPS/6443"
        testSuite -> trainerV2 "Creates TrainJob CRs" "HTTPS/6443"
        testSuite -> kuberay "Creates RayCluster/RayJob CRs" "HTTPS/6443"
        testSuite -> kueue "Creates ClusterQueue/LocalQueue" "HTTPS/6443"
        testSuite -> jobsetCtrl "Monitors JobSet lifecycle" "HTTPS/6443"
        testSuite -> rhoaiOperator "Reads DataScienceCluster state" "HTTPS/6443"
        testSuite -> monitoring "Queries training metrics" "HTTPS/443"
        testSuite -> kubeAPI "CRD CRUD operations" "HTTPS/6443"

        // Relationships - Runtime images to external
        trainingImages -> s3 "Downloads/uploads data and models" "HTTPS/443"
        trainingImages -> huggingface "Downloads pre-trained models" "HTTPS/443"
        rayImages -> s3 "Downloads/uploads data" "HTTPS/443"

        // Relationships - Build dependencies
        tektonPipelines -> konflux "Triggers builds" "HTTPS"
    }

    views {
        systemContext distributedWorkloads "SystemContext" {
            include *
            autoLayout
        }

        container distributedWorkloads "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Person" {
                shape person
                background #08427B
                color #ffffff
            }
            element "Software System" {
                background #1168bd
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Internal OpenShift" {
                background #f5a623
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Container" {
                background #438DD5
                color #ffffff
            }
        }
    }
}
