/*
 * Feast Operator - C4 Context Diagram (Structurizr DSL)
 * Generated by: Claude Opus 4.6
 */

workspace {
    model {
        user = person "Data Scientist / Admin" "Creates FeatureStore CRs and consumes features from ML applications"

        feastOperator = softwareSystem "Feast Operator" "Manages lifecycle of Feast feature stores on Kubernetes/OpenShift via FeatureStore CRs" {
            controller = container "FeatureStoreReconciler" "Reconciles FeatureStore CRs; creates Deployments, Services, ConfigMaps, PVCs, RBAC, CronJobs, Routes" "Go (controller-runtime)"
            notebookCtrl = container "NotebookConfigMapReconciler" "Watches Notebook CRs and creates feast client ConfigMaps" "Go (controller-runtime)"
            onlineStore = container "Online Store" "Serves features for online/real-time reads" "Python 3.11 (HTTP 6566/6567)"
            offlineStore = container "Offline Store" "Serves features for batch/offline reads" "Python 3.11 (HTTP 8815/8816)"
            registryServer = container "Registry Server" "Feature registry (gRPC 6570/6571, REST 6572/6573)" "Python 3.11"
            feastUI = container "Feast UI" "Web UI for browsing feature store metadata" "Python 3.11 (HTTP 8888/8443)"
            cronJob = container "CronJob" "Scheduled feast apply and materialize-incremental" "ose-cli"
        }

        rhodsOperator = softwareSystem "rhods-operator" "Deploys feast-operator via kustomize overlay" "Internal RHOAI"
        kubeflowNotebooks = softwareSystem "Kubeflow Notebooks" "Notebook environments for data scientists" "Internal ODH"
        openshiftServiceCA = softwareSystem "OpenShift Service CA" "Automatic TLS certificate provisioning" "OpenShift Platform"
        openshiftRouter = softwareSystem "OpenShift Route Controller" "Exposes services externally via Routes" "OpenShift Platform"
        prometheus = softwareSystem "Prometheus" "Metrics collection and monitoring" "OpenShift Platform"

        kubeAPI = softwareSystem "Kubernetes API Server" "Cluster control plane" "Platform"

        postgresql = softwareSystem "PostgreSQL" "Relational database for online/offline/registry persistence" "External"
        redis = softwareSystem "Redis" "In-memory store for online feature serving" "External"
        s3 = softwareSystem "S3 / GCS" "Object storage for registry file persistence" "External"
        gitRepo = softwareSystem "Git Repository" "Source for feast project files" "External"

        # Relationships - User
        user -> feastOperator "Creates FeatureStore CR via kubectl/oc" "HTTPS/443"
        user -> feastUI "Browses feature store metadata" "HTTPS/443 (via Route)"
        user -> onlineStore "Queries features from ML applications" "HTTP/80 or HTTPS/443"
        user -> offlineStore "Queries features for batch jobs" "HTTP/80 or HTTPS/443"

        # Relationships - Internal
        rhodsOperator -> feastOperator "Deploys via kustomize overlays/rhoai" "Kustomize"
        controller -> kubeAPI "Creates/manages Deployments, Services, ConfigMaps, PVCs, RBAC" "HTTPS/443"
        notebookCtrl -> kubeflowNotebooks "Watches Notebook CRs" "Kubernetes API"
        notebookCtrl -> kubeAPI "Creates feast-config ConfigMaps" "HTTPS/443"
        feastOperator -> openshiftServiceCA "Requests TLS certs via annotations" "Annotation-based"
        feastUI -> openshiftRouter "Exposed externally via OpenShift Route" "Route CR"
        prometheus -> feastOperator "Scrapes operator metrics" "HTTPS/8443"

        # Relationships - External
        onlineStore -> postgresql "Reads/writes features" "TCP/5432"
        onlineStore -> redis "Reads/writes features" "TCP/6379"
        offlineStore -> postgresql "Reads features" "TCP/5432"
        registryServer -> s3 "Persists registry files" "HTTPS/443"
        cronJob -> gitRepo "Clones feast project" "HTTPS/443"
        feastOperator -> s3 "Registry file persistence" "HTTPS/443"
    }

    views {
        systemContext feastOperator "SystemContext" {
            include *
            autoLayout
        }

        container feastOperator "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438dd5
                color #ffffff
            }
            element "Person" {
                background #08427b
                color #ffffff
                shape person
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Internal ODH" {
                background #7ed321
                color #ffffff
            }
            element "OpenShift Platform" {
                background #ee0000
                color #ffffff
            }
            element "Platform" {
                background #999999
                color #ffffff
            }
        }
    }
}
