// C4 Context Diagram - llama-stack-provider-ragas
// Generated by: Claude Opus 4.6

workspace {
    model {
        user = person "Data Scientist / ML Engineer" "Evaluates LLM outputs using Ragas metrics via Llama Stack eval API"

        llamaStackProviderRagas = softwareSystem "llama-stack-provider-ragas" "Ragas evaluation framework as Llama Stack provider plugin for LLM quality assessment" {
            inlineProvider = container "RagasEvaluatorInline" "Runs Ragas evaluation in-process within Llama Stack server" "Python Plugin (InlineProviderSpec)"
            remoteProvider = container "RagasEvaluatorRemote" "Submits Ragas evaluation as Kubeflow Pipeline runs" "Python Plugin (RemoteProviderSpec)"
            inlineLLM = container "LlamaStackInlineLLM" "Adapts Llama Stack inference API for Ragas LLM interface" "Python Wrapper (BaseRagasLLM)"
            inlineEmbeddings = container "LlamaStackInlineEmbeddings" "Adapts Llama Stack inference API for Ragas embeddings interface" "Python Wrapper (BaseRagasEmbeddings)"
            remoteLLM = container "LlamaStackRemoteLLM" "Adapts Llama Stack client SDK for Ragas LLM interface" "Python Wrapper (BaseRagasLLM)"
            remoteEmbeddings = container "LlamaStackRemoteEmbeddings" "Adapts Llama Stack client SDK for Ragas embeddings interface" "Python Wrapper (BaseRagasEmbeddings)"
            kfpPipeline = container "KFP Pipeline" "Two-step pipeline: retrieve data, run Ragas evaluation" "Kubeflow Pipeline Definition"
            compatLayer = container "Compatibility Layer" "Backward compatibility between llama_stack and llama_stack_api packages" "Python Module"
        }

        llamaStackServer = softwareSystem "Llama Stack Server" "Hosts provider plugins and serves Llama Stack API" "Internal RHOAI"
        llamaStackOperator = softwareSystem "Llama Stack Operator" "Deploys Llama Stack distributions via LlamaStackDistribution CRD" "Internal RHOAI"
        trustyaiOperator = softwareSystem "TrustyAI Service Operator" "Provides ragas-provider-image via ConfigMap" "Internal RHOAI"
        kubeflowPipelines = softwareSystem "Kubeflow Pipelines (Data Science Pipelines)" "Pipeline orchestration for remote evaluation" "Internal RHOAI"
        ollama = softwareSystem "Ollama" "LLM inference backend (default)" "External"
        vllm = softwareSystem "vLLM" "Production LLM inference backend" "External"
        s3Storage = softwareSystem "S3-compatible Storage" "Evaluation results persistence" "External"
        kubernetesAPI = softwareSystem "Kubernetes API" "ConfigMap reads and kubeconfig loading" "External"

        // User relationships
        user -> llamaStackProviderRagas "Submits evaluation jobs via Llama Stack eval API"

        // Internal relationships
        inlineProvider -> inlineLLM "Uses for LLM calls"
        inlineProvider -> inlineEmbeddings "Uses for embedding calls"
        remoteProvider -> remoteLLM "Uses for LLM calls"
        remoteProvider -> remoteEmbeddings "Uses for embedding calls"
        remoteProvider -> kfpPipeline "Submits pipeline runs"

        // System relationships
        llamaStackServer -> llamaStackProviderRagas "Loads as eval provider plugin" "Python API"
        llamaStackOperator -> llamaStackServer "Deploys distributions" "CRD"
        trustyaiOperator -> llamaStackProviderRagas "Provides base image config" "ConfigMap"
        llamaStackProviderRagas -> kubeflowPipelines "Submits and monitors evaluation pipelines" "HTTPS/443"
        llamaStackProviderRagas -> ollama "LLM inference and embeddings (inline)" "HTTP/11434"
        llamaStackProviderRagas -> vllm "LLM inference and embeddings (production)" "HTTP(S)/configurable"
        llamaStackProviderRagas -> s3Storage "Stores/retrieves evaluation results" "HTTPS/443"
        llamaStackProviderRagas -> kubernetesAPI "Reads ConfigMaps, loads kubeconfig" "HTTPS/6443"
        user -> llamaStackServer "Creates eval requests via kubectl or API" "HTTP/8321"
    }

    views {
        systemContext llamaStackProviderRagas "SystemContext" {
            include *
            autoLayout
        }

        container llamaStackProviderRagas "Containers" {
            include *
            autoLayout
        }

        styles {
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Person" {
                shape Person
                background #4a90e2
                color #ffffff
            }
            element "Software System" {
                background #4a90e2
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
