// ML Metadata (MLMD) - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6

workspace {
    model {
        datascientist = person "Data Scientist" "Creates and runs ML pipelines that produce metadata"

        mlmd = softwareSystem "ML Metadata (MLMD)" "gRPC server for recording and retrieving ML workflow metadata, artifacts, executions, and contexts" {
            server = container "metadata_store_server" "C++ gRPC server binary exposing MetadataStoreService API" "C++ / gRPC / HTTP2"
            serviceImpl = container "MetadataStoreServiceImpl" "Thread-safe gRPC service implementation" "C++ gRPC Service"
            metadataStore = container "MetadataStore" "Core metadata storage logic with connection pooling" "C++ Library"
            metadataAccessObject = container "MetadataAccessObject" "Database-agnostic CRUD abstraction" "C++ Library"
        }

        dspApiServer = softwareSystem "DSP API Server" "Data Science Pipelines API server that orchestrates pipeline runs" "Internal RHOAI"
        dspPersistenceAgent = softwareSystem "DSP Persistence Agent" "Persists pipeline run status and artifact metadata" "Internal RHOAI"
        kubeflowPipelines = softwareSystem "Kubeflow Pipelines" "Pipeline orchestration platform" "Internal RHOAI"
        mysql = softwareSystem "MySQL/MariaDB" "Relational database for metadata persistence" "Database"
        postgresql = softwareSystem "PostgreSQL" "Alternative relational database for metadata persistence" "Database"
        dspOperator = softwareSystem "DSP Operator" "Deploys and manages MLMD server and DSP components" "Internal RHOAI"

        // Relationships
        datascientist -> dspApiServer "Submits pipeline runs via"
        dspApiServer -> mlmd "Records/queries pipeline metadata" "gRPC/HTTP2 :8080"
        dspPersistenceAgent -> mlmd "Persists run status and artifacts" "gRPC/HTTP2 :8080"
        kubeflowPipelines -> mlmd "Stores pipeline metadata" "gRPC/HTTP2 :8080"
        mlmd -> mysql "Persists metadata" "MySQL :3306"
        mlmd -> postgresql "Persists metadata (alternative)" "PostgreSQL :5432"
        dspOperator -> mlmd "Deploys and configures"

        // Container relationships
        server -> serviceImpl "Hosts"
        serviceImpl -> metadataStore "Delegates to"
        metadataStore -> metadataAccessObject "Uses"
    }

    views {
        systemContext mlmd "SystemContext" {
            include *
            autoLayout
        }

        container mlmd "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438dd5
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Database" {
                background #f5a623
                color #ffffff
                shape Cylinder
            }
            element "Person" {
                background #08427b
                color #ffffff
                shape Person
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
