// MLflow Operator - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6
// Source: architecture/rhoai-3.4-ea.2/mlflow-operator.md

workspace {
    model {
        dataScientist = person "Data Scientist" "Creates experiments, tracks runs, registers models via MLflow"
        namespaceOwner = person "Namespace Owner" "Configures per-namespace artifact storage via MLflowConfig"
        platformAdmin = person "Platform Admin" "Deploys and manages MLflow instances via MLflow CR"

        mlflowOperator = softwareSystem "MLflow Operator" "Kubernetes operator that deploys and manages MLflow tracking server instances on OpenShift" {
            controllerManager = container "MLflow Operator Controller Manager" "Reconciles MLflow CRs, renders embedded Helm chart, creates K8s resources via Server-Side Apply" "Go (controller-runtime)"
            helmEngine = container "Embedded Helm Chart" "Templates for Deployment, Service, NetworkPolicy, PVC, RBAC, ServiceMonitor" "Helm v3 SDK"
            mlflowServer = container "MLflow Tracking Server" "Experiment tracking, model registry, artifact serving with K8s-native RBAC auth" "Python (uvicorn), 8443/TCP HTTPS"
            caBundleInit = container "CA Bundle Init Container" "Combines system, platform, and custom CA certificates" "Shell"
            caBundleWatcher = container "CA Bundle Watcher Sidecar" "Watches for CA ConfigMap changes and regenerates cert bundle" "Shell"
        }

        // Internal RHOAI dependencies
        rhodsOperator = softwareSystem "rhods-operator" "Deploys mlflow-operator via Kustomize overlays" "Internal RHOAI"
        dataScienceGateway = softwareSystem "data-science-gateway" "Shared Gateway API ingress (Envoy) in openshift-ingress namespace" "Internal RHOAI"
        openshiftConsole = softwareSystem "OpenShift Console" "Web console with application menu (ConsoleLink integration)" "Internal RHOAI"
        prometheus = softwareSystem "Prometheus" "Metrics collection via ServiceMonitor CRs" "Internal RHOAI"

        // External dependencies
        kubernetesAPI = softwareSystem "Kubernetes API Server" "Cluster API for resource management and RBAC authorization" "External"
        serviceCaOperator = softwareSystem "OpenShift service-ca Operator" "Provisions TLS certificates for services" "External"
        postgresqlDB = softwareSystem "PostgreSQL Database" "Backend store for experiment/run metadata and model registry" "External"
        mysqlDB = softwareSystem "MySQL Database" "Alternative backend store for metadata and model registry" "External"
        s3Storage = softwareSystem "S3-Compatible Storage" "Artifact storage for models, plots, and files (S3, MinIO, SeaweedFS)" "External"

        // Relationships - Users
        platformAdmin -> mlflowOperator "Creates MLflow CR (cluster-scoped)" "kubectl"
        namespaceOwner -> mlflowOperator "Creates MLflowConfig CR (namespace-scoped)" "kubectl"
        dataScientist -> mlflowOperator "Tracks experiments, registers models" "HTTPS/443 via Gateway"

        // Relationships - Internal container
        controllerManager -> helmEngine "Renders Helm templates"
        helmEngine -> mlflowServer "Deploys MLflow server pod"
        caBundleInit -> mlflowServer "Initializes CA certificates"
        caBundleWatcher -> mlflowServer "Updates CA certificates on changes"

        // Relationships - Internal RHOAI
        rhodsOperator -> mlflowOperator "Deploys operator via Kustomize" "Kustomize"
        mlflowOperator -> dataScienceGateway "Creates HTTPRoute for ingress" "Gateway API/8443"
        mlflowOperator -> openshiftConsole "Creates ConsoleLink for app menu" "ConsoleLink CR"
        prometheus -> mlflowOperator "Scrapes metrics" "HTTPS/8443"

        // Relationships - External
        mlflowOperator -> kubernetesAPI "Manages resources, RBAC checks" "HTTPS/6443"
        mlflowOperator -> serviceCaOperator "TLS certificate provisioning" "service annotation"
        mlflowOperator -> postgresqlDB "Stores metadata" "PostgreSQL/5432 TLS"
        mlflowOperator -> mysqlDB "Stores metadata" "MySQL/3306 TLS"
        mlflowOperator -> s3Storage "Stores/retrieves artifacts" "HTTPS/443,9000,8333"
    }

    views {
        systemContext mlflowOperator "SystemContext" {
            include *
            autoLayout
        }

        container mlflowOperator "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Person" {
                shape Person
                background #08427b
                color #ffffff
            }
            element "Software System" {
                background #1168bd
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
