// MLflow C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6
// Source: architecture/rhoai-3.4-ea.2/mlflow.md

workspace {
    model {
        dataScientist = person "Data Scientist" "Creates and tracks ML experiments, registers models, uses AI Gateway"
        mlEngineer = person "ML Engineer" "Deploys models, manages gateway endpoints"
        platformAdmin = person "Platform Admin" "Deploys and configures MLflow instances"

        mlflow = softwareSystem "MLflow" "ML experiment tracking, model registry, and AI gateway platform (RHOAI 3.4 EA2)" {
            trackingServer = container "MLflow Tracking Server" "Core API server for experiment tracking, model registry, and AI gateway" "Python (Flask + FastAPI, Gunicorn/Uvicorn)" "Service"
            webUI = container "MLflow Web UI" "Frontend for experiment visualization, model management, and gateway configuration" "React/TypeScript SPA" "WebApp"
            k8sAuthPlugin = container "Kubernetes Auth Plugin" "Enforces Kubernetes RBAC via SelfSubjectAccessReview/SubjectAccessReview" "Python Plugin" "Plugin"
            k8sWorkspaceProvider = container "Kubernetes Workspace Provider" "Maps Kubernetes namespaces to MLflow workspaces" "Python Plugin" "Plugin"
            namespaceCache = container "Namespace Cache" "Background thread maintaining cached namespace list" "Python Thread" "Background"
            mlflowConfigCache = container "MLflowConfig Cache" "Watches MLflowConfig CRDs for per-namespace artifact overrides" "Python Thread" "Background"
            aiGateway = container "AI Gateway" "Database-backed gateway for proxying LLM requests" "FastAPI Router" "Service"
            otlpIngestor = container "OTLP Trace Ingestor" "OpenTelemetry Protocol endpoint for span ingestion" "FastAPI Router" "Service"
            artifactProxy = container "Artifact Proxy" "Proxies artifact upload/download to storage backends" "Flask Handler" "Service"
            prometheusExporter = container "Prometheus Exporter" "Exposes Prometheus metrics at /metrics" "Flask Extension" "Monitoring"
        }

        kubeRBACProxy = softwareSystem "kube-rbac-proxy" "Authentication sidecar proxy injecting user identity headers" "Internal RHOAI"
        rhoaiPlatform = softwareSystem "OpenShift Data Science Platform" "Deploys and manages MLflow server instances" "Internal RHOAI"
        prometheus = softwareSystem "Prometheus" "Metrics collection and monitoring" "Internal"

        k8sAPI = softwareSystem "Kubernetes API Server" "Cluster API for RBAC, namespaces, secrets" "External"
        postgresql = softwareSystem "PostgreSQL" "Backend metadata store for experiments, runs, models, traces" "External"
        s3Storage = softwareSystem "S3-compatible Storage" "Artifact storage for model files, datasets, logs" "External"
        llmProviders = softwareSystem "LLM Providers" "OpenAI, Anthropic, Google Gemini, Mistral APIs" "External"
        platformGateway = softwareSystem "Platform Gateway" "data-science-gateway HTTPRoute for external access" "Internal RHOAI"

        // User relationships
        dataScientist -> mlflow "Tracks experiments, registers models, queries AI Gateway" "HTTPS/443, REST API"
        mlEngineer -> mlflow "Manages gateway endpoints, model deployments" "HTTPS/443, REST API"
        platformAdmin -> rhoaiPlatform "Deploys MLflow instances" "CLI/UI"

        // Internal container relationships
        trackingServer -> k8sAuthPlugin "Delegates auth" "Python call"
        trackingServer -> k8sWorkspaceProvider "Resolves workspace" "Python call"
        webUI -> trackingServer "REST/GraphQL API calls" "HTTP/5000"
        k8sAuthPlugin -> k8sAPI "SelfSubjectAccessReview / SubjectAccessReview" "HTTPS/443"
        k8sWorkspaceProvider -> namespaceCache "Reads cached namespaces" "In-memory"
        namespaceCache -> k8sAPI "Watch namespaces" "HTTPS/443"
        mlflowConfigCache -> k8sAPI "Watch MLflowConfig CRDs" "HTTPS/443"
        aiGateway -> llmProviders "Proxied LLM requests" "HTTPS/443"
        artifactProxy -> s3Storage "Upload/download artifacts" "HTTPS/443, S3 API"

        // External relationships
        mlflow -> k8sAPI "Namespace listing, RBAC authorization, Secret access, MLflowConfig watch" "HTTPS/443"
        mlflow -> postgresql "Persistent storage for experiments, runs, models, gateway config, traces" "PostgreSQL/5432"
        mlflow -> s3Storage "Artifact storage (model files, datasets, logs)" "HTTPS/443, S3 REST API"
        mlflow -> llmProviders "AI Gateway proxied inference requests" "HTTPS/443"

        platformGateway -> kubeRBACProxy "Routes external traffic" "HTTPS/8443"
        kubeRBACProxy -> mlflow "Forwards authenticated requests with identity headers" "HTTP/5000"
        rhoaiPlatform -> mlflow "Deploys and manages" "Kubernetes API"
        prometheus -> mlflow "Scrapes metrics" "HTTP/5000 GET /metrics"
    }

    views {
        systemContext mlflow "SystemContext" "MLflow system context showing external dependencies and users" {
            include *
            autoLayout
        }

        container mlflow "Containers" "MLflow internal container architecture" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438dd5
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Internal" {
                background #7ed321
                color #ffffff
            }
            element "Person" {
                shape Person
                background #08427b
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
            element "Service" {
                shape RoundedBox
            }
            element "WebApp" {
                shape WebBrowser
            }
            element "Plugin" {
                shape Component
            }
            element "Background" {
                shape Circle
                background #85bbf0
            }
            element "Monitoring" {
                shape Hexagon
                background #85bbf0
            }
        }
    }
}
