// C4 Context Diagram: Models as a Service (MaaS)
// Generated by: Claude Opus 4.6
// Source: architecture/rhoai-3.4-ea.2/models-as-a-service.md

workspace {
    model {
        user = person "Data Scientist / API Consumer" "Creates API keys, subscribes to models, and sends inference requests"

        maas = softwareSystem "Models as a Service (MaaS)" "Platform for serving LLM inference models with API key management, tiered subscriptions, and token-based rate limiting" {
            maasApi = container "maas-api" "REST API for API key lifecycle management, model discovery, tier lookups, and subscription selection" "Go (Gin)" {
                keyMgmt = component "API Key Management" "CRUD operations for hash-based API keys (sk-oai-* format)" "Go"
                modelDiscovery = component "Model Discovery" "Lists available LLM models in OpenAI-compatible format" "Go"
                tierLookup = component "Tier Lookup" "Determines subscription tier from user group memberships" "Go"
                keyValidation = component "API Key Validation" "Internal endpoint called by Authorino for key validation" "Go"
                subscriptionSelect = component "Subscription Selection" "Internal endpoint called by Authorino for rate limit tier" "Go"
            }
            maasController = container "maas-controller" "Reconciles MaaSModelRef, MaaSAuthPolicy, MaaSSubscription CRs into Kuadrant policies" "Go (controller-runtime)" {
                modelRefCtrl = component "MaaSModelRef Controller" "Watches MaaSModelRef CRs, validates HTTPRoutes, resolves model endpoints" "controller-runtime"
                authPolicyCtrl = component "MaaSAuthPolicy Controller" "Aggregates MaaSAuthPolicy CRs into per-model Kuadrant AuthPolicies" "controller-runtime"
                subscriptionCtrl = component "MaaSSubscription Controller" "Aggregates MaaSSubscription CRs into per-model Kuadrant TokenRateLimitPolicies" "controller-runtime"
            }
            gateway = container "maas-default-gateway" "Central ingress gateway for all MaaS traffic" "Gateway API (openshift-default)"
        }

        // External Dependencies
        kuadrantAuthorino = softwareSystem "Kuadrant Authorino" "Authentication and authorization policy enforcement" "External"
        kuadrantLimitador = softwareSystem "Kuadrant Limitador" "Token-based rate limiting enforcement" "External"
        gatewayAPI = softwareSystem "Gateway API" "Traffic routing via Gateway and HTTPRoute resources" "External"
        postgresql = softwareSystem "PostgreSQL" "API key storage with hash-based keys, expiration, and usage tracking" "External"
        certManager = softwareSystem "cert-manager" "TLS certificate provisioning (optional)" "External"

        // Internal ODH Dependencies
        kserve = softwareSystem "KServe (LLMInferenceService)" "Model serving platform creating HTTPRoutes for inference endpoints" "Internal ODH"
        odhOperator = softwareSystem "ODH/RHOAI Operator" "Deploys MaaS components when modelsAsService is enabled" "Internal ODH"
        k8sAPI = softwareSystem "Kubernetes API" "CRD reconciliation, ConfigMap access, TokenReview" "External"

        // Relationships
        user -> maas "Creates API keys, lists models, sends inference requests" "HTTPS/443"
        user -> gateway "Sends requests via" "HTTPS/443 TLS"

        gateway -> kuadrantAuthorino "ExtAuth policy evaluation" "gRPC mTLS"
        kuadrantAuthorino -> maasApi "API key validation and subscription selection callbacks" "HTTPS/8443"
        gateway -> kuadrantLimitador "Token rate limit checks" "gRPC mTLS"
        gateway -> kserve "Forwards inference requests to model backends" "HTTP/HTTPS"

        maasApi -> postgresql "Stores and retrieves API keys" "PostgreSQL/5432"
        maasApi -> k8sAPI "TokenReview, ConfigMap access" "HTTPS/443"

        maasController -> k8sAPI "Watches CRs, creates Kuadrant policies" "HTTPS/443"
        maasController -> kserve "Watches LLMInferenceService readiness" "HTTPS/443"

        maas -> kuadrantAuthorino "Uses for authentication/authorization via AuthPolicy CRs"
        maas -> kuadrantLimitador "Uses for rate limiting via TokenRateLimitPolicy CRs"
        maas -> gatewayAPI "Uses for traffic routing via Gateway and HTTPRoute"
        maas -> certManager "Uses for TLS certificate provisioning (optional)"

        odhOperator -> maas "Deploys when modelsAsService enabled in DataScienceCluster"
    }

    views {
        systemContext maas "SystemContext" {
            include *
            autoLayout
        }

        container maas "Containers" {
            include *
            autoLayout
        }

        component maasApi "MaaSApiComponents" {
            include *
            autoLayout
        }

        component maasController "MaaSControllerComponents" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #4a90e2
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal ODH" {
                background #7ed321
                color #ffffff
            }
            element "Person" {
                background #08427b
                color #ffffff
                shape Person
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
            element "Component" {
                background #85bbf0
                color #000000
            }
        }
    }
}
