// NeMo Guardrails - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6
// Source: architecture/rhoai-3.4-ea.2/NeMo-Guardrails.md

workspace {
    model {
        developer = person "Application Developer" "Builds LLM-powered applications with guardrails"
        aiEngineer = person "AI Engineer" "Configures guardrail policies and Colang flows"

        nemoGuardrails = softwareSystem "NeMo Guardrails" "Programmable safety guardrails proxy for LLM-based conversational systems" {
            guardrailsServer = container "Guardrails Server" "OpenAI-compatible API server applying input/output rails" "Python FastAPI/Uvicorn" "Port 8000"
            actionsServer = container "Actions Server" "Standalone server for executing guardrail actions" "Python FastAPI" "Port 8001"
            iorailsEngine = container "IORails Engine" "Optimized engine for input/output-only guardrail configurations" "Python Module"
            llmrailsEngine = container "LLMRails Engine" "Full-featured engine with dialog flows and Colang scripts" "Python Module"
            railsManager = container "Rails Manager" "Orchestrates rail execution routing to model engines" "Python Module"
            modelManager = container "Model Manager" "Manages NLP model lifecycle (spaCy, transformers, FastEmbed)" "Python Module"
            guardrailsLibrary = container "Guardrails Library" "20+ guardrail implementations (content safety, jailbreak, PII, etc.)" "Python Modules"
            colangRuntime = container "Colang Runtime" "DSL runtime for conversational guardrail flows" "Python Module"
            dataStore = container "DataStore" "Pluggable conversation state persistence" "Python Interface"

            guardrailsServer -> railsManager "Routes requests to"
            railsManager -> iorailsEngine "Uses for IO-only configs"
            railsManager -> llmrailsEngine "Uses for full dialog configs"
            railsManager -> modelManager "Loads NLP models via"
            railsManager -> guardrailsLibrary "Executes rails from"
            llmrailsEngine -> colangRuntime "Executes Colang flows via"
            guardrailsServer -> dataStore "Persists conversation state"
        }

        // Upstream LLM
        llmEndpoint = softwareSystem "Upstream LLM Endpoint" "Backend LLM inference service (vLLM, TGI, OpenAI, NVIDIA NIM)" "External"

        // Optional Services
        redis = softwareSystem "Redis" "Optional persistent conversation thread storage" "External"
        otelCollector = softwareSystem "OpenTelemetry Collector" "Optional distributed tracing collection" "External"

        // RHOAI Internal
        trustyai = softwareSystem "TrustyAI" "Responsible AI stack within RHOAI" "Internal RHOAI"

        // Relationships
        developer -> nemoGuardrails "Sends chat completions via HTTP/8000"
        aiEngineer -> nemoGuardrails "Configures guardrails via ConfigMaps"
        nemoGuardrails -> llmEndpoint "Forwards approved requests" "HTTPS/443 TLS 1.2+ Bearer Token"
        nemoGuardrails -> redis "Stores conversation state" "Redis/6379 Optional TLS"
        nemoGuardrails -> otelCollector "Exports traces" "OTLP HTTP/gRPC"
        trustyai -> nemoGuardrails "Part of responsible AI stack"
    }

    views {
        systemContext nemoGuardrails "SystemContext" {
            include *
            autoLayout
        }

        container nemoGuardrails "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #4a90e2
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Person" {
                background #08427b
                color #ffffff
                shape person
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
