/*
 * NeMo Guardrails - C4 Context Diagram (Structurizr DSL)
 * Generated by: Claude Opus 4.6
 * Source: architecture/rhoai-3.4-ea.2/NeMo-Guardrails.md
 */

workspace {
    model {
        user = person "Application Developer / Client" "Sends chat completion requests requiring guardrails enforcement"

        nemoGuardrails = softwareSystem "NeMo Guardrails" "Programmable guardrails toolkit for controlling and securing LLM-based conversational systems" {
            server = container "NeMo Guardrails Server" "OpenAI-compatible API server with guardrails extensions" "FastAPI / Python 3.12 / UBI9"
            railsEngine = container "Rails Engine" "Core LLM rails engine (LLMRails, RailsConfig)" "Python Module"
            colangRuntime = container "Colang Runtime" "Colang DSL runtime (v1.0 and v2.x) for defining guardrail flows" "Python Module"
            guardrailsLibrary = container "Guardrails Library" "20+ guardrail modules: content safety, hallucination, jailbreak, injection, PII detection, topic safety" "Python Module"
            embeddingsModule = container "Embeddings Module" "Embedding providers for similarity search and knowledge base" "Python Module"
            actionFramework = container "Action Framework" "Action execution framework for guardrail logic" "Python Module"
            langchainIntegration = container "LangChain Integration" "LLM provider abstraction via LangChain" "Python Module"
            datastore = container "Datastore" "Thread/conversation state persistence (memory or Redis)" "Python Module"
            tracingModule = container "Tracing Module" "OpenTelemetry-based tracing and interaction logging" "Python Module"
        }

        llmEndpoint = softwareSystem "LLM Inference Endpoint" "Backend LLM for text generation and guardrail evaluation (vLLM, NVIDIA NIM, OpenAI)" "External"
        rhoaiPlatform = softwareSystem "RHOAI Platform" "Platform gateway, auth, and configuration management" "Internal RHOAI"
        redis = softwareSystem "Redis" "Optional thread/conversation state persistence backend" "External"
        otelCollector = softwareSystem "OpenTelemetry Collector" "Distributed tracing collection and export" "External"

        # External relationships
        user -> nemoGuardrails "Sends chat completions and guardrail check requests" "HTTPS/443 via platform gateway"
        nemoGuardrails -> llmEndpoint "Evaluates guardrails and generates text" "HTTPS/443 or HTTP/8000, API Key"
        nemoGuardrails -> redis "Persists conversation state (optional)" "TCP/6379, Optional TLS"
        nemoGuardrails -> otelCollector "Exports distributed traces (optional)" "gRPC/4317 or HTTP/4318"
        rhoaiPlatform -> nemoGuardrails "Routes traffic and enforces auth" "HTTPRoute, kube-rbac-proxy"

        # Container relationships
        server -> railsEngine "Processes requests through rails pipeline"
        railsEngine -> colangRuntime "Executes Colang flow definitions"
        railsEngine -> guardrailsLibrary "Invokes guardrail modules (input/dialog/output rails)"
        railsEngine -> actionFramework "Executes guardrail actions"
        railsEngine -> embeddingsModule "Computes embeddings for similarity search"
        railsEngine -> langchainIntegration "Abstracts LLM provider communication"
        server -> datastore "Manages conversation thread state"
        server -> tracingModule "Records interaction traces"
        langchainIntegration -> llmEndpoint "Sends LLM requests" "HTTPS/443, Bearer Token"
        datastore -> redis "Persists state (optional)" "TCP/6379"
        tracingModule -> otelCollector "Exports traces" "gRPC/4317"
    }

    views {
        systemContext nemoGuardrails "SystemContext" {
            include *
            autoLayout
        }

        container nemoGuardrails "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438DD5
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Person" {
                shape person
                background #08427B
                color #ffffff
            }
            element "Container" {
                background #438DD5
                color #ffffff
            }
        }
    }
}
