// RHOAI Build Config - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6
// Source: architecture/rhoai-3.4-ea.2/RHOAI-Build-Config.md

workspace {
    model {
        // People
        developer = person "Developer / Release Engineer" "Commits build config changes, triggers builds"
        clusterAdmin = person "Cluster Administrator" "Installs and upgrades RHOAI operator via OLM"

        // Primary System
        buildConfig = softwareSystem "RHOAI-Build-Config" "Central build orchestration repository for Red Hat OpenShift AI. Houses OLM bundle, FBC catalog, and CI/CD pipeline definitions." {
            bundle = container "Operator Bundle" "OLM Bundle Image packaging CSV, CRDs, RBAC for rhods-operator" "OLM Bundle"
            fbcFragment = container "FBC Fragment" "Per-OCP-version file-based catalog defining operator channel and upgrade graph" "OLM Catalog"
            buildConfigYAML = container "Build Config" "YAML mapping staging (quay.io) to production (registry.redhat.io) images" "YAML Configuration"
            tektonPipelines = container "Tekton Pipelines" "Konflux push and scheduled build pipelines for bundle and FBC" "Tekton/Konflux"
            githubWorkflows = container "GitHub Workflows" "Bundle/FBC processing, nightly triggers, stage push, auto-merge" "GitHub Actions"
            integrationTests = container "Integration Tests" "Enterprise contract validation and integration test definitions" "Test Configuration"
            releaseArtifacts = container "Release Artifacts" "Stage and production release component and FBC snapshot definitions" "Release YAML"
        }

        // External Systems - CI/CD
        github = softwareSystem "GitHub" "Source code hosting for RHOAI-Build-Config repository" "External"
        konflux = softwareSystem "Konflux" "Tekton-based CI/CD build system for Red Hat" "External"
        enterpriseContract = softwareSystem "Enterprise Contract" "Release gate verification system" "External"

        // External Systems - Registries
        quayStaging = softwareSystem "quay.io (Staging)" "Staging container image registry" "External"
        registryProd = softwareSystem "registry.redhat.io (Production)" "Production container image registry" "External"
        brewRegistry = softwareSystem "brew.registry.redhat.io" "Base image registry for FBC builds" "External"

        // External Systems - Platform
        ocp = softwareSystem "OpenShift Container Platform" "Target platform (v4.19, v4.20, v4.21)" "External"
        olm = softwareSystem "OLM" "Operator Lifecycle Manager for operator installation" "External"
        operatorSDK = softwareSystem "operator-sdk" "Bundle building and validation tooling (v1.39.2)" "External"
        opm = softwareSystem "opm" "FBC catalog image building tool" "External"

        // Internal ODH Systems
        rhodsOperator = softwareSystem "rhods-operator" "The operator binary shipped in the bundle CSV (92 RELATED_IMAGEs)" "Internal RHOAI"
        odhDashboard = softwareSystem "ODH Dashboard" "Dashboard UI component" "Internal RHOAI"
        kserve = softwareSystem "KServe" "Model serving inference platform" "Internal RHOAI"
        dsp = softwareSystem "Data Science Pipelines" "ML pipeline orchestration" "Internal RHOAI"
        modelRegistry = softwareSystem "Model Registry" "Model metadata registry" "Internal RHOAI"
        trainingOperator = softwareSystem "Training Operator" "Distributed training operator" "Internal RHOAI"

        // Relationships - People
        developer -> buildConfig "Commits build config changes via"
        clusterAdmin -> olm "Installs RHOAI operator via"

        // Relationships - Build Flow
        buildConfig -> github "Source hosted on" "HTTPS/443"
        buildConfig -> konflux "Builds triggered via" "Tekton Pipelines"
        konflux -> quayStaging "Pushes bundle/FBC images to" "HTTPS/443"
        konflux -> brewRegistry "Pulls FBC base images from" "HTTPS/443"
        konflux -> enterpriseContract "Validates releases with" "HTTPS/443"

        // Relationships - Installation Flow
        olm -> registryProd "Pulls operator bundle/catalog from" "HTTPS/443"
        olm -> ocp "Installs operator on" "Kubernetes API"

        // Relationships - Internal Components
        buildConfig -> rhodsOperator "Packages and ships" "OLM Bundle"
        buildConfig -> odhDashboard "Pins image digest for" "RELATED_IMAGE"
        buildConfig -> kserve "Pins image digest for" "RELATED_IMAGE"
        buildConfig -> dsp "Pins image digest for" "RELATED_IMAGE"
        buildConfig -> modelRegistry "Pins image digest for" "RELATED_IMAGE"
        buildConfig -> trainingOperator "Pins image digest for" "RELATED_IMAGE"

        // Container relationships
        tektonPipelines -> bundle "Builds"
        tektonPipelines -> fbcFragment "Builds"
        githubWorkflows -> bundle "Processes"
        buildConfigYAML -> bundle "Provides image mappings to"
        integrationTests -> bundle "Validates"
    }

    views {
        systemContext buildConfig "SystemContext" {
            include *
            autoLayout
        }

        container buildConfig "Containers" {
            include *
            autoLayout
        }

        styles {
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Software System" {
                background #4a90e2
                color #ffffff
            }
            element "Container" {
                background #4a90e2
                color #ffffff
            }
            element "Person" {
                background #08427b
                color #ffffff
                shape Person
            }
        }
    }
}
