// RHOAI Operator (rhods-operator) - C4 Context Diagram
// Generated by: Claude Opus 4.6

workspace {
    model {
        admin = person "Platform Admin" "Configures RHOAI platform via DSC and DSCI Custom Resources"
        datascientist = person "Data Scientist" "Uses RHOAI Dashboard, Workbenches, Model Serving, Pipelines"

        rhoaiOperator = softwareSystem "RHOAI Operator (rhods-operator)" "Central control plane for Red Hat OpenShift AI - manages lifecycle of all AI/ML platform components" {
            dsciController = container "DSCInitialization Controller" "Platform initialization: namespace, monitoring, service mesh, CA bundles, auth, gateway config" "Go Controller (controller-runtime)"
            dscController = container "DataScienceCluster Controller" "Manages component lifecycle via component CRs" "Go Controller (controller-runtime)"
            gatewayController = container "Gateway Controller" "Deploys Gateway API infrastructure: GatewayClass, Gateway, kube-auth-proxy, EnvoyFilter, DestinationRule" "Go Controller (controller-runtime)"
            authController = container "Auth Controller" "Manages RBAC: ClusterRoles, ClusterRoleBindings for admin/allowed groups" "Go Controller (controller-runtime)"
            monitoringController = container "Monitoring Controller" "Deploys MonitoringStack, Prometheus rules, Tempo, OpenTelemetry" "Go Controller (controller-runtime)"
            certController = container "CertConfigMapGenerator" "Generates and distributes TLS certificates and CA configmaps" "Go Controller (controller-runtime)"
            componentControllers = container "Component Controllers (16)" "Individual controllers for Dashboard, Workbenches, KServe, DSP, ModelRegistry, TrustyAI, Ray, Kueue, etc." "Go Controllers (controller-runtime)"
            webhookServer = container "Webhook Server" "Validating/defaulting webhooks for DSC, DSCI, Auth, Monitoring CRDs" "Admission Webhooks (9443/TCP)"
            kubeAuthProxy = container "kube-auth-proxy" "OAuth2/OIDC authentication proxy for Gateway API ingress" "Deployment (HPA 2-10 replicas)"
            dashboardRedirect = container "dashboard-redirect" "Nginx-based 301 redirect from legacy URLs to Gateway API hostname" "nginx Deployment"
        }

        kubernetesAPI = softwareSystem "Kubernetes API Server" "Cluster control plane" "External"
        istio = softwareSystem "Istio / Service Mesh" "EnvoyFilter, DestinationRule for gateway auth integration" "External"
        openshiftGW = softwareSystem "OpenShift Gateway Controller" "Implements Gateway API (openshift.io/gateway-controller/v1)" "External"
        oauthProvider = softwareSystem "OAuth/OIDC Provider" "OpenShift OAuth Server or External OIDC (ROSA/ARO)" "External"
        olm = softwareSystem "OLM (Operator Lifecycle Manager)" "Operator installation and upgrade management" "External"
        certManager = softwareSystem "cert-manager" "TLS certificate provisioning (optional)" "External"

        // Internal ODH Components (managed by operator)
        dashboard = softwareSystem "ODH Dashboard" "Dashboard UI" "Internal ODH"
        notebookController = softwareSystem "Notebook Controller" "Workbench/Notebook management" "Internal ODH"
        kserve = softwareSystem "KServe" "Model serving infrastructure" "Internal ODH"
        dsp = softwareSystem "Data Science Pipelines" "Pipeline orchestration" "Internal ODH"
        modelRegistry = softwareSystem "Model Registry" "Model metadata registry" "Internal ODH"
        trustyai = softwareSystem "TrustyAI" "AI explainability" "Internal ODH"
        kuberay = softwareSystem "KubeRay" "Distributed computing (Ray)" "Internal ODH"
        kueue = softwareSystem "Kueue" "Job scheduling" "Internal ODH"
        trainingOperator = softwareSystem "Training Operator" "Training workloads" "Internal ODH"
        modelController = softwareSystem "ODH Model Controller" "Model routing" "Internal ODH"
        monitoring = softwareSystem "Prometheus / MonitoringStack" "Monitoring, alerting, observability" "External"

        // Relationships
        admin -> rhoaiOperator "Creates DSCInitialization and DataScienceCluster CRs via kubectl"
        datascientist -> rhoaiOperator "Accesses platform via Gateway API (rh-ai.{domain})"

        rhoaiOperator -> kubernetesAPI "CR management, resource CRUD, status updates" "HTTPS/6443"
        rhoaiOperator -> istio "Creates EnvoyFilter and DestinationRule" ""
        rhoaiOperator -> openshiftGW "Creates GatewayClass and Gateway resources" ""
        rhoaiOperator -> oauthProvider "kube-auth-proxy authenticates users" "HTTPS/443"
        olm -> rhoaiOperator "Installs and upgrades operator via CSV/Subscription" ""
        rhoaiOperator -> certManager "Optional TLS certificate provisioning" ""

        rhoaiOperator -> dashboard "Deploys via Kustomize manifests" ""
        rhoaiOperator -> notebookController "Deploys via Kustomize manifests" ""
        rhoaiOperator -> kserve "Deploys via Kustomize manifests" ""
        rhoaiOperator -> dsp "Deploys via Kustomize manifests" ""
        rhoaiOperator -> modelRegistry "Deploys via Kustomize manifests" ""
        rhoaiOperator -> trustyai "Deploys via Kustomize manifests" ""
        rhoaiOperator -> kuberay "Deploys via Kustomize manifests" ""
        rhoaiOperator -> kueue "Deploys via Kustomize manifests" ""
        rhoaiOperator -> trainingOperator "Deploys via Kustomize manifests" ""
        rhoaiOperator -> modelController "Deploys via Kustomize manifests" ""
        rhoaiOperator -> monitoring "Deploys MonitoringStack, Prometheus rules" ""

        // Container relationships
        dsciController -> gatewayController "Creates GatewayConfig CR"
        dsciController -> authController "Creates Auth CR"
        dsciController -> monitoringController "Creates Monitoring CR"
        dscController -> componentControllers "Creates component CRs"
        gatewayController -> kubeAuthProxy "Deploys and configures"
        gatewayController -> dashboardRedirect "Deploys redirect infrastructure"
    }

    views {
        systemContext rhoaiOperator "SystemContext" {
            include *
            autoLayout
        }

        container rhoaiOperator "Containers" {
            include *
            autoLayout
        }

        styles {
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal ODH" {
                background #7ed321
                color #ffffff
            }
            element "Person" {
                shape Person
                background #4a90e2
                color #ffffff
            }
            element "Software System" {
                background #4a90e2
                color #ffffff
            }
            element "Container" {
                background #5ba3f5
                color #ffffff
            }
        }
    }
}
