/*
 * Spark Operator - C4 Context Diagram (Structurizr DSL)
 * Generated by: Claude Opus 4.6
 * Source: architecture/rhoai-3.4-ea.2/spark-operator.md
 */

workspace {
    model {
        user = person "Data Engineer / Data Scientist" "Submits and manages Apache Spark applications on OpenShift"

        sparkOperator = softwareSystem "Spark Operator" "Kubernetes operator for managing Apache Spark application lifecycle including submission, scheduling, monitoring, and scaling" {
            controller = container "spark-operator-controller" "Manages SparkApplication, ScheduledSparkApplication, and SparkConnect CRs; creates driver/executor pods, services, ingresses" "Go Operator (controller-runtime)" "Operator"
            webhook = container "spark-operator-webhook" "Mutates Spark pods (injects config, volumes, env vars) and validates SparkApplication resources" "Go Webhook Server" "Webhook"
            sparkSubmit = container "spark-submit" "Embedded Spark submit for launching driver pods" "Apache Spark 4.0.1" "Runtime"
        }

        k8sApi = softwareSystem "Kubernetes API Server" "Core platform for pod, service, configmap, ingress management" "External"
        prometheus = softwareSystem "Prometheus" "Metrics collection and monitoring" "External"
        rhodsOperator = softwareSystem "rhods-operator" "RHOAI operator that deploys Spark Operator via kustomize overlays" "Internal RHOAI"

        volcano = softwareSystem "Volcano Scheduler" "Optional batch scheduler for gang scheduling" "External Optional"
        yunikorn = softwareSystem "YuniKorn Scheduler" "Optional batch scheduler for queue-based scheduling" "External Optional"

        sparkDriver = softwareSystem "Spark Driver Pod" "Runs the Spark driver process, created by operator" "Managed Workload"
        sparkExecutors = softwareSystem "Spark Executor Pods" "Run Spark tasks, created by driver" "Managed Workload"
        sparkConnect = softwareSystem "Spark Connect Server" "Provides gRPC-based Spark Connect interface" "Managed Workload"

        /* Relationships */
        user -> sparkOperator "Creates SparkApplication, ScheduledSparkApplication, SparkConnect CRs" "kubectl / HTTPS 443"
        user -> sparkDriver "Connects to Spark UI" "HTTP 4040"
        user -> sparkConnect "Sends Spark queries" "gRPC 15002"

        sparkOperator -> k8sApi "Watches CRDs, manages pods/services/ingresses" "HTTPS/443 TLS SA Token"
        k8sApi -> webhook "Admission webhook calls" "HTTPS/443→9443 TLS"
        controller -> sparkSubmit "Launches Spark driver" "Local exec"

        sparkDriver -> k8sApi "Creates executor pods" "HTTPS/443 TLS SA Token"
        sparkDriver -> sparkExecutors "Spark RPC communication" "TCP/7078, 7079 plaintext"
        sparkConnect -> sparkExecutors "Spark RPC communication" "TCP/7078, 7079 plaintext"

        rhodsOperator -> sparkOperator "Deploys via kustomize overlay" "Kustomize"

        prometheus -> sparkOperator "Scrapes metrics" "HTTP/8080 plaintext"

        sparkOperator -> volcano "Optional gang scheduling" "CRD API HTTPS/443"
        sparkOperator -> yunikorn "Optional queue scheduling" "CRD API HTTPS/443"
    }

    views {
        systemContext sparkOperator "SystemContext" {
            include *
            autoLayout
        }

        container sparkOperator "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438DD5
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "External Optional" {
                background #bbbbbb
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Managed Workload" {
                background #f5a623
                color #ffffff
            }
            element "Person" {
                background #08427b
                color #ffffff
                shape Person
            }
            element "Operator" {
                background #4a90e2
                color #ffffff
            }
            element "Webhook" {
                background #4a90e2
                color #ffffff
            }
            element "Runtime" {
                background #e8744c
                color #ffffff
            }
        }
    }
}
