/*
 * C4 Context Diagram - Kubeflow Trainer
 * Generated by: Claude Opus 4.6
 * Source: architecture/rhoai-3.4-ea.2/trainer.md
 */

workspace {
    model {
        user = person "Data Scientist / ML Engineer" "Submits distributed training jobs via kubectl or RHOAI Dashboard"

        trainer = softwareSystem "Kubeflow Trainer" "Kubernetes operator managing distributed ML training jobs via TrainJob/TrainingRuntime CRD abstraction" {
            controllerManager = container "trainer-controller-manager" "Main controller binary managing TrainJob, TrainingRuntime, and ClusterTrainingRuntime CRDs" "Go Operator (controller-runtime)"
            webhooks = container "Validating Webhooks" "Validates TrainJob, TrainingRuntime, and ClusterTrainingRuntime CRs on CREATE/UPDATE" "Admission Webhooks (9443/TCP)"
            progressionTracking = container "Progression Tracking" "Polls training pod HTTP metrics endpoints to track training progress (RHOAI-specific)" "HTTP Poller"
            networkPolicyManager = container "NetworkPolicy Manager" "Creates per-TrainJob NetworkPolicy for pod isolation (RHOAI-specific)" "Controller Component"
            clusterRuntimes = container "ClusterTrainingRuntimes" "15 pre-configured runtimes for PyTorch distributed training (CUDA, ROCm, CPU)" "CRD Resources"
        }

        k8sAPI = softwareSystem "Kubernetes API Server" "Cluster API for resource management and CRD reconciliation" "External"
        jobsetController = softwareSystem "JobSet Controller" "Manages JobSet CRs and underlying Kubernetes Jobs" "Internal Dependency"
        prometheus = softwareSystem "Prometheus" "Metrics collection and monitoring" "External"
        schedulerPlugins = softwareSystem "Scheduler-Plugins (coscheduling)" "Gang-scheduling via PodGroup CRs" "External Optional"
        volcano = softwareSystem "Volcano" "Alternative gang-scheduling via PodGroup CRs" "External Optional"
        certController = softwareSystem "cert-controller (OPA)" "Webhook certificate generation and rotation" "External"
        rhoaiDashboard = softwareSystem "RHOAI Dashboard" "Web UI for managing ML workloads" "Internal ODH"
        rhods = softwareSystem "rhods-operator" "Deploys trainer component via kustomize overlay" "Internal ODH"

        # Relationships
        user -> trainer "Submits TrainJob CRs" "kubectl / Dashboard"
        trainer -> k8sAPI "CRD reconciliation, resource CRUD" "HTTPS/443, TLS 1.2+, SA Token"
        trainer -> jobsetController "Creates JobSet CRs" "CRD ownership"
        trainer -> prometheus "Exposes controller metrics" "HTTPS/8443, TLS (self-signed)"
        trainer -> schedulerPlugins "Creates PodGroup CRs (optional)" "CRD creation"
        trainer -> volcano "Creates PodGroup CRs (optional)" "CRD creation"
        certController -> trainer "Provisions webhook TLS certs" "Self-managed rotation"
        rhods -> trainer "Deploys via kustomize overlay" "Kustomize"
        rhoaiDashboard -> trainer "Training Hub workbench images" "ImageStreams"

        # Internal container relationships
        controllerManager -> webhooks "Routes admission requests"
        controllerManager -> progressionTracking "Polls training pods"
        controllerManager -> networkPolicyManager "Creates NetworkPolicies"
        progressionTracking -> k8sAPI "Patches TrainJob annotations" "HTTPS/443"
    }

    views {
        systemContext trainer "SystemContext" {
            include *
            autoLayout
        }

        container trainer "Containers" {
            include *
            autoLayout
        }

        styles {
            element "External" {
                background #999999
                color #ffffff
            }
            element "External Optional" {
                background #cccccc
                color #333333
                border dashed
            }
            element "Internal ODH" {
                background #7ed321
                color #ffffff
            }
            element "Internal Dependency" {
                background #4a90e2
                color #ffffff
            }
            element "Person" {
                shape person
                background #08427b
                color #ffffff
            }
            element "Software System" {
                background #1168bd
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
