/*
 * Training Operator - C4 Context Diagram (Structurizr DSL)
 * Generated by: Claude Opus 4.6
 */

workspace {
    model {
        user = person "Data Scientist / ML Engineer" "Creates and manages distributed training jobs on Kubernetes"

        trainingOperator = softwareSystem "Training Operator" "Kubernetes-native operator for managing distributed ML training jobs across PyTorch, TensorFlow, XGBoost, MPI, PaddlePaddle, and JAX" {
            controller = container "Training Operator Controller" "Reconciles training job CRDs, manages Pod/Service/NetworkPolicy lifecycle" "Go Operator (controller-runtime)" {
                pytorchCtrl = component "PyTorchJob Controller" "Manages PyTorch distributed training jobs" "Go Controller"
                tfCtrl = component "TFJob Controller" "Manages TensorFlow distributed training jobs" "Go Controller"
                xgboostCtrl = component "XGBoostJob Controller" "Manages XGBoost distributed training jobs" "Go Controller"
                mpiCtrl = component "MPIJob Controller" "Manages MPI-based distributed training jobs" "Go Controller"
                paddleCtrl = component "PaddleJob Controller" "Manages PaddlePaddle distributed training jobs" "Go Controller"
                jaxCtrl = component "JAXJob Controller" "Manages JAX distributed training jobs" "Go Controller"
            }
            webhook = container "Validating Webhook Server" "Validates CREATE/UPDATE operations on training job CRDs" "Go HTTPS Server (port 9443)"
            certRotator = container "Cert Rotator" "Auto-generates and rotates TLS certificates for webhook server" "cert-controller v0.12.0"
        }

        k8sAPI = softwareSystem "Kubernetes API Server" "Core platform for CRD management, Pod/Service lifecycle" "External"
        prometheus = softwareSystem "Prometheus (OpenShift Monitoring)" "Metrics collection and monitoring" "Internal RHOAI"
        rhoaiOperator = softwareSystem "RHOAI Operator (rhods-operator)" "Deploys and manages the training-operator" "Internal RHOAI"
        volcano = softwareSystem "Volcano Scheduler" "Gang scheduling via PodGroups (optional)" "External Optional"
        schedulerPlugins = softwareSystem "Scheduler-Plugins" "Gang scheduling via PodGroups (optional)" "External Optional"

        // Relationships
        user -> trainingOperator "Creates training job CRs (PyTorchJob, TFJob, etc.) via kubectl"
        rhoaiOperator -> trainingOperator "Deploys and manages via kustomize manifests"

        trainingOperator -> k8sAPI "CRD reconciliation, Pod/Service/NetworkPolicy management" "HTTPS/443 TLS 1.2+ SA Token"
        k8sAPI -> trainingOperator "Admission webhook calls" "HTTPS/9443 TLS auto-rotated"
        prometheus -> trainingOperator "Scrapes operator metrics" "HTTP/8080 plaintext PodMonitor"

        trainingOperator -> volcano "Creates PodGroup CRDs for gang scheduling" "CRD API"
        trainingOperator -> schedulerPlugins "Creates PodGroup CRDs for gang scheduling" "CRD API"

        // Internal relationships
        controller -> webhook "Validates incoming CRs"
        certRotator -> webhook "Provides TLS certificates"
    }

    views {
        systemContext trainingOperator "SystemContext" {
            include *
            autoLayout
            description "System context for Training Operator showing external interactions"
        }

        container trainingOperator "Containers" {
            include *
            autoLayout
            description "Container view showing internal structure of Training Operator"
        }

        component controller "Components" {
            include *
            autoLayout
            description "Component view showing individual framework controllers"
        }

        styles {
            element "Software System" {
                background #4a90e2
                color #ffffff
                shape RoundedBox
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "External Optional" {
                background #cccccc
                color #333333
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Person" {
                background #08427b
                color #ffffff
                shape Person
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
            element "Component" {
                background #85bbf0
                color #000000
            }
        }
    }
}
