// C4 Context Diagram: vllm-orchestrator-gateway
// Generated by: Claude Opus 4.6

workspace {
    model {
        datascientist = person "Data Scientist" "Uses notebooks and applications for LLM inference"
        developer = person "Application Developer" "Builds applications consuming OpenAI-compatible API"

        vllmOrchGateway = softwareSystem "vllm-orchestrator-gateway" "Rust HTTP gateway providing OpenAI-compatible chat completion endpoints with configurable guardrail detector-based filtering" {
            gateway = container "Gateway Service" "Routes chat completion requests through detector pipelines, supports streaming (SSE) and non-streaming modes" "Rust / axum 0.7.9"
            configParser = container "Config Parser" "Parses YAML config defining detectors, routes, and orchestrator connection" "Rust / serde_yml"
        }

        orchestrator = softwareSystem "FMS Guardrails Orchestrator" "Performs content detection and proxies LLM inference requests" "Internal ODH"
        vllm = softwareSystem "vLLM" "Large language model serving engine" "External"
        detectors = softwareSystem "Guardrails Detectors" "Content detection services (PII, safety, regex)" "Internal ODH"
        trustyai = softwareSystem "TrustyAI Ecosystem" "AI safety and trustworthiness platform" "Internal ODH"
        certManager = softwareSystem "cert-manager" "TLS certificate provisioning" "External"
        serviceCaOperator = softwareSystem "service-ca-operator" "OpenShift service CA certificate provisioning" "External"

        // Relationships
        datascientist -> vllmOrchGateway "Sends chat completion requests" "HTTP/8090"
        developer -> vllmOrchGateway "Sends chat completion requests" "HTTP/8090"

        vllmOrchGateway -> orchestrator "Proxies requests with detector config" "HTTP/HTTPS 8085, Optional mTLS"
        orchestrator -> vllm "Inference requests" "HTTP/HTTPS"
        orchestrator -> detectors "Content detection requests" "HTTP/HTTPS"

        vllmOrchGateway -> trustyai "Part of guardrails stack" "" "Indirect"
        certManager -> vllmOrchGateway "Provisions TLS certificates" "kubernetes.io/tls"
        serviceCaOperator -> vllmOrchGateway "Provisions CA certificates" "ConfigMap"

        // Container relationships
        gateway -> configParser "Reads configuration" ""
        gateway -> orchestrator "POST /api/v2/chat/completions-detection" "HTTP/HTTPS 8085"
    }

    views {
        systemContext vllmOrchGateway "SystemContext" {
            include *
            autoLayout
        }

        container vllmOrchGateway "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438DD5
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal ODH" {
                background #7ed321
                color #ffffff
            }
            element "Person" {
                background #08427B
                color #ffffff
                shape person
            }
            element "Container" {
                background #438DD5
                color #ffffff
            }
        }
    }
}
