// KubeRay Operator - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6

workspace {
    model {
        user = person "Data Scientist" "Creates and manages Ray clusters, jobs, and services on OpenShift"

        kuberay = softwareSystem "KubeRay Operator" "Manages lifecycle of Ray clusters, jobs, and services on Kubernetes/OpenShift" {
            rcController = container "RayCluster Controller" "Reconciles RayCluster CRs; creates head/worker pods, services" "Go (controller-runtime)"
            rjController = container "RayJob Controller" "Manages Ray jobs; creates RayClusters and submitter batch Jobs" "Go (controller-runtime)"
            rsController = container "RayService Controller" "Manages Ray Serve deployments; handles blue-green upgrades" "Go (controller-runtime)"
            authController = container "Authentication Controller" "Injects kube-rbac-proxy sidecars, creates HTTPRoutes and ReferenceGrants" "Go (controller-runtime)"
            npController = container "NetworkPolicy Controller" "Creates per-RayCluster NetworkPolicies for workload isolation" "Go (controller-runtime)"
            mtlsController = container "mTLS Controller" "Manages cert-manager Issuers and Certificates for inter-node encryption" "Go (controller-runtime)"
            mutatingWebhook = container "Mutating Webhook" "Enforces secure defaults: enableSecureTrustedNetwork=true, disables enableIngress" "Go Admission Webhook" "9443/TCP HTTPS"
            validatingWebhook = container "Validating Webhook" "Validates RayCluster spec (name format, resource constraints)" "Go Admission Webhook" "9443/TCP HTTPS"
        }

        k8sApi = softwareSystem "Kubernetes API Server" "Cluster control plane" "External"
        certManager = softwareSystem "cert-manager" "Certificate management for mTLS between Ray nodes" "External"
        dsGateway = softwareSystem "data-science-gateway" "OpenShift Gateway API ingress for Ray dashboards" "Internal RHOAI"
        rhodsOperator = softwareSystem "rhods-operator" "RHOAI operator that deploys KubeRay via kustomize" "Internal RHOAI"
        prometheus = softwareSystem "Prometheus" "Metrics collection and monitoring" "External"
        volcano = softwareSystem "Volcano Scheduler" "Optional gang scheduling for Ray clusters" "External"

        // User interactions
        user -> kuberay "Creates RayCluster/RayJob/RayService CRs via kubectl"
        user -> dsGateway "Accesses Ray dashboard via browser" "HTTPS/443"

        // KubeRay dependencies
        kuberay -> k8sApi "Manages pods, services, jobs, CRDs" "HTTPS/6443"
        kuberay -> certManager "Creates Issuer and Certificate CRs for mTLS" "HTTPS/6443"
        kuberay -> dsGateway "Creates HTTPRoutes referencing this Gateway" "Gateway API"
        kuberay -> volcano "Creates PodGroup CRs for gang scheduling" "HTTPS/6443"

        // Reverse dependencies
        rhodsOperator -> kuberay "Deploys via kustomize overlay" "Kustomize"
        prometheus -> kuberay "Scrapes operator metrics" "HTTP/8080"

        // Gateway to Ray head flow
        dsGateway -> kuberay "Routes traffic to Ray head via HTTPRoute" "HTTPS → HTTP/8265"

        // Internal container relationships
        rcController -> k8sApi "Creates head/worker pods, services"
        rjController -> k8sApi "Creates RayClusters, submitter Jobs"
        rsController -> k8sApi "Manages RayCluster upgrades"
        authController -> k8sApi "Creates HTTPRoutes, ReferenceGrants, injects sidecars"
        npController -> k8sApi "Creates NetworkPolicies"
        mtlsController -> certManager "Creates Issuers, Certificates"
    }

    views {
        systemContext kuberay "SystemContext" {
            include *
            autoLayout
        }

        container kuberay "Containers" {
            include *
            autoLayout
        }

        styles {
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #000000
            }
            element "Person" {
                background #4a90e2
                color #ffffff
                shape Person
            }
            element "Software System" {
                background #438dd5
                color #ffffff
            }
            element "Container" {
                background #85bbf0
                color #000000
            }
        }
    }
}
