/* C4 Context Diagram: llm-d-inference-scheduler */
/* Generated by: Claude Opus 4.6 */

workspace {
    model {
        client = person "Client Application" "Sends LLM inference requests (chat completions, completions)"

        llmdScheduler = softwareSystem "llm-d Inference Scheduler" "Endpoint Picker (EPP) and P/D routing sidecar for optimized LLM inference request routing via Gateway API" {
            epp = container "EPP (Endpoint Picker)" "Receives ext-proc gRPC calls from Envoy, runs pluggable filter/score pipeline, returns optimal pod endpoint" "Go Service" "ext-proc"
            sidecar = container "P/D Routing Sidecar" "Reverse proxy on decode pods orchestrating disaggregated prefill/decode inference" "Go Sidecar"
            filterPlugins = container "Filter Plugins" "by-label, by-label-selector, decode-filter, prefill-filter" "Go Plugin Framework"
            scorerPlugins = container "Scorer Plugins" "prefix-cache, precise-prefix-cache, load-aware, active-request, session-affinity, no-hit-lru" "Go Plugin Framework"
            profileHandlers = container "Profile Handlers" "single-profile, pd-profile, dp-profile" "Go Plugin Framework"
            ssrfValidator = container "SSRF Allowlist Validator" "Watches InferencePool and Pods, validates prefill targets" "Go Controller"
        }

        envoyGateway = softwareSystem "Envoy Gateway" "Gateway API implementation with ext-proc filter support" "External"
        k8sAPI = softwareSystem "Kubernetes API Server" "Manages cluster state, CRDs, RBAC" "External"
        vllmServers = softwareSystem "vLLM Model Servers" "LLM inference serving with OpenAI-compatible API" "Internal RHOAI"
        prometheus = softwareSystem "Prometheus" "Metrics collection and monitoring" "External"
        huggingface = softwareSystem "HuggingFace Hub" "Tokenizer model downloads" "External"
        zmqEvents = softwareSystem "vLLM KV Cache Events" "Real-time KV cache state via ZeroMQ" "External"

        /* External interactions */
        client -> envoyGateway "Sends inference requests" "HTTP/80"
        envoyGateway -> epp "ext-proc routing request" "gRPC/9002 plaintext"
        epp -> envoyGateway "Returns selected pod endpoint" "gRPC/9002"
        envoyGateway -> sidecar "Forwards to decode pod" "HTTPS/8000 TLS 1.2+"

        /* Internal EPP flows */
        epp -> filterPlugins "Applies filters to candidate pods"
        epp -> scorerPlugins "Scores filtered candidates"
        epp -> profileHandlers "Selects scheduling profile"
        epp -> k8sAPI "Watches InferencePool, Pods" "HTTPS/443 Bearer Token"
        epp -> zmqEvents "Subscribes to KV cache events" "ZMQ/5557 plaintext"

        /* Sidecar flows */
        sidecar -> vllmServers "Proxies to local vLLM decoder" "HTTP(S)/8001"
        sidecar -> vllmServers "Sends prefill to remote workers" "HTTP(S)/varies SSRF validated"
        sidecar -> ssrfValidator "Validates prefill targets"
        ssrfValidator -> k8sAPI "Watches InferencePool, Pods" "HTTPS/443 Bearer Token"

        /* Monitoring */
        prometheus -> epp "Scrapes metrics" "HTTP/9090"

        /* Optional */
        epp -> huggingface "Downloads tokenizers" "HTTPS/443 HF_TOKEN"
    }

    views {
        systemContext llmdScheduler "SystemContext" {
            include *
            autoLayout
        }

        container llmdScheduler "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438dd5
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Person" {
                background #08427b
                color #ffffff
                shape person
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
