// MLflow Operator - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6

workspace {
    model {
        admin = person "Platform Admin" "Creates and manages MLflow CR instances"
        dataScientist = person "Data Scientist" "Uses MLflow tracking server for experiment tracking and model registry"

        mlflowOperator = softwareSystem "MLflow Operator" "Manages lifecycle of MLflow tracking server instances on OpenShift/Kubernetes" {
            controller = container "MLflow Operator Controller" "Watches MLflow CRs, renders Helm charts, reconciles resources via Server-Side Apply" "Go (controller-runtime)"
            helmRenderer = container "Helm Renderer" "Converts MLflow CR spec to Helm values and renders embedded charts/mlflow chart" "Go (Helm v3 library)"
            routingController = container "Routing Controller Logic" "Dynamically creates HTTPRoute and ConsoleLink resources based on cluster capabilities" "Go"
            metricsServer = container "Metrics Server" "Exposes Prometheus metrics on 8443/TCP with TLS and token auth" "controller-runtime"
        }

        mlflowServer = softwareSystem "MLflow Tracking Server" "MLflow tracking server instance (managed workload) with TLS, kubernetes-auth, and workspace support" "Managed by Operator"

        rhodsOperator = softwareSystem "rhods-operator" "Deploys mlflow-operator via kustomize overlay" "Internal RHOAI"
        dataScienceGateway = softwareSystem "data-science-gateway" "Gateway API Gateway providing external ingress via HTTPRoute" "Internal RHOAI"
        openshiftConsole = softwareSystem "OpenShift Console" "OpenShift web console with application menu" "OpenShift Platform"
        openshiftServiceCA = softwareSystem "OpenShift service-ca" "Auto-provisions TLS certificates for Kubernetes services" "OpenShift Platform"
        prometheus = softwareSystem "Prometheus" "Monitoring and metrics collection" "OpenShift Platform"
        kubernetesAPI = softwareSystem "Kubernetes API Server" "Cluster API server for resource management and RBAC" "Kubernetes"

        backendStore = softwareSystem "Backend Store" "PostgreSQL or MySQL database for MLflow metadata" "External"
        artifactStorage = softwareSystem "Artifact Storage" "S3, GCS, or Azure Blob for MLflow artifacts" "External"

        // Relationships
        admin -> mlflowOperator "Creates MLflow CR" "kubectl / YAML"
        dataScientist -> dataScienceGateway "Accesses MLflow UI/API" "HTTPS/443"
        dataScienceGateway -> mlflowServer "Routes requests via HTTPRoute" "HTTPS/8443"

        rhodsOperator -> mlflowOperator "Deploys via kustomize" "Kustomize overlay"
        mlflowOperator -> kubernetesAPI "Watches CRs, applies resources" "HTTPS/443, SA Token"
        mlflowOperator -> mlflowServer "Creates and manages" "Server-Side Apply"

        controller -> helmRenderer "Renders chart" "In-memory"
        controller -> routingController "Creates routes" "In-process"

        mlflowServer -> kubernetesAPI "SubjectAccessReview auth" "HTTPS/443"
        mlflowServer -> backendStore "Stores metadata" "TCP, URI credentials"
        mlflowServer -> artifactStorage "Stores artifacts" "HTTPS/443, Cloud credentials"

        openshiftServiceCA -> mlflowServer "Provisions TLS certs" "service-ca annotation"
        openshiftServiceCA -> mlflowOperator "Provisions metrics TLS cert" "service-ca annotation"
        prometheus -> mlflowOperator "Scrapes metrics" "HTTPS/8443, Bearer Token"

        mlflowOperator -> dataScienceGateway "Creates HTTPRoute referencing gateway" "Gateway API"
        mlflowOperator -> openshiftConsole "Creates ConsoleLink" "OpenShift API"
    }

    views {
        systemContext mlflowOperator "SystemContext" {
            include *
            autoLayout
        }

        container mlflowOperator "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438DD5
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "OpenShift Platform" {
                background #e06666
                color #ffffff
            }
            element "Managed by Operator" {
                background #6aa84f
                color #ffffff
            }
            element "Person" {
                background #08427B
                color #ffffff
                shape Person
            }
            element "Container" {
                background #438DD5
                color #ffffff
            }
        }
    }
}
