// Model Registry Operator - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6
// Source: architecture/rhoai-3.3/model-registry-operator.md

workspace {
    model {
        datascientist = person "Data Scientist" "Creates and manages ML model registries and browses model catalog"
        admin = person "Platform Admin" "Configures model registry instances and catalog sources"

        modelRegistryOperator = softwareSystem "Model Registry Operator" "Kubernetes operator managing Model Registry instances and Model Catalog service" {
            mrReconciler = container "ModelRegistryReconciler" "Watches ModelRegistry CRs; creates Deployments, Services, RBAC, Routes, NetworkPolicies per instance" "Go Controller"
            mcReconciler = container "ModelCatalogReconciler" "Manages singleton model-catalog Deployment, Service, PostgreSQL, RBAC, Routes" "Go Controller"
            migrationMgr = container "StorageMigrationManager" "CRD storage version migration (v1alpha1 -> v1beta1)" "Go Component"
            webhooks = container "Admission Webhooks" "Mutating, validating, and conversion webhooks for ModelRegistry CRs" "Go Webhook Handlers"
            kubeRbacProxy = container "kube-rbac-proxy" "Authentication/authorization proxy sidecar (port 8443/TCP)" "Sidecar Container"
            restContainer = container "model-registry (rest-container)" "REST API for ML model metadata CRUD operations" "Application Container"
            catalogContainer = container "model-catalog" "REST API for centralized model catalog discovery" "Application Container"
        }

        // External Dependencies
        k8sApi = softwareSystem "Kubernetes API Server" "Cluster control plane for resource management" "External"
        openshiftRouter = softwareSystem "OpenShift Router" "Ingress controller providing external Routes" "External"
        openshiftOAuth = softwareSystem "OpenShift OAuth/User API" "User and Group management for access control" "External"
        openshiftServingCert = softwareSystem "OpenShift Serving Cert Controller" "Auto-provisions TLS certificates for Services" "External"
        storageVersionMigration = softwareSystem "StorageVersionMigration API" "Kubernetes CRD storage version migration" "External"

        // Internal ODH Dependencies
        rhodsOperator = softwareSystem "rhods-operator" "Deploys this operator via kustomize overlays" "Internal RHOAI"
        platformModelRegistryCR = softwareSystem "Platform ModelRegistry Component CR" "components.platform.opendatahub.io" "Internal RHOAI"
        authCR = softwareSystem "Platform Auth CR" "services.platform.opendatahub.io/Auth - admin groups config" "Internal RHOAI"
        modelMetadataCollection = softwareSystem "odh-model-metadata-collection" "Provides catalog data and benchmark data" "Internal RHOAI"

        // Databases
        postgresql = softwareSystem "PostgreSQL" "Backend database for model registry and catalog data" "Database"
        mysql = softwareSystem "MySQL" "Alternative backend database for model registry" "Database"

        // Relationships - User interactions
        datascientist -> modelRegistryOperator "Creates ModelRegistry CRs, queries model registry and catalog APIs" "HTTPS/443"
        admin -> modelRegistryOperator "Configures ModelRegistry CRs, manages catalog sources" "kubectl/HTTPS"

        // Relationships - Internal
        rhodsOperator -> modelRegistryOperator "Deploys via kustomize overlays/odh" "Kustomize"
        modelRegistryOperator -> k8sApi "CRUD operations on cluster resources" "HTTPS/443"
        modelRegistryOperator -> openshiftOAuth "Creates Groups for registry access control" "HTTPS/443"
        modelRegistryOperator -> openshiftServingCert "Requests TLS certificates via annotations" "Annotation-based"
        modelRegistryOperator -> storageVersionMigration "Performs CRD version migration" "HTTPS/443"
        modelRegistryOperator -> platformModelRegistryCR "Reads platform component CR as owner reference" "HTTPS/443"
        modelRegistryOperator -> authCR "Reads adminGroups for catalog admin RBAC" "HTTPS/443"
        modelRegistryOperator -> postgresql "Stores model metadata and catalog data" "TCP/5432"
        modelRegistryOperator -> mysql "Stores model metadata (alternative backend)" "TCP/3306"
        openshiftRouter -> modelRegistryOperator "Routes external traffic to registry and catalog" "HTTPS reencrypt/8443"
        k8sApi -> modelRegistryOperator "Webhook calls for CR validation/mutation" "HTTPS/9443"

        // Container-level relationships
        mrReconciler -> k8sApi "Creates/updates Deployments, Services, RBAC, Routes, NetworkPolicies" "HTTPS/443"
        mcReconciler -> k8sApi "Creates/updates catalog resources" "HTTPS/443"
        mcReconciler -> platformModelRegistryCR "Reads component CR" "HTTPS/443"
        mcReconciler -> authCR "Reads admin groups" "HTTPS/443"
        migrationMgr -> storageVersionMigration "Monitors/performs CRD migration" "HTTPS/443"
        kubeRbacProxy -> k8sApi "SubjectAccessReview for authorization" "HTTPS/443"
        kubeRbacProxy -> restContainer "Proxies authorized requests" "HTTP/8080 localhost"
        kubeRbacProxy -> catalogContainer "Proxies authorized requests" "HTTP/8080 localhost"
        restContainer -> postgresql "Model metadata queries" "TCP/5432"
        catalogContainer -> postgresql "Catalog data queries" "TCP/5432"
    }

    views {
        systemContext modelRegistryOperator "SystemContext" {
            include *
            autoLayout
        }

        container modelRegistryOperator "Containers" {
            include *
            autoLayout
        }

        styles {
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Database" {
                background #9b59b6
                color #ffffff
                shape Cylinder
            }
            element "Software System" {
                background #4a90e2
                color #ffffff
            }
            element "Person" {
                background #08427b
                color #ffffff
                shape Person
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
