// ODH Dashboard - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6

workspace {
    model {
        // People
        dataScientist = person "Data Scientist" "Creates and manages workbenches, models, and pipelines"
        platformAdmin = person "Platform Admin" "Configures dashboard features, manages platform settings"

        // Main System
        odhDashboard = softwareSystem "ODH Dashboard" "Primary web UI for Red Hat OpenShift AI platform management" {
            kubeRbacProxy = container "kube-rbac-proxy" "Authentication sidecar enforcing RBAC via SubjectAccessReview" "Go Sidecar" "Auth"
            dashboardBackend = container "odh-dashboard Backend" "BFF serving React SPA and proxying K8s API calls" "Node.js/Fastify"
            modelRegistryUI = container "model-registry-ui" "Model Registry federated UI micro-frontend" "React/PatternFly" "Federated"
            genAIUI = container "gen-ai-ui" "Gen AI Studio federated UI micro-frontend" "React/PatternFly" "Federated"
            maasUI = container "maas-ui" "Model-as-a-Service federated UI micro-frontend" "React/PatternFly" "Federated"
        }

        // Internal ODH Components
        notebookController = softwareSystem "Notebook Controller" "Manages notebook/workbench lifecycle" "Internal ODH"
        kserve = softwareSystem "KServe" "Model serving with InferenceService management" "Internal ODH"
        modelRegistryOp = softwareSystem "Model Registry Operator" "Model registry instance management" "Internal ODH"
        dscOperator = softwareSystem "DataScienceCluster Operator" "Platform component status" "Internal ODH"
        rhodsOperator = softwareSystem "RHODS Operator" "Deploys and manages the dashboard" "Internal ODH"
        nimOperator = softwareSystem "NIM Operator" "NVIDIA NIM account management" "Internal ODH"
        llamaStack = softwareSystem "LlamaStack" "LlamaStack distribution management" "Internal ODH"
        feast = softwareSystem "Feast" "Feature store management" "Internal ODH"

        // Platform Components
        k8sAPI = softwareSystem "Kubernetes API Server" "Cluster API for all resource operations" "Platform"
        gatewayAPI = softwareSystem "Gateway API (data-science-gateway)" "Platform ingress gateway for external traffic" "Platform"
        thanosQuerier = softwareSystem "Thanos Querier" "Prometheus metrics aggregation and query" "Platform"
        openshiftConsole = softwareSystem "OpenShift Console" "OpenShift web console with application menu" "Platform"

        // Relationships - People
        dataScientist -> odhDashboard "Manages workbenches, models, pipelines via" "HTTPS/443"
        platformAdmin -> odhDashboard "Configures platform features via" "HTTPS/443"

        // Relationships - Internal containers
        kubeRbacProxy -> dashboardBackend "Forwards authenticated requests" "HTTP/8080 localhost"
        kubeRbacProxy -> k8sAPI "Validates user via SubjectAccessReview" "HTTPS/443"
        dashboardBackend -> modelRegistryUI "Proxies federated module requests" "HTTPS/8043"
        dashboardBackend -> genAIUI "Proxies federated module requests" "HTTPS/8143"
        dashboardBackend -> maasUI "Proxies federated module requests" "HTTPS/8243"

        // Relationships - External
        gatewayAPI -> kubeRbacProxy "Routes external traffic to dashboard" "HTTPS/8443"
        dashboardBackend -> k8sAPI "All K8s resource CRUD on behalf of users" "HTTPS/443"
        dashboardBackend -> thanosQuerier "Queries PVC usage, model serving, bias metrics" "HTTPS/9092"

        // Relationships - Internal ODH (CRD-based)
        odhDashboard -> notebookController "Manages Notebook CRs" "CRD: kubeflow.org/Notebook"
        odhDashboard -> kserve "Reads InferenceService, manages ServingRuntime" "CRD: serving.kserve.io"
        odhDashboard -> modelRegistryOp "Manages ModelRegistry instances" "CRD: modelregistry.opendatahub.io"
        odhDashboard -> dscOperator "Reads platform component status" "CRD: datasciencecluster.opendatahub.io"
        odhDashboard -> nimOperator "Manages NIM accounts" "CRD: nim.opendatahub.io"
        odhDashboard -> llamaStack "Reads LlamaStack distribution status" "CRD: llamastack.io"
        odhDashboard -> feast "Reads feature store status" "CRD: feast.dev"
        rhodsOperator -> odhDashboard "Deploys and manages" "Operator lifecycle"
        odhDashboard -> openshiftConsole "Adds ConsoleLink to app menu" "ConsoleLink CR"
    }

    views {
        systemContext odhDashboard "SystemContext" {
            include *
            autoLayout
        }

        container odhDashboard "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438dd5
                color #ffffff
            }
            element "Internal ODH" {
                background #7ed321
                color #ffffff
            }
            element "Platform" {
                background #999999
                color #ffffff
            }
            element "Person" {
                background #08427b
                color #ffffff
                shape Person
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
            element "Auth" {
                background #b85450
                color #ffffff
            }
            element "Federated" {
                background #6c8ebf
                color #ffffff
            }
        }
    }
}
