// vLLM CPU - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6

workspace {
    model {
        user = person "Data Scientist" "Deploys and queries LLM inference endpoints"
        admin = person "Platform Admin" "Configures and monitors RHOAI platform"

        vllmCpu = softwareSystem "vLLM CPU" "CPU-optimized LLM inference serving runtime with OpenAI-compatible API" {
            apiServer = container "OpenAI API Server" "FastAPI/Uvicorn HTTP server serving OpenAI-compatible REST API" "Python FastAPI" "8000/TCP"
            authMiddleware = container "Authentication Middleware" "Bearer token validation for /v1/* endpoints" "Python ASGI Middleware"
            asyncEngine = container "AsyncLLM Engine V1" "Core inference engine managing model loading, scheduling, and token generation" "Python Async"
            modelExecutor = container "Model Executor" "Loads and executes transformer models on CPU using PyTorch" "Python/PyTorch"
            cppExtensions = container "C/C++ Extensions" "CPU-optimized kernels compiled via CMake" "C/C++ Native"
            zmqIPC = container "ZeroMQ IPC" "Inter-process communication for multi-process inference" "PyZMQ"
        }

        // Platform components (Internal RHOAI)
        kserve = softwareSystem "KServe" "Deploys and manages vLLM pods as InferenceService" "Internal RHOAI"
        modelRegistry = softwareSystem "Model Registry" "Manages model metadata and versions" "Internal RHOAI"
        dsPipelines = softwareSystem "Data Science Pipelines" "Workflow orchestration for ML pipelines" "Internal RHOAI"
        dashboard = softwareSystem "RHOAI Dashboard" "Web UI for configuring and monitoring serving runtimes" "Internal RHOAI"
        prometheus = softwareSystem "Prometheus" "Metrics collection and monitoring" "Internal RHOAI"

        // Platform infrastructure
        platformGateway = softwareSystem "Platform Gateway" "Envoy-based ingress with Gateway API and kube-rbac-proxy" "Infrastructure"
        kubeRBACProxy = softwareSystem "kube-rbac-proxy" "RBAC-based authorization sidecar" "Infrastructure"

        // External services
        hfHub = softwareSystem "HuggingFace Hub" "Model weights and tokenizer downloads" "External"
        s3Storage = softwareSystem "S3-compatible Storage" "Model artifact storage in object storage" "External"
        containerRegistry = softwareSystem "Container Registry" "Container image hosting" "External"

        // Relationships - Users
        user -> platformGateway "Sends inference requests via" "HTTPS/443"
        admin -> dashboard "Configures serving runtimes via" "HTTPS"

        // Relationships - Platform Gateway to vLLM
        platformGateway -> kubeRBACProxy "Forwards requests" "HTTPS/8443"
        kubeRBACProxy -> vllmCpu "Proxies authorized requests" "HTTP/8000"

        // Relationships - Internal RHOAI
        kserve -> vllmCpu "Deploys and manages pods" "Kubernetes API"
        dashboard -> kserve "Creates InferenceService CRs" "Kubernetes API"
        dsPipelines -> kserve "Triggers model deployments" "Kubernetes API"
        prometheus -> vllmCpu "Scrapes metrics" "HTTP/8000 /metrics"

        // Relationships - External
        vllmCpu -> hfHub "Downloads model weights" "HTTPS/443 TLS 1.2+"
        vllmCpu -> s3Storage "Loads model artifacts" "HTTPS/443 TLS 1.2+"

        // Internal container relationships
        apiServer -> authMiddleware "Validates tokens"
        authMiddleware -> asyncEngine "Forwards requests"
        asyncEngine -> zmqIPC "IPC communication"
        zmqIPC -> modelExecutor "Dispatches inference"
        modelExecutor -> cppExtensions "CPU-optimized ops"
    }

    views {
        systemContext vllmCpu "SystemContext" {
            include *
            autoLayout
        }

        container vllmCpu "Containers" {
            include *
            autoLayout
        }

        styles {
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Infrastructure" {
                background #d79b00
                color #ffffff
            }
            element "Person" {
                background #4a90e2
                color #ffffff
                shape Person
            }
            element "Software System" {
                background #4a90e2
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
