/*
 * C4 Context Diagram: vllm-orchestrator-gateway
 * Generated by: Claude Opus 4.6
 * Source: architecture/rhoai-3.3/vllm-orchestrator-gateway.md
 */

workspace {
    model {
        client = person "Client Application" "Sends OpenAI-compatible chat completion requests"
        operator = person "Platform Operator" "Configures gateway routes, detectors, and TLS settings via YAML"

        gateway = softwareSystem "vllm-orchestrator-gateway" "HTTP gateway providing per-route OpenAI-compatible chat completion endpoints with configurable detector-based content filtering" {
            httpServer = container "HTTP Server" "Axum-based HTTP server with dynamic route generation from YAML config" "Rust (axum 0.7.9)"
            configLoader = container "Config Loader" "Reads and validates YAML configuration defining orchestrator connection, detectors, and routes" "Rust (serde_yml)"
            tlsClient = container "TLS Client Builder" "Constructs HTTP/HTTPS client with optional mTLS identity and custom CA" "Rust (reqwest, openssl)"
            streamHandler = container "Streaming Handler" "Processes SSE streaming chat completions with detection-based fallback" "Rust (futures, tokio)"
            nonStreamHandler = container "Non-Streaming Handler" "Processes standard JSON chat completions with detection-based fallback" "Rust (serde_json)"
        }

        orchestrator = softwareSystem "FMS Guardrails Orchestrator" "Performs content detection and LLM inference orchestration" "Internal RHOAI"
        detectors = softwareSystem "Guardrails Detectors" "Content detection services (e.g., regex-language for PII)" "Internal RHOAI"
        vllm = softwareSystem "vLLM Inference Server" "LLM inference backend (e.g., Qwen/Qwen2.5-1.5B-Instruct)" "Internal RHOAI"
        openshift = softwareSystem "OpenShift Platform" "Provides service-serving certificates and CA for mTLS" "External"

        /* Relationships */
        client -> gateway "POST /{route}/v1/chat/completions" "HTTP/8090, plaintext"
        operator -> gateway "Configures routes and detectors" "YAML config file"

        gateway -> orchestrator "POST /api/v2/chat/completions-detection" "HTTP or HTTPS/8085, optional mTLS"
        orchestrator -> detectors "Invokes content detectors" "Internal"
        orchestrator -> vllm "Sends inference requests" "Internal"
        openshift -> gateway "Provisions TLS certificates" "service-serving-cert-signer, service-ca"

        /* Container relationships */
        httpServer -> configLoader "Loads route and detector config at startup"
        httpServer -> tlsClient "Uses configured HTTP/HTTPS client"
        httpServer -> streamHandler "Routes streaming requests"
        httpServer -> nonStreamHandler "Routes non-streaming requests"
        streamHandler -> orchestrator "Forwards with injected detectors" "HTTP or HTTPS/8085"
        nonStreamHandler -> orchestrator "Forwards with injected detectors" "HTTP or HTTPS/8085"
    }

    views {
        systemContext gateway "SystemContext" {
            include *
            autoLayout
        }

        container gateway "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #4a90e2
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Person" {
                background #08427b
                color #ffffff
                shape person
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
