// Feast Operator - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6
// Source: architecture/rhoai-3.4-ea.1/feast.md

workspace {
    model {
        user = person "Data Scientist" "Creates and manages Feast feature stores for ML workflows"
        mlApp = person "ML Application" "Consumes features from the online/offline store"

        feastOperator = softwareSystem "Feast Operator" "Kubernetes operator managing Feast feature store deployments (online/offline store, registry, UI, materialization)" {
            fsReconciler = container "FeatureStoreReconciler" "Reconciles FeatureStore CRs; creates Deployments, Services, ConfigMaps, PVCs, RBAC, CronJobs, Routes" "Go Controller (controller-runtime)"
            nbReconciler = container "NotebookConfigMapReconciler" "Watches Kubeflow Notebook CRs with feast integration labels; creates per-notebook feast config ConfigMaps" "Go Controller"
            feastServices = container "FeastServices" "Manages deployment of online, offline, registry, and UI feast services within a single Deployment" "Go Service Layer"
            feastAuth = container "FeastAuthorization" "Deploys Kubernetes RBAC or OIDC authorization resources for feast services" "Go Auth Module"
            namespaceRegistry = container "Namespace Registry" "Manages central ConfigMap tracking all FeatureStore deployments across namespaces" "Go Discovery"
            cronJobMgr = container "CronJob Manager" "Creates CronJobs for feast apply and materialize-incremental" "Go Batch Processing"
        }

        feastDeployment = softwareSystem "Feast Deployment" "Dynamically created Feast feature store services (online, offline, registry, UI)" {
            onlineStore = container "Online Store" "Feature serving via feast serve" "Python (feature-server)" "6566/6567 TCP"
            offlineStore = container "Offline Store" "Offline feature serving via feast serve_offline" "Python (feature-server)" "8815/8816 TCP"
            registryServer = container "Registry Server" "Feature registry (gRPC + REST)" "Python (feature-server)" "6570-6573 TCP"
            uiServer = container "UI Server" "Feast web UI" "Python (feature-server)" "8888/8443 TCP"
        }

        // External dependencies
        k8sAPI = softwareSystem "Kubernetes API Server" "Cluster API for resource management" "External"
        ocpServiceCA = softwareSystem "OpenShift Service CA" "Automatic TLS certificate provisioning" "External"
        ocpRouteController = softwareSystem "OpenShift Route Controller" "External access via Routes" "External"
        prometheus = softwareSystem "Prometheus" "Metrics collection and monitoring" "External"

        // Internal ODH dependencies
        rhodsOperator = softwareSystem "rhods-operator" "Deploys feast-operator via kustomize overlays" "Internal RHOAI"
        kubeflowNotebooks = softwareSystem "Kubeflow Notebooks" "Notebook CRs for feast integration" "Internal RHOAI"
        odhTrustedCA = softwareSystem "odh-trusted-ca-bundle" "Custom CA bundle ConfigMap" "Internal RHOAI"

        // External services (egress)
        gitRepos = softwareSystem "Git Repositories" "Source for feast project initialization" "External Service"
        dbBackends = softwareSystem "Database Backends" "Persistence (PostgreSQL, Redis, Snowflake)" "External Service"
        objectStorage = softwareSystem "S3/GCS Object Storage" "Registry file persistence" "External Service"

        // Relationships - User interactions
        user -> feastOperator "Creates FeatureStore CR via kubectl" "HTTPS/443"
        user -> uiServer "Accesses Feast UI" "HTTPS/443 (via OpenShift Route)"
        mlApp -> onlineStore "Queries features" "HTTP(S)/80 or 443"
        mlApp -> offlineStore "Queries historical features" "HTTP(S)/80 or 443"

        // Operator internal relationships
        fsReconciler -> feastServices "manages"
        fsReconciler -> feastAuth "configures auth"
        fsReconciler -> namespaceRegistry "updates registry"
        fsReconciler -> cronJobMgr "creates cronjobs"

        // Operator to Kubernetes
        feastOperator -> k8sAPI "CRUD operations on Deployments, Services, ConfigMaps, PVCs, RBAC" "HTTPS/443, SA Token"
        feastOperator -> ocpServiceCA "Auto TLS cert provisioning via annotations"
        feastOperator -> ocpRouteController "Creates Routes for UI service"

        // Deployment dependencies
        rhodsOperator -> feastOperator "Deploys via kustomize overlays/rhoai"
        nbReconciler -> kubeflowNotebooks "Watches Notebook CRs for feast integration label"
        feastOperator -> odhTrustedCA "Reads custom CA bundle ConfigMap"

        // Feast deployment egress
        feastDeployment -> gitRepos "Git clone for project init" "HTTPS/443"
        feastDeployment -> dbBackends "Feature persistence" "Various ports, user-configured"
        feastDeployment -> objectStorage "Registry file persistence" "HTTPS/443"

        // Monitoring
        prometheus -> feastOperator "Scrapes operator metrics" "HTTPS/8443, Bearer Token"
    }

    views {
        systemContext feastOperator "SystemContext" {
            include *
            autoLayout
        }

        container feastOperator "OperatorContainers" {
            include *
            autoLayout
        }

        container feastDeployment "FeastDeploymentContainers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438DD5
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "External Service" {
                background #f5a623
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Person" {
                shape Person
                background #08427B
                color #ffffff
            }
            element "Container" {
                background #438DD5
                color #ffffff
            }
        }
    }
}
