/*
 * C4 Context Diagram: Guardrails Regex Detector
 * Generated by: Claude Opus 4.6
 * Source: architecture/rhoai-3.4-ea.1/guardrails-regex-detector.md
 */

workspace {
    model {
        orchestrator = person "FMS Guardrails Orchestrator" "Routes text content to detection backends for content safety filtering"

        regexDetector = softwareSystem "Guardrails Regex Detector" "Lightweight Rust HTTP microservice that detects PII and custom patterns in text using regular expressions" {
            service = container "regex-detector" "Main HTTP service; listens on port 8080, exposes detection and health APIs" "Rust / Axum / Tokio"
            detectors = container "Detectors Module" "Built-in PII detectors (email, SSN, credit card) and custom regex matching logic" "Rust Module"
        }

        kubelet = softwareSystem "Kubernetes Kubelet" "Performs liveness/readiness health checks" "Infrastructure"
        serviceMesh = softwareSystem "Istio Service Mesh" "Provides mTLS encryption between services (optional)" "Infrastructure"

        /* Relationships */
        orchestrator -> regexDetector "Sends text for PII/regex detection" "HTTP POST /api/v1/text/contents, 8080/TCP"
        kubelet -> regexDetector "Health checks" "HTTP GET /health, 8080/TCP"
        serviceMesh -> regexDetector "Provides mTLS sidecar" "Envoy proxy injection"

        /* Internal relationships */
        service -> detectors "Invokes pattern matching" "In-process function call"
    }

    views {
        systemContext regexDetector "SystemContext" {
            include *
            autoLayout
            description "System context for Guardrails Regex Detector showing callers and infrastructure"
        }

        container regexDetector "Containers" {
            include *
            autoLayout
            description "Internal structure of the Guardrails Regex Detector"
        }

        styles {
            element "Software System" {
                background #4a90e2
                color #ffffff
                shape RoundedBox
            }
            element "Infrastructure" {
                background #999999
                color #ffffff
            }
            element "Person" {
                background #f5a623
                color #ffffff
                shape Person
            }
            element "Container" {
                background #4a90e2
                color #ffffff
            }
        }
    }
}
