// KubeRay Operator - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6

workspace {
    model {
        user = person "Data Scientist" "Creates and manages Ray clusters, jobs, and services for distributed computing"

        kuberay = softwareSystem "KubeRay Operator" "Kubernetes operator for managing Ray cluster lifecycles including RayCluster, RayJob, and RayService resources" {
            rayClusterCtrl = container "RayCluster Controller" "Reconciles RayCluster CRs; creates head/worker pods, services, RBAC resources" "Go Controller (controller-runtime)"
            rayJobCtrl = container "RayJob Controller" "Reconciles RayJob CRs; creates clusters, submitter jobs, manages job lifecycle" "Go Controller (controller-runtime)"
            rayServiceCtrl = container "RayService Controller" "Reconciles RayService CRs; manages active/pending clusters for zero-downtime upgrades" "Go Controller (controller-runtime)"
            authCtrl = container "Authentication Controller" "Creates HTTPRoute CRs and kube-rbac-proxy sidecars per RayCluster for dashboard auth (RHOAI-specific)" "Go Controller (controller-runtime)"
            netpolCtrl = container "NetworkPolicy Controller" "Creates NetworkPolicies per RayCluster for head and worker pod isolation (RHOAI-specific)" "Go Controller (controller-runtime)"
            mtlsCtrl = container "mTLS Controller" "Manages cert-manager Issuers and Certificates for intra-cluster mTLS (RHOAI-specific)" "Go Controller (controller-runtime)"
            webhook = container "Admission Webhooks" "Mutating and validating webhooks for RayCluster resources" "Admission Webhook"
        }

        kubernetes = softwareSystem "Kubernetes" "Container orchestration platform" "External"
        openshift = softwareSystem "OpenShift" "Enterprise Kubernetes with Routes, OAuth, Gateway API" "External"
        certManager = softwareSystem "cert-manager" "Certificate lifecycle management for mTLS" "External"
        gatewayAPI = softwareSystem "Gateway API" "HTTPRoute-based ingress (RHOAI 3.x pattern)" "External"
        redis = softwareSystem "Redis" "External storage for GCS fault tolerance" "External"
        kueue = softwareSystem "Kueue" "Multi-cluster job scheduling" "External"
        prometheus = softwareSystem "Prometheus" "Metrics collection and monitoring" "External"

        rhoaiOperator = softwareSystem "ODH/RHOAI Operator" "Deploys and manages KubeRay operator" "Internal RHOAI"
        dsGateway = softwareSystem "Data Science Gateway" "Gateway API parent for HTTPRoute ingress" "Internal RHOAI"

        user -> kuberay "Creates RayCluster, RayJob, RayService CRs via kubectl"
        kuberay -> kubernetes "CRUD operations on Pods, Services, RBAC, NetworkPolicies" "HTTPS/443"
        kuberay -> openshift "Creates Routes (legacy), reads OAuth config" "HTTPS/443"
        kuberay -> certManager "Creates Issuers and Certificates for mTLS" "via Kubernetes API"
        kuberay -> gatewayAPI "Creates HTTPRoutes and ReferenceGrants" "via Kubernetes API"
        kuberay -> redis "GCS fault tolerance storage" "TCP/configurable"
        kuberay -> kueue "Multi-cluster job delegation" "via Kubernetes API"
        prometheus -> kuberay "Scrapes operator and Ray cluster metrics" "HTTP/8080"
        rhoaiOperator -> kuberay "Deploys via kustomize manifests"
        kuberay -> dsGateway "HTTPRoute references parent gateway" "Gateway API"
    }

    views {
        systemContext kuberay "SystemContext" {
            include *
            autoLayout
        }

        container kuberay "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438dd5
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #000000
            }
            element "Person" {
                background #08427b
                color #ffffff
                shape person
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
