// C4 Context Diagram - llama-stack-k8s-operator
// Generated by: Claude Opus 4.6

workspace {
    model {
        user = person "Platform Admin / Data Scientist" "Creates and manages LlamaStackDistribution CRs"

        llamaStackOperator = softwareSystem "llama-stack-k8s-operator" "Kubernetes operator managing Llama Stack distribution server instances on OpenShift" {
            reconciler = container "LlamaStackDistribution Reconciler" "Reconciles LlamaStackDistribution CRs; manages full lifecycle of server resources" "Go Controller (controller-runtime)"
            kustomizeRenderer = container "Kustomize Manifest Renderer" "Renders base manifests through kustomize pipeline with custom Go plugins" "Go Library (sigs.k8s.io/kustomize)"
            caBundleManager = container "CA Bundle Manager" "Manages CA bundle ConfigMaps with auto-detection of ODH trusted CA bundles" "Go Logic"
            clusterInfo = container "ClusterInfo Utility" "Detects operator namespace, resolves distribution images" "Go Utility"
            featureFlags = container "Feature Flags" "Controls feature toggles (EnableNetworkPolicy) via operator ConfigMap" "Go Configuration"

            reconciler -> kustomizeRenderer "Renders manifests"
            reconciler -> caBundleManager "Manages CA bundles"
            reconciler -> clusterInfo "Queries cluster info"
            reconciler -> featureFlags "Reads feature flags"
        }

        llamaStackServer = softwareSystem "Llama Stack Server" "AI inference server instances managed by the operator" "Managed"
        k8sAPI = softwareSystem "Kubernetes API Server" "Kubernetes control plane API" "External"
        rhodsOperator = softwareSystem "rhods-operator" "RHOAI platform operator that deploys components via kustomize" "Internal RHOAI"
        odhTrustedCA = softwareSystem "ODH Trusted CA Bundle" "Platform-level trusted CA certificate ConfigMap" "Internal RHOAI"
        prometheus = softwareSystem "Prometheus" "Metrics collection and monitoring" "External"
        openshiftSCC = softwareSystem "OpenShift SCC" "Security Context Constraints (anyuid)" "External"

        user -> llamaStackOperator "Creates LlamaStackDistribution CR via kubectl" "HTTPS/443"
        llamaStackOperator -> k8sAPI "Manages resources (Deployments, Services, PVCs, NetworkPolicies, etc.)" "HTTPS/443 TLS 1.2+"
        llamaStackOperator -> llamaStackServer "Health checks, provider info, version queries" "HTTP/8321 plaintext"
        rhodsOperator -> llamaStackOperator "Deploys operator via kustomize overlay" "kustomize"
        llamaStackOperator -> odhTrustedCA "Watches and auto-detects CA bundle ConfigMap" "In-cluster"
        prometheus -> llamaStackOperator "Scrapes metrics via kube-rbac-proxy" "HTTPS/8443 TLS"
        llamaStackOperator -> openshiftSCC "Grants anyuid SCC to server pods" "RBAC"
    }

    views {
        systemContext llamaStackOperator "SystemContext" {
            include *
            autoLayout
        }

        container llamaStackOperator "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438dd5
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Managed" {
                background #f5a623
                color #ffffff
            }
            element "Person" {
                shape person
                background #08427b
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
