// Model Registry Operator - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6
// Source: architecture/rhoai-3.4-ea.1/model-registry-operator.md

workspace {
    model {
        datascientist = person "Data Scientist" "Creates and manages ML model registries and catalogs"
        admin = person "Platform Admin" "Deploys and configures model registry operator"

        modelRegistryOperator = softwareSystem "Model Registry Operator" "Kubernetes operator managing ModelRegistry CR lifecycle, model catalog, and per-instance auth proxies" {
            mrReconciler = container "ModelRegistryReconciler" "Reconciles ModelRegistry CRs; creates deployments, services, routes, RBAC, and kube-rbac-proxy per instance" "Go Controller"
            mcReconciler = container "ModelCatalogReconciler" "Manages singleton model catalog with PostgreSQL, RBAC, and routing" "Go Controller"
            migrationMgr = container "StorageMigrationManager" "CRD storage version migration v1alpha1 to v1beta1" "Go Component"
            webhookServer = container "Webhook Server" "Mutating and validating webhooks for ModelRegistry CRs" "Go Admission Webhook"
            capDetector = container "ClusterCapabilities Detector" "Detects OpenShift platform APIs and BYOIDC mode" "Go Component"
        }

        modelRegistryService = softwareSystem "Model Registry Service" "REST API for ML model metadata storage (deployed per CR)" {
            restContainer = container "model-registry REST" "REST API serving model metadata via MLMD protocol" "Go Service" "8080/TCP"
            kubeRBACProxy = container "kube-rbac-proxy" "RBAC-based authentication proxy sidecar" "Auth Proxy" "8443/TCP"
        }

        modelCatalogService = softwareSystem "Model Catalog" "Singleton catalog service for model metadata and benchmarks" {
            catalogREST = container "model-catalog REST" "Catalog REST API" "Go Service" "8080/TCP"
            catalogProxy = container "model-catalog kube-rbac-proxy" "RBAC auth proxy for catalog" "Auth Proxy" "8443/TCP"
        }

        // External systems
        postgresql = softwareSystem "PostgreSQL 16" "Relational database for model metadata storage" "Database"
        kubernetesAPI = softwareSystem "Kubernetes API Server" "Cluster API for resource management and RBAC enforcement" "Infrastructure"
        openshiftRouter = softwareSystem "OpenShift Router" "Ingress controller providing external route access" "Infrastructure"
        openshiftServingCert = softwareSystem "OpenShift Serving Cert Controller" "Auto-provisions TLS certificates for annotated services" "Infrastructure"

        // Internal ODH systems
        rhodsOperator = softwareSystem "rhods-operator" "Deploys model-registry-operator via kustomize overlay" "Internal RHOAI"
        odhPlatformAuth = softwareSystem "ODH Platform Auth Service" "Provides admin group configuration via Auth CR" "Internal RHOAI"
        odhPlatformMR = softwareSystem "ODH Platform ModelRegistry Component" "Platform-level ModelRegistry component CR" "Internal RHOAI"

        // Relationships - Users
        datascientist -> modelRegistryService "Accesses model registry REST API" "HTTPS/443 via Route"
        datascientist -> modelCatalogService "Browses model catalog" "HTTPS/443 via Route"
        admin -> modelRegistryOperator "Creates ModelRegistry CRs" "kubectl/oc"

        // Relationships - Operator
        modelRegistryOperator -> kubernetesAPI "Manages resources (CRUD), webhook admission" "HTTPS/443"
        modelRegistryOperator -> odhPlatformAuth "Reads admin groups from Auth CR" "HTTPS/443"
        modelRegistryOperator -> odhPlatformMR "Reads ModelRegistry component for owner refs" "HTTPS/443"
        rhodsOperator -> modelRegistryOperator "Deploys via kustomize overlay" "config/overlays/odh"

        // Relationships - Services
        modelRegistryService -> postgresql "Stores model metadata" "PostgreSQL/5432"
        modelCatalogService -> postgresql "Stores catalog metadata" "PostgreSQL/5432"
        kubeRBACProxy -> kubernetesAPI "TokenReview + SubjectAccessReview" "HTTPS/443"
        openshiftRouter -> modelRegistryService "Routes external traffic" "HTTPS/8443 reencrypt"
        openshiftRouter -> modelCatalogService "Routes external traffic" "HTTPS/8443 reencrypt"
        openshiftServingCert -> modelRegistryService "Provisions TLS certificates" "Annotation-based"
        openshiftServingCert -> modelRegistryOperator "Provisions TLS certificates" "Annotation-based"

        // Container relationships
        mrReconciler -> kubernetesAPI "Creates deployments, services, routes, RBAC" "HTTPS/443"
        mcReconciler -> kubernetesAPI "Creates catalog resources" "HTTPS/443"
        webhookServer -> kubernetesAPI "Admission responses" "HTTPS/9443"
    }

    views {
        systemContext modelRegistryOperator "SystemContext" {
            include *
            autoLayout
        }

        container modelRegistryOperator "OperatorContainers" {
            include *
            autoLayout
        }

        container modelRegistryService "ServiceContainers" {
            include *
            autoLayout
        }

        styles {
            element "Database" {
                shape Cylinder
                background #336791
                color #ffffff
            }
            element "Infrastructure" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Auth Proxy" {
                background #e74c3c
                color #ffffff
            }
            element "Person" {
                shape Person
                background #4a90e2
                color #ffffff
            }
        }
    }
}
