/*
 * NeMo Guardrails - C4 Context Diagram (Structurizr DSL)
 * Generated by: Claude Opus 4.6
 * Source: architecture/rhoai-3.4-ea.1/NeMo-Guardrails.md
 */

workspace {
    model {
        developer = person "AI Application Developer" "Configures guardrail policies using Colang DSL"
        endUser = person "End User" "Interacts via application (through orchestrator)"

        nemoGuardrails = softwareSystem "NeMo Guardrails" "Programmable guardrails toolkit for LLM-based conversational systems. Enforces safety, security, and behavior controls on LLM interactions." {
            guardrailsServer = container "Guardrails Server" "Main HTTP server exposing OpenAI-compatible API with guardrail extensions" "FastAPI/Uvicorn, Port 8000" "Service"
            actionsServer = container "Actions Server" "Separate server for executing custom actions" "FastAPI, Port 8001" "Service"
            llmRailsEngine = container "LLMRails Engine" "Core engine orchestrating guardrail evaluation (input, output, dialog, retrieval rails)" "Python Library"
            colangRuntime = container "Colang Runtime" "Interpreter for Colang v1.0 and v2.x domain-specific guardrail language" "Python Library"
            knowledgeBase = container "Knowledge Base" "Document embedding and retrieval for RAG-based guardrails" "Python Library"
            guardrailLibrary = container "Guardrail Library" "Built-in guardrails: content safety, jailbreak detection, hallucination, topic safety, SDD" "Python Library"
            embeddingProviders = container "Embedding Providers" "Pluggable embedding backends (FastEmbed, SentenceTransformers, HuggingFace)" "Python Library"
            tracingModule = container "Tracing Module" "OpenTelemetry-compatible tracing and span extraction" "Python Library"
        }

        fmsOrchestrator = softwareSystem "FMS Guardrails Orchestrator" "Routes guardrail requests to NeMo Guardrails server" "Internal RHOAI"
        backendLLM = softwareSystem "Backend LLM" "LLM inference services (vLLM, NVIDIA NIM, OpenAI)" "External"
        huggingFaceHub = softwareSystem "HuggingFace Hub" "Model weight repository (build-time only)" "External"

        /* Relationships */
        endUser -> fmsOrchestrator "Sends chat requests"
        fmsOrchestrator -> nemoGuardrails "POST /v1/chat/completions, /v1/guardrail/checks" "HTTP/8000"
        developer -> nemoGuardrails "Configures guardrail policies (Colang files)"

        nemoGuardrails -> backendLLM "Forwards prompts for LLM generation" "HTTPS/443, API Key"
        nemoGuardrails -> huggingFaceHub "Downloads model weights (build-time only)" "HTTPS/443"

        /* Internal container relationships */
        guardrailsServer -> llmRailsEngine "Delegates guardrail evaluation"
        llmRailsEngine -> colangRuntime "Executes Colang policies"
        llmRailsEngine -> guardrailLibrary "Evaluates built-in rails"
        llmRailsEngine -> knowledgeBase "Queries knowledge base"
        llmRailsEngine -> embeddingProviders "Generates embeddings"
        guardrailsServer -> actionsServer "Dispatches custom actions" "HTTP/8001"
        guardrailsServer -> tracingModule "Exports traces"
    }

    views {
        systemContext nemoGuardrails "SystemContext" {
            include *
            autoLayout
        }

        container nemoGuardrails "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                shape RoundedBox
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Service" {
                background #4a90e2
                color #ffffff
            }
            element "Person" {
                shape Person
                background #08427b
                color #ffffff
            }
        }
    }
}
