// C4 Context Diagram for Notebooks (Workbench Images)
// Generated by: Claude Opus 4.6

workspace {
    model {
        dataScientist = person "Data Scientist" "Uses notebook workbenches for interactive ML development"
        mlEngineer = person "ML Engineer" "Builds and runs ML pipelines using runtime images"

        notebooks = softwareSystem "Notebooks (Workbench Images)" "Pre-built container images providing interactive data science workbenches and pipeline runtimes for RHOAI" {
            workbenchImages = container "Workbench Images" "JupyterLab, VS Code Server, RStudio Server environments with ML/AI libraries" "Container Images (UBI9)"
            runtimeImages = container "Runtime Images" "Lightweight Elyra pipeline execution environments" "Container Images (UBI9)"
            baseImages = container "Base Images" "Foundation images with Python 3.12, CPU/CUDA/ROCm support" "Container Images (UBI9/C9S)"
            kustomizeManifests = container "Kustomize Manifests" "OpenShift ImageStream definitions for operator deployment" "YAML/Kustomize"
            tektonPipelines = container "Tekton Pipelines" "95 Konflux pipeline definitions for hermetic image builds" "Tekton PipelineRun"
        }

        // Internal RHOAI Dependencies
        rhodsOperator = softwareSystem "rhods-operator" "Deploys ImageStream resources to cluster from CSV RELATED_IMAGE refs" "Internal RHOAI"
        notebookController = softwareSystem "ODH Notebook Controller" "Launches workbench pods, injects kube-rbac-proxy, creates Services/HTTPRoutes" "Internal RHOAI"
        odhDashboard = softwareSystem "ODH Dashboard" "Web UI for selecting and launching notebook workbenches" "Internal RHOAI"
        elyra = softwareSystem "Elyra" "Visual pipeline editor using runtime images for node execution" "Internal RHOAI"
        kubeRbacProxy = softwareSystem "kube-rbac-proxy" "Authentication sidecar injected by controller for RBAC enforcement" "Internal RHOAI"
        dataScienceGateway = softwareSystem "data-science-gateway" "Gateway API gateway routing external traffic to notebook workbenches" "Internal RHOAI"

        // External Dependencies
        registryRedhat = softwareSystem "registry.redhat.io" "Red Hat container image registry for UBI9 base images" "External"
        quayIO = softwareSystem "quay.io" "Container image registry for built notebook images" "External"
        pypiOrg = softwareSystem "pypi.org" "Python Package Index for dependency installation" "External"
        konflux = softwareSystem "Konflux" "Tekton-based CI/CD for hermetic image builds" "External"
        kubernetesAPI = softwareSystem "Kubernetes API" "OpenShift cluster API server" "External"

        // Relationships
        dataScientist -> odhDashboard "Selects notebook image via" "HTTPS/443"
        dataScientist -> dataScienceGateway "Accesses workbench via" "HTTPS/443"
        mlEngineer -> elyra "Runs pipelines using" "HTTPS/443"

        odhDashboard -> notebookController "Creates Notebook CR" "HTTPS/6443"
        notebookController -> notebooks "Reads ImageStreams, launches pods from" "HTTPS/6443"
        rhodsOperator -> notebooks "Deploys ImageStream manifests from" "Kustomize"
        elyra -> notebooks "Executes pipeline nodes using runtime images from"

        notebooks -> registryRedhat "Pulls base images from" "HTTPS/443"
        notebooks -> quayIO "Pushes/pulls built images" "HTTPS/443"
        notebooks -> pypiOrg "Installs Python packages from" "HTTPS/443"
        konflux -> notebooks "Builds images via Tekton pipelines"
        notebooks -> kubernetesAPI "oc CLI access from running notebooks" "HTTPS/6443"

        dataScienceGateway -> kubeRbacProxy "Routes to sidecar" "HTTPS/8443"
        kubeRbacProxy -> notebooks "Proxies authenticated requests to notebook container" "HTTP/8888"

        baseImages -> workbenchImages "Foundation for"
        baseImages -> runtimeImages "Foundation for"
    }

    views {
        systemContext notebooks "SystemContext" {
            include *
            autoLayout
        }

        container notebooks "Containers" {
            include *
            autoLayout
        }

        styles {
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Person" {
                shape person
                background #4a90e2
                color #ffffff
            }
            element "Software System" {
                background #438dd5
                color #ffffff
            }
            element "Container" {
                background #85bbf0
                color #000000
            }
        }
    }
}
