// TrustyAI Service Operator - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6
// Source: architecture/rhoai-3.4-ea.1/trustyai-service-operator.md

workspace {
    model {
        dataScientist = person "Data Scientist" "Creates TrustyAI services, runs LM evaluations, configures guardrails"
        mlEngineer = person "ML Engineer" "Deploys and monitors AI/ML models with explainability and safety"

        trustyaiOperator = softwareSystem "TrustyAI Service Operator" "Multi-controller Kubernetes operator managing AI trustworthiness and safety services" {
            tasController = container "TAS Controller" "Reconciles TrustyAIService CRs; deploys explainability services with kube-rbac-proxy" "Go Controller"
            lmesController = container "LMES Controller" "Reconciles LMEvalJob CRs; creates evaluation pods with driver sidecar" "Go Controller"
            gorchController = container "GORCH Controller" "Reconciles GuardrailsOrchestrator CRs; deploys orchestrator with detectors and gateway" "Go Controller"
            nemoController = container "NEMO_GUARDRAILS Controller" "Reconciles NemoGuardrails CRs; deploys NeMo Guardrails servers" "Go Controller"
            evalhubController = container "EVALHUB Controller" "Reconciles EvalHub CRs; deploys evaluation hub with kube-rbac-proxy" "Go Controller"
            jobManager = container "Job Manager Controller" "Integrates LMEvalJob with Kueue for job scheduling" "Go Controller"
            lmesDriver = container "LMES Driver" "Sidecar binary managing evaluation job lifecycle" "Go Binary"
        }

        // Internal ODH Dependencies
        rhodsOperator = softwareSystem "RHODS Operator" "Deploys TrustyAI operator via kustomize overlays" "Internal RHOAI"
        kserve = softwareSystem "KServe" "ML model inference serving platform" "Internal RHOAI"
        modelMesh = softwareSystem "ModelMesh Serving" "Multi-model serving platform" "Internal RHOAI"
        odhOperator = softwareSystem "OpenDataHub Operator" "Platform operator providing DSC configuration" "Internal RHOAI"

        // External Dependencies
        istio = softwareSystem "Istio / Service Mesh" "Service mesh for mTLS and traffic routing" "External"
        kueue = softwareSystem "Kueue" "Job queuing and scheduling framework" "External"
        prometheus = softwareSystem "Prometheus / OpenShift Monitoring" "Metrics collection and alerting" "External"
        openshiftServiceCA = softwareSystem "OpenShift Service CA" "Automatic TLS certificate provisioning" "External"
        certManager = softwareSystem "OpenShift Router" "Ingress routing with TLS termination" "External"

        // External Services
        postgresql = softwareSystem "PostgreSQL" "Relational database for TrustyAI and EvalHub storage" "External Service"
        s3 = softwareSystem "S3-Compatible Storage" "Object storage for LMES offline data" "External Service"
        ociRegistries = softwareSystem "OCI Registries" "Container registries for LMES result upload" "External Service"
        gitRepos = softwareSystem "Git Repositories" "Source for LMES custom evaluation tasks" "External Service"
        otlp = softwareSystem "OTLP Endpoints" "OpenTelemetry endpoints for orchestrator telemetry" "External Service"
        mlflow = softwareSystem "MLFlow" "Experiment tracking for EvalHub" "External Service"

        // Relationships - Users
        dataScientist -> trustyaiOperator "Creates TrustyAIService, LMEvalJob, GuardrailsOrchestrator CRs via kubectl"
        mlEngineer -> trustyaiOperator "Monitors model fairness, runs evaluations"

        // Relationships - Internal
        rhodsOperator -> trustyaiOperator "Deploys via kustomize overlays"
        trustyaiOperator -> kserve "Patches InferenceService payloadProcessor; auto-discovers for guardrailing" "HTTPS/443"
        trustyaiOperator -> modelMesh "Patches MM_PAYLOAD_PROCESSORS env var" "HTTPS/443"
        odhOperator -> trustyaiOperator "Provides DSC config (trustyai-dsc-config ConfigMap)"

        // Relationships - External Dependencies
        trustyaiOperator -> istio "Creates DestinationRules and VirtualServices (when mesh present)"
        trustyaiOperator -> kueue "Creates Workloads for LMEvalJob scheduling" "HTTPS/443"
        trustyaiOperator -> prometheus "Exposes ServiceMonitors for metrics scraping" "HTTP/8080"
        trustyaiOperator -> openshiftServiceCA "Annotates services for automatic TLS cert provisioning"

        // Relationships - External Services
        trustyaiOperator -> postgresql "TrustyAI/EvalHub database storage" "TCP/configurable TLS optional"
        trustyaiOperator -> s3 "LMES offline data storage" "HTTPS/443"
        trustyaiOperator -> ociRegistries "LMES result upload" "HTTPS/443"
        trustyaiOperator -> gitRepos "LMES custom task download" "HTTPS/443"
        trustyaiOperator -> otlp "Orchestrator telemetry export" "gRPC/HTTP"
        trustyaiOperator -> mlflow "EvalHub experiment tracking" "HTTPS"
    }

    views {
        systemContext trustyaiOperator "SystemContext" {
            include *
            autoLayout
        }

        container trustyaiOperator "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Person" {
                shape Person
                background #08427b
                color #ffffff
            }
            element "Software System" {
                background #1168bd
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #000000
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "External Service" {
                background #f5a623
                color #000000
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
