/*
 * C4 Context Diagram: vllm-orchestrator-gateway
 * Generated by: Claude Opus 4.6
 */

workspace {
    model {
        client = person "API Client" "Sends OpenAI-compatible chat completion requests"

        gateway = softwareSystem "vllm-orchestrator-gateway" "Rust-based HTTP gateway that routes chat completion requests through configurable detector pipelines via the FMS Guardrails Orchestrator" {
            httpServer = container "axum HTTP Server" "Exposes /{route}/v1/chat/completions endpoints on port 8090; dynamically registers routes from YAML config" "Rust (axum 0.7.9)"
            configModule = container "Config Module" "Reads and validates YAML configuration defining orchestrator connection, detectors, and routes" "Rust (serde_yml)"
            apiModule = container "API Module" "Defines request/response data structures for orchestrator communication (OrchestratorResponse, StreamingResponse, Detections)" "Rust (serde)"
            orchestratorClient = container "Orchestrator HTTP Client" "Communicates with FMS Guardrails Orchestrator backend with optional mTLS support" "Rust (reqwest + native-tls)"
        }

        orchestrator = softwareSystem "FMS Guardrails Orchestrator" "Performs chat completions with detector-based content filtering" "Internal ODH"
        detectors = softwareSystem "Guardrails Detectors" "Content detection services (PII, toxicity, regex patterns)" "Internal ODH"
        vllm = softwareSystem "vLLM / LLM Backend" "Large Language Model inference service for chat completions" "Internal ODH"
        certManager = softwareSystem "Platform Certificate Provider" "Provisions TLS certificates (service-ca operator or cert-manager)" "External"

        /* Relationships */
        client -> gateway "POST /{route}/v1/chat/completions" "HTTP/8090 (plaintext), Authorization header pass-through"
        gateway -> orchestrator "POST /api/v2/chat/completions-detection" "HTTP or HTTPS/8085, Optional mTLS (TLS 1.2+)"
        orchestrator -> detectors "Invokes detectors for input/output content filtering" "Internal"
        orchestrator -> vllm "Sends chat completion requests for LLM inference" "Internal"
        certManager -> gateway "Provisions mTLS certificates" "kubernetes.io/tls secrets"

        /* Internal container relationships */
        httpServer -> orchestratorClient "Forwards requests with injected detector config"
        configModule -> httpServer "Provides route and detector configuration"
        apiModule -> orchestratorClient "Provides data structures for serialization"
    }

    views {
        systemContext gateway "SystemContext" {
            include *
            autoLayout
            description "System context showing vllm-orchestrator-gateway in the broader RHOAI ecosystem"
        }

        container gateway "Containers" {
            include *
            autoLayout
            description "Internal container structure of the vllm-orchestrator-gateway"
        }

        styles {
            element "Software System" {
                background #4a90e2
                color #ffffff
                shape RoundedBox
            }
            element "Internal ODH" {
                background #7ed321
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Person" {
                background #f5a623
                color #ffffff
                shape Person
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
