/*
 * Feast C4 Context Diagram (Structurizr DSL)
 * Generated by: Claude Opus 4.6
 * Source: architecture/rhoai-2.24/feast.md
 */

workspace {
    model {
        user = person "Data Scientist" "Creates FeatureStore CRs, defines feature definitions, retrieves features for ML training and inference"

        mlApp = person "ML Application" "Retrieves online/offline features for model inference and training"

        feast = softwareSystem "Feast Operator" "Manages Feast (Feature Store) deployments on Kubernetes/OpenShift, automating online/offline stores, registries, and UI services" {
            controller = container "FeatureStore Controller" "Watches FeatureStore CRs and reconciles all managed resources" "Go (controller-runtime)"
            onlineServer = container "Online Store Server" "Serves features for online inference via HTTP" "Python (feature-server), Ports: 6566/6567"
            offlineServer = container "Offline Store Server" "Serves features for batch/offline retrieval via gRPC" "Python (feature-server), Ports: 8815/8816"
            registryServer = container "Registry Server" "Central metadata registry via gRPC and REST" "Python (feature-server), Ports: 6570/6571 (gRPC), 6572/6573 (REST)"
            uiServer = container "UI Server" "Web UI for browsing the feature store" "Python (feature-server), Ports: 8888/8443"
            cronJob = container "CronJob" "Executes feast apply and feast materialize-incremental" "Kubernetes CronJob (ose-cli)"
            clientConfigMap = container "Client ConfigMap" "Provides feature_store.yaml for client applications" "Kubernetes ConfigMap"
        }

        rhodsOperator = softwareSystem "RHODS Operator" "Deploys Feast operator via kustomize overlays with RELATED_IMAGE injection" "Internal RHOAI"
        kubernetesAPI = softwareSystem "Kubernetes API Server" "Kubernetes control plane API" "Infrastructure"
        ocpServiceCerts = softwareSystem "OpenShift Service Serving Certs" "Auto-provisions TLS certificates for services" "Infrastructure"
        odhCABundle = softwareSystem "odh-trusted-ca-bundle" "Custom CA bundle ConfigMap for TLS trust" "Internal RHOAI"

        redis = softwareSystem "Redis" "In-memory data store for online feature serving" "External"
        postgresql = softwareSystem "PostgreSQL" "Relational database for online/offline/registry persistence" "External"
        snowflake = softwareSystem "Snowflake" "Cloud data warehouse for offline/online/registry persistence" "External"
        dynamodb = softwareSystem "DynamoDB" "AWS managed NoSQL for online feature serving" "External"
        cassandra = softwareSystem "Cassandra" "Distributed NoSQL for online feature serving" "External"
        gitRepos = softwareSystem "Git Repositories" "Feature repo initialization via git clone" "External"

        # Relationships
        user -> feast "Creates FeatureStore CR via kubectl" "HTTPS/443"
        mlApp -> onlineServer "Retrieves online features" "HTTP(S)/80 or 443"
        mlApp -> offlineServer "Retrieves historical features" "gRPC/80 or 443"

        rhodsOperator -> feast "Deploys via kustomize" "Kustomize"

        controller -> kubernetesAPI "Manages resources (Deployments, Services, PVCs, ConfigMaps, RBAC)" "HTTPS/443"
        controller -> onlineServer "Creates and manages" "Kubernetes Deployment"
        controller -> offlineServer "Creates and manages" "Kubernetes Deployment"
        controller -> registryServer "Creates and manages" "Kubernetes Deployment"
        controller -> uiServer "Creates and manages" "Kubernetes Deployment"
        controller -> cronJob "Creates and manages" "Kubernetes CronJob"

        cronJob -> onlineServer "Executes feast apply via kubectl exec" "kubectl exec / RBAC"

        onlineServer -> redis "Reads/writes features" "Redis protocol"
        onlineServer -> postgresql "Reads/writes features" "PostgreSQL protocol"
        onlineServer -> snowflake "Reads/writes features" "Snowflake protocol"
        onlineServer -> dynamodb "Reads/writes features" "DynamoDB API/HTTPS"
        onlineServer -> cassandra "Reads/writes features" "Cassandra protocol"

        offlineServer -> postgresql "Queries historical data" "PostgreSQL protocol"
        offlineServer -> snowflake "Queries historical data" "Snowflake protocol"

        ocpServiceCerts -> feast "Provisions TLS certificates" "Annotation-based"
        odhCABundle -> feast "Custom CA bundle" "ConfigMap mount"
        feast -> gitRepos "Clones feature repos" "HTTPS/443"
    }

    views {
        systemContext feast "SystemContext" {
            include *
            autoLayout
        }

        container feast "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Person" {
                shape Person
                background #4a90e2
                color #ffffff
            }
            element "Software System" {
                background #4a90e2
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Infrastructure" {
                background #e8e8e8
                color #333333
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
