/*
 * ML Metadata (MLMD) - C4 Context Diagram (Structurizr DSL)
 * Generated by: Claude Opus 4.6
 */

workspace {
    model {
        datascientist = person "Data Scientist" "Creates and runs ML pipelines that generate metadata"

        mlmd = softwareSystem "ML Metadata (MLMD)" "gRPC server for recording and retrieving metadata associated with ML pipeline workflows, tracking artifacts, executions, and their lineage" {
            grpcServer = container "metadata_store_server" "Main gRPC server binary exposing MetadataStoreService on port 8080" "C++ gRPC Server"
            serviceImpl = container "MetadataStoreServiceImpl" "Thread-safe implementation of all MetadataStoreService RPC methods" "C++ gRPC Service"
            metadataStore = container "MetadataStore" "Core metadata store logic implementing atomic CRUD operations" "C++ Library"
            metadataAccessObject = container "MetadataAccessObject" "Database abstraction layer handling SQL query generation" "C++ Library"
            pythonClient = container "Python Client Library" "Python client for connecting to MLMD gRPC server" "Python Package (ml-metadata)"
        }

        dsp = softwareSystem "Data Science Pipelines (DSP)" "Pipeline orchestration platform - primary consumer of MLMD" "Internal RHOAI"
        dspOperator = softwareSystem "DSP Operator" "Manages MLMD server deployment as part of DSP infrastructure" "Internal RHOAI"
        mysql = softwareSystem "MySQL/MariaDB" "Persistent metadata storage backend" "Database"
        postgresql = softwareSystem "PostgreSQL" "Persistent metadata storage backend" "Database"

        datascientist -> dsp "Runs ML pipelines"
        dsp -> mlmd "Stores and retrieves pipeline metadata (artifacts, executions, contexts, events, lineage)" "gRPC/HTTP2 on 8080/TCP, Optional TLS/mTLS"
        dspOperator -> mlmd "Deploys and configures MLMD server container" "Container Orchestration"
        mlmd -> mysql "Stores metadata records" "MySQL Protocol on 3306/TCP, Optional TLS"
        mlmd -> postgresql "Stores metadata records" "PostgreSQL Protocol on 5432/TCP, Optional TLS"
    }

    views {
        systemContext mlmd "SystemContext" {
            include *
            autoLayout
        }

        container mlmd "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Person" {
                shape Person
                background #08427b
                color #ffffff
            }
            element "Software System" {
                background #1168bd
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Database" {
                shape Cylinder
                background #f5a623
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
