// Model Registry Operator - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6
// Source: architecture/rhoai-2.24/model-registry-operator.md

workspace {
    model {
        dataScientist = person "Data Scientist" "Creates and manages ML model registry instances"
        platformAdmin = person "Platform Admin" "Deploys and configures the operator"

        modelRegistryOperator = softwareSystem "Model Registry Operator" "Kubernetes operator managing ModelRegistry instances for ML metadata storage" {
            reconciler = container "ModelRegistryReconciler" "Reconciles ModelRegistry CRs; creates Deployments, Services, Routes, RBAC, NetworkPolicies" "Go Controller (controller-runtime)"
            webhookServer = container "Webhook Server" "Mutating and validating webhooks for ModelRegistry CRs (v1alpha1/v1beta1)" "Go Webhook (9443/TCP HTTPS)"
            migrationManager = container "StorageMigrationManager" "Monitors and performs CRD storage version migration v1alpha1 to v1beta1" "Go Background Process"
            restProxy = container "REST Proxy" "model-registry binary in proxy mode; serves REST API with embedded MLMD gRPC backend" "Go Service (8080/TCP HTTP)"
            oauthProxy = container "OAuth Proxy Sidecar" "ose-oauth-proxy; authenticates via OpenShift OAuth with SAR delegation" "Sidecar (8443/TCP HTTPS)"
            catalogService = container "Model Catalog Service" "model-registry binary in catalog mode; optional feature-gated catalog API" "Go Service (8080/TCP HTTP)"
        }

        rhodsOperator = softwareSystem "RHODS Operator" "Deploys Model Registry Operator via kustomize overlays with image parameter injection" "Internal RHOAI"
        openshiftOAuth = softwareSystem "OpenShift OAuth" "Authenticates users accessing registry REST API" "External"
        openshiftRouter = softwareSystem "OpenShift Router" "Exposes registry routes externally via TLS reencrypt" "External"
        kubernetesAPI = softwareSystem "Kubernetes API Server" "Controller reconciliation, webhook registration, CRD migration" "External"
        postgresql = softwareSystem "PostgreSQL" "ML Metadata storage backend" "External"
        mysql = softwareSystem "MySQL" "ML Metadata storage backend (alternative)" "External"
        istio = softwareSystem "Istio Service Mesh" "Optional: VirtualService, DestinationRule, Gateway (being deprecated)" "External Deprecated"
        authorino = softwareSystem "Authorino" "Optional: AuthConfig for Istio-based auth (being deprecated)" "External Deprecated"

        // Relationships
        dataScientist -> modelRegistryOperator "Creates ModelRegistry CRs via kubectl/dashboard"
        platformAdmin -> rhodsOperator "Deploys operator"
        rhodsOperator -> modelRegistryOperator "Deploys via kustomize overlays/odh" "Kustomize"

        reconciler -> kubernetesAPI "CRUD resources (Deployments, Services, Routes, RBAC)" "HTTPS/6443"
        reconciler -> restProxy "Creates and manages"
        reconciler -> oauthProxy "Creates and manages"
        reconciler -> catalogService "Creates and manages (optional)"
        migrationManager -> kubernetesAPI "StorageVersionMigration API" "HTTPS/6443"

        dataScientist -> openshiftRouter "Accesses registry API" "HTTPS/443"
        openshiftRouter -> oauthProxy "Routes traffic" "HTTPS/8443 reencrypt"
        oauthProxy -> openshiftOAuth "Validates OAuth tokens" "HTTPS"
        oauthProxy -> restProxy "Forwards authenticated requests" "HTTP/8080 localhost"
        restProxy -> postgresql "Stores ML metadata" "TCP/5432 Optional SSL"
        restProxy -> mysql "Stores ML metadata" "TCP/3306 Optional SSL"

        kubernetesAPI -> webhookServer "Invokes admission webhooks" "HTTPS/9443"

        reconciler -> istio "Cleans up deprecated Istio config"
        reconciler -> authorino "Cleans up deprecated AuthConfig"
    }

    views {
        systemContext modelRegistryOperator "SystemContext" {
            include *
            autoLayout
        }

        container modelRegistryOperator "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438DD5
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "External Deprecated" {
                background #cccccc
                color #666666
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Person" {
                background #08427B
                color #ffffff
                shape person
            }
            element "Container" {
                background #438DD5
                color #ffffff
            }
        }
    }
}
