// C4 Context Diagram: modelmesh-runtime-adapter
// Generated by: Claude Opus 4.6
// Source: architecture/rhoai-2.24/modelmesh-runtime-adapter.md

workspace {
    model {
        mlEngineer = person "ML Engineer" "Deploys and serves ML models via ModelMesh"

        runtimeAdapter = softwareSystem "ModelMesh Runtime Adapter" "Sidecar that pulls model artifacts and adapts model lifecycle operations for different ML runtimes" {
            puller = container "model-serving-puller" "gRPC proxy that intercepts model lifecycle calls, pulls model artifacts from storage, forwards to adapter" "Go gRPC Server, Port 8084"
            tritonAdapter = container "Triton Adapter" "Translates ModelRuntime gRPC to NVIDIA Triton gRPC API" "Go gRPC Server, Port 8085"
            mlserverAdapter = container "MLServer Adapter" "Translates ModelRuntime gRPC to Seldon MLServer gRPC API" "Go gRPC Server, Port 8085"
            ovmsAdapter = container "OVMS Adapter" "Translates ModelRuntime gRPC to OpenVINO Model Server config-file-based management" "Go gRPC Server, Port 8085"
            torchserveAdapter = container "TorchServe Adapter" "Translates ModelRuntime gRPC to PyTorch TorchServe management/inference APIs" "Go gRPC Server, Port 8085"
            pullmanLib = container "pullman" "Pluggable storage provider framework for S3, GCS, Azure, HTTP, PVC" "Go Library"
        }

        modelMesh = softwareSystem "ModelMesh" "Intelligent model routing and placement system" "Internal RHOAI"
        modelMeshServing = softwareSystem "ModelMesh Serving" "Deployment orchestrator that configures and deploys runtime adapter as sidecar" "Internal RHOAI"
        restProxy = softwareSystem "REST Proxy" "Co-located sidecar providing HTTP inference endpoint" "Internal RHOAI"

        tritonRuntime = softwareSystem "NVIDIA Triton Inference Server" "High-performance ML inference runtime" "External"
        mlserverRuntime = softwareSystem "Seldon MLServer" "ML inference server supporting multiple frameworks" "External"
        ovmsRuntime = softwareSystem "OpenVINO Model Server" "Intel OpenVINO-based inference server" "External"
        torchserveRuntime = softwareSystem "PyTorch TorchServe" "PyTorch model serving framework" "External"

        s3Storage = softwareSystem "S3 / MinIO / IBM COS" "S3-compatible object storage for model artifacts" "External"
        gcsStorage = softwareSystem "Google Cloud Storage" "GCP object storage for model artifacts" "External"
        azureStorage = softwareSystem "Azure Blob Storage" "Azure object storage for model artifacts" "External"

        // Relationships
        modelMesh -> runtimeAdapter "Invokes ModelRuntime gRPC (loadModel, unloadModel, runtimeStatus)" "gRPC/8084 plaintext"
        modelMeshServing -> runtimeAdapter "Deploys and configures as sidecar container"

        puller -> pullmanLib "Uses for model artifact download"
        puller -> tritonAdapter "Forwards model lifecycle calls" "gRPC/8085 plaintext"
        puller -> mlserverAdapter "Forwards model lifecycle calls" "gRPC/8085 plaintext"
        puller -> ovmsAdapter "Forwards model lifecycle calls" "gRPC/8085 plaintext"
        puller -> torchserveAdapter "Forwards model lifecycle calls" "gRPC/8085 plaintext"

        tritonAdapter -> tritonRuntime "RepositoryModelLoad/Unload, ServerReady" "gRPC/8001 plaintext"
        mlserverAdapter -> mlserverRuntime "RepositoryModelLoad/Unload" "gRPC/8001 plaintext"
        ovmsAdapter -> ovmsRuntime "Config file updates + gRPC status" "gRPC/8001 plaintext"
        torchserveAdapter -> torchserveRuntime "RegisterModel/UnregisterModel" "gRPC/7070-7071 plaintext"

        pullmanLib -> s3Storage "Downloads model artifacts" "HTTPS/443 TLS 1.2+ Access Key"
        pullmanLib -> gcsStorage "Downloads model artifacts" "HTTPS/443 TLS 1.2+ OAuth2"
        pullmanLib -> azureStorage "Downloads model artifacts" "HTTPS/443 TLS 1.2+ Azure Identity"
    }

    views {
        systemContext runtimeAdapter "SystemContext" {
            include *
            autoLayout
        }

        container runtimeAdapter "Containers" {
            include *
            autoLayout
        }

        styles {
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Person" {
                shape person
                background #4a90e2
                color #ffffff
            }
            element "Software System" {
                background #4a90e2
                color #ffffff
            }
            element "Container" {
                background #5b9bd5
                color #ffffff
            }
        }
    }
}
