/*
 * C4 Context Diagram - Notebooks (Workbench Images)
 * Generated by: Claude Opus 4.6
 */
workspace {
    model {
        dataScientist = person "Data Scientist" "Creates and uses interactive workbenches for ML development"
        mlEngineer = person "ML Engineer" "Builds and runs Elyra pipelines using runtime images"

        notebooks = softwareSystem "Notebooks (Workbench Images)" "Pre-built container images for Jupyter, Code Server, and RStudio workbenches plus Elyra pipeline runtime images" {
            jupyterImages = container "Jupyter Workbench Images" "Minimal, Data Science, PyTorch, TensorFlow, TrustyAI, ROCm variants" "Container Images (UBI9 Python 3.11/3.12)"
            codeServerImages = container "Code Server Images" "VS Code in browser with data science libraries" "Container Images (code-server 4.98)"
            rstudioImages = container "RStudio Images" "RStudio Server with R 4.4 and Python" "Container Images (BuildConfig)"
            runtimeImages = container "Elyra Runtime Images" "Minimal, Data Science, PyTorch, TensorFlow runtime images" "Container Images (UBI9 Python 3.11/3.12)"
            kustomizeManifests = container "Kustomize Manifests" "ImageStream definitions, ConfigMaps with pinned digests, overlays" "Kustomize YAML"
            konfluxPipelines = container "Konflux CI/CD Pipelines" "61 Tekton PipelineRun definitions for building and publishing images" "Tekton PipelineRuns"
        }

        rhodsOperator = softwareSystem "rhods-operator" "Deploys ImageStream manifests into the cluster" "Internal RHOAI"
        notebookController = softwareSystem "ODH Notebook Controller" "Creates notebook pods, manages auth sidecars, ingress" "Internal RHOAI"
        odhDashboard = softwareSystem "ODH Dashboard" "Displays available workbench images to users via UI" "Internal RHOAI"
        dsPipelines = softwareSystem "Data Science Pipelines" "Executes Elyra pipelines using runtime images" "Internal RHOAI"

        openshift = softwareSystem "OpenShift Platform" "Container orchestration, OAuth, image registry" "External"
        quayRegistry = softwareSystem "quay.io/modh" "Container image registry for published images" "External"
        s3Storage = softwareSystem "S3-compatible Storage" "Model and pipeline artifact storage" "External"
        pypi = softwareSystem "PyPI / Package Registries" "Python package repositories" "External"
        ubi9Registry = softwareSystem "UBI9 Base Images" "Red Hat Universal Base Images (registry.access.redhat.com)" "External"

        # Relationships - Users
        dataScientist -> notebooks "Opens workbenches via Dashboard" "HTTPS/443"
        mlEngineer -> notebooks "Runs Elyra pipelines" "HTTPS/443"

        # Relationships - Internal
        rhodsOperator -> kustomizeManifests "Deploys ImageStream CRs from overlays/additional"
        notebookController -> jupyterImages "Creates notebook pods using image references" "Kubernetes API"
        notebookController -> codeServerImages "Creates notebook pods using image references" "Kubernetes API"
        notebookController -> rstudioImages "Creates notebook pods using image references" "Kubernetes API"
        odhDashboard -> notebooks "Reads ImageStream annotations (opendatahub.io/notebook-image-*)" "Kubernetes API"
        dsPipelines -> runtimeImages "Uses runtime ImageStream tags for pipeline execution"

        # Relationships - Build
        konfluxPipelines -> jupyterImages "Builds"
        konfluxPipelines -> codeServerImages "Builds"
        konfluxPipelines -> runtimeImages "Builds"
        konfluxPipelines -> quayRegistry "Publishes images" "HTTPS/443"
        ubi9Registry -> jupyterImages "Provides base images" "HTTPS/443"

        # Relationships - External
        notebooks -> openshift "oc CLI operations from notebooks" "HTTPS/443"
        notebooks -> s3Storage "Pipeline artifact storage" "HTTPS/443"
        notebooks -> pypi "Runtime pip install by users" "HTTPS/443"
        openshift -> quayRegistry "Imports images via ImageStreams" "HTTPS/443"
    }

    views {
        systemContext notebooks "SystemContext" {
            include *
            autoLayout
        }

        container notebooks "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Person" {
                shape person
                background #4a90e2
                color #ffffff
            }
            element "Software System" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Container" {
                background #4a90e2
                color #ffffff
            }
        }
    }
}
