// rhods-operator C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6
// Source: architecture/rhoai-2.24/rhods-operator.md

workspace {
    model {
        admin = person "Platform Admin" "Configures and manages the RHOAI platform on OpenShift"
        datascientist = person "Data Scientist" "Uses AI/ML platform components (Notebooks, Pipelines, Model Serving)"

        rhodsOperator = softwareSystem "rhods-operator (RHOAI Operator)" "Central platform operator managing lifecycle of all AI/ML components on OpenShift" {
            dsciController = container "DSCInitialization Controller" "Manages platform initialization: namespaces, monitoring, service mesh, CA bundles, auth" "Go Controller"
            dscController = container "DataScienceCluster Controller" "Orchestrates component lifecycle by creating/deleting component CRs based on DSC spec" "Go Controller"
            componentControllers = container "Component Controllers" "14 controllers deploying individual AI/ML components from kustomize manifests" "Go Controllers"
            serviceControllers = container "Service Controllers" "Auth, Monitoring, SecretGenerator, CertConfigmapGenerator, Setup" "Go Controllers"
            webhookServer = container "Webhook Server" "Validates and mutates DSC, DSCI, InferenceService, Notebook, Kueue resources" "Go Admission Webhooks"
        }

        // External Dependencies
        ocp = softwareSystem "OpenShift Container Platform" "Target platform (v4.15-v4.19)" "External"
        olm = softwareSystem "OLM" "Operator installation and lifecycle management" "External"
        istio = softwareSystem "OpenShift Service Mesh (Istio)" "Service mesh networking for KServe" "External"
        knative = softwareSystem "OpenShift Serverless (Knative)" "Serverless autoscaling for KServe" "External"
        authorino = softwareSystem "Authorino Operator" "External authorization provider" "External"
        tekton = softwareSystem "OpenShift Pipelines (Tekton)" "Pipeline execution for DSP" "External"
        prometheus = softwareSystem "Prometheus / Observability Operator" "Monitoring and alerting" "External"
        otel = softwareSystem "OpenTelemetry Operator" "Distributed tracing collection" "External"
        tempo = softwareSystem "Tempo Operator" "Trace storage backend" "External"
        certManager = softwareSystem "cert-manager" "Certificate management" "External"

        // Internal ODH Components (deployed by operator)
        dashboard = softwareSystem "ODH Dashboard" "Web UI for managing AI/ML workloads" "Internal RHOAI"
        notebooks = softwareSystem "Notebook Controller" "Jupyter notebook workbench management" "Internal RHOAI"
        kserve = softwareSystem "KServe" "Serverless ML model serving" "Internal RHOAI"
        modelmesh = softwareSystem "ModelMesh Serving" "Multi-model serving infrastructure" "Internal RHOAI"
        modelController = softwareSystem "ODH Model Controller" "Model management coordination" "Internal RHOAI"
        dsp = softwareSystem "Data Science Pipelines" "ML pipeline orchestration" "Internal RHOAI"
        codeflare = softwareSystem "CodeFlare" "Distributed computing stack" "Internal RHOAI"
        kuberay = softwareSystem "KubeRay" "Ray cluster operator" "Internal RHOAI"
        kueue = softwareSystem "Kueue" "Job queuing system" "Internal RHOAI"
        trustyai = softwareSystem "TrustyAI" "AI explainability service" "Internal RHOAI"
        modelRegistry = softwareSystem "Model Registry" "Model metadata storage" "Internal RHOAI"
        trainingOp = softwareSystem "Training Operator" "Distributed training jobs" "Internal RHOAI"

        // External Services
        segmentio = softwareSystem "segment.io" "Usage telemetry" "External Service"
        pagerduty = softwareSystem "PagerDuty" "Alerting (managed RHOAI)" "External Service"
        dms = softwareSystem "DeadManSnitch" "Monitoring heartbeat (managed RHOAI)" "External Service"

        // Relationships - Users
        admin -> rhodsOperator "Creates DSC/DSCI CRs via kubectl/oc"
        datascientist -> dashboard "Accesses AI/ML platform UI"

        // Relationships - Operator to external deps
        rhodsOperator -> ocp "Runs on" "HTTPS/6443"
        rhodsOperator -> olm "Installed via"
        rhodsOperator -> istio "Configures ServiceMeshControlPlane" "HTTPS/6443"
        rhodsOperator -> knative "Configures KnativeServing" "HTTPS/6443"
        rhodsOperator -> authorino "Configures Authorino CR" "HTTPS/6443"
        rhodsOperator -> tekton "Required for DSP component"
        rhodsOperator -> prometheus "Creates ServiceMonitor/PrometheusRule CRs" "HTTPS/6443"
        rhodsOperator -> otel "Creates OpenTelemetryCollector CR" "HTTPS/6443"
        rhodsOperator -> tempo "Creates TempoMonolithic/TempoStack CR" "HTTPS/6443"

        // Relationships - Operator deploys components
        rhodsOperator -> dashboard "Deploys via kustomize manifests"
        rhodsOperator -> notebooks "Deploys via kustomize manifests"
        rhodsOperator -> kserve "Deploys via kustomize manifests"
        rhodsOperator -> modelmesh "Deploys via kustomize manifests"
        rhodsOperator -> modelController "Deploys via kustomize manifests"
        rhodsOperator -> dsp "Deploys via kustomize manifests"
        rhodsOperator -> codeflare "Deploys via kustomize manifests"
        rhodsOperator -> kuberay "Deploys via kustomize manifests"
        rhodsOperator -> kueue "Deploys via kustomize manifests"
        rhodsOperator -> trustyai "Deploys via kustomize manifests"
        rhodsOperator -> modelRegistry "Deploys via kustomize manifests"
        rhodsOperator -> trainingOp "Deploys via kustomize manifests"

        // Relationships - External services
        rhodsOperator -> segmentio "Sends usage telemetry" "HTTPS/443"
        rhodsOperator -> pagerduty "Sends alerts (managed)" "HTTPS/443"
        rhodsOperator -> dms "Sends heartbeat (managed)" "HTTPS/443"

        // Internal container relationships
        dscController -> componentControllers "Creates component CRs"
        dsciController -> serviceControllers "Creates Auth/Monitoring CRs"
    }

    views {
        systemContext rhodsOperator "SystemContext" {
            include *
            autoLayout
        }

        container rhodsOperator "Containers" {
            include *
            autoLayout
        }

        styles {
            element "External" {
                background #999999
                color #ffffff
            }
            element "External Service" {
                background #f5a623
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Person" {
                shape Person
                background #4a90e2
                color #ffffff
            }
            element "Software System" {
                shape RoundedBox
            }
            element "Container" {
                shape RoundedBox
            }
        }
    }
}
