/*
 * C4 Context Diagram: vllm-orchestrator-gateway
 * Generated by: Claude Opus 4.6
 * Source: architecture/rhoai-2.24/vllm-orchestrator-gateway.md
 */

workspace {
    model {
        client = person "API Consumer" "Sends OpenAI-compatible chat completion requests"

        gateway = softwareSystem "vllm-orchestrator-gateway" "Rust HTTP gateway providing OpenAI-compatible chat completion endpoints with configurable guardrail detector pipelines" {
            httpServer = container "HTTP Server" "axum-based HTTP server exposing dynamic routes on port 8090" "Rust / axum 0.7.9"
            configLoader = container "Config Loader" "Reads YAML configuration defining orchestrator, detectors, and routes" "Rust / serde_yml"
            tlsBuilder = container "TLS Client Builder" "Builds HTTP/HTTPS client with optional mTLS for orchestrator communication" "Rust / openssl + native-tls"
            apiTypes = container "API Types" "Request/response data structures for orchestrator communication" "Rust / serde"
        }

        orchestrator = softwareSystem "FMS Guardrails Orchestrator" "Performs content detection via detector pipelines and guardrailed generation" "Internal - TrustyAI"
        detectors = softwareSystem "Guardrails Detectors" "Detector services (e.g., regex-language) for PII detection, content filtering" "Internal - TrustyAI"
        vllm = softwareSystem "vLLM / LLM Runtime" "Model serving backend (e.g., Qwen2.5-1.5B-Instruct)" "Internal"
        serviceCa = softwareSystem "OpenShift service-ca" "Provides TLS certificates for mTLS communication" "Platform"

        # Relationships
        client -> gateway "POST /{route}/v1/chat/completions" "HTTP/8090, plaintext, Auth header passthrough"
        gateway -> orchestrator "POST /api/v2/chat/completions-detection" "HTTP or HTTPS/8085, optional mTLS"
        orchestrator -> vllm "Inference request" "Varies"
        orchestrator -> detectors "Content detection" "Varies"
        serviceCa -> gateway "Provides TLS certificates" "File mount"

        # Internal container relationships
        configLoader -> httpServer "Provides route + detector configuration"
        tlsBuilder -> httpServer "Provides configured HTTP client"
        apiTypes -> httpServer "Defines request/response structures"
    }

    views {
        systemContext gateway "SystemContext" {
            include *
            autoLayout
        }

        container gateway "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438DD5
                color #ffffff
            }
            element "Person" {
                background #08427B
                color #ffffff
                shape person
            }
            element "Container" {
                background #438DD5
                color #ffffff
            }
            element "Internal - TrustyAI" {
                background #7ed321
                color #ffffff
            }
            element "Platform" {
                background #999999
                color #ffffff
            }
            element "Internal" {
                background #85BBF0
                color #000000
            }
        }
    }
}
