// C4 Context Diagram for llama-stack-provider-trustyai-garak
// Generated by: Claude Opus 4.6

workspace {
    model {
        user = person "Data Scientist / Security Engineer" "Runs LLM security scans and red-teaming assessments"

        trustyaiGarak = softwareSystem "TrustyAI Garak Provider" "Llama Stack out-of-tree provider for automated LLM security testing using NVIDIA Garak" {
            garakEvalAdapter = container "GarakEvalAdapter" "Inline Eval provider with async job management and semaphore-controlled concurrency" "Python Llama Stack Provider"
            garakRemoteEvalAdapter = container "GarakRemoteEvalAdapter" "Remote Eval provider executing scans via Kubeflow Pipelines" "Python Llama Stack Provider"
            shieldOrchestrator = container "SimpleShieldOrchestrator" "Orchestrates input/output shield checks around LLM inference for shield-integrated scanning" "Python HTTP Orchestrator"
            scanConfig = container "GarakScanConfig" "Compliance framework profiles (OWASP LLM Top 10, AVID) and scan profiles (quick, standard)" "Python Configuration"
        }

        llamaStackServer = softwareSystem "Llama Stack Server" "Host framework providing Files, Safety, Shields, Benchmarks APIs" "Internal RHOAI"
        vllm = softwareSystem "vLLM Inference Server" "OpenAI-compatible model serving endpoint for LLM inference" "Internal RHOAI"
        garakEngine = softwareSystem "NVIDIA Garak" "Red-teaming and vulnerability scanning engine (v0.12.0)" "External"
        kfp = softwareSystem "Kubeflow Pipelines (DSPA)" "Pipeline orchestration for remote scan execution" "Internal RHOAI"
        s3 = softwareSystem "S3/MinIO Object Storage" "Artifact storage for pipeline result passing" "External"
        promptGuard = softwareSystem "Prompt-Guard-86M" "Input shield for prompt injection detection" "Internal RHOAI"
        llamaGuard = softwareSystem "Llama-Guard-3-8B" "Output shield for content safety filtering" "Internal RHOAI"

        // User interactions
        user -> trustyaiGarak "Runs security scans via Llama Stack Eval API" "HTTP/8321"

        // Internal relationships
        garakEvalAdapter -> garakEngine "Spawns as subprocess for inline scanning"
        garakEvalAdapter -> llamaStackServer "Uploads scan reports via Files API" "HTTP/8321"
        garakRemoteEvalAdapter -> kfp "Submits and monitors pipeline runs" "HTTPS/443"
        garakRemoteEvalAdapter -> s3 "Retrieves scan artifacts" "HTTPS/443"
        shieldOrchestrator -> llamaStackServer "Calls Safety API for shield checks" "HTTP/8321"
        shieldOrchestrator -> vllm "Sends inference requests" "HTTP/HTTPS"

        // External dependencies
        trustyaiGarak -> vllm "Sends vulnerability probes to target LLM" "HTTP/HTTPS"
        trustyaiGarak -> llamaStackServer "Uses Files, Safety, Benchmarks APIs" "HTTP/8321"
        trustyaiGarak -> kfp "Remote pipeline execution" "HTTPS/443"
        trustyaiGarak -> s3 "Stores/retrieves scan artifacts" "HTTPS/443"
        trustyaiGarak -> promptGuard "Input shield checks via Safety API" "HTTP/8321"
        trustyaiGarak -> llamaGuard "Output shield checks via Safety API" "HTTP/8321"
    }

    views {
        systemContext trustyaiGarak "SystemContext" {
            include *
            autoLayout
        }

        container trustyaiGarak "Containers" {
            include *
            autoLayout
        }

        styles {
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Software System" {
                background #4a90e2
                color #ffffff
            }
            element "Container" {
                background #4a90e2
                color #ffffff
            }
            element "Person" {
                background #08427b
                color #ffffff
                shape Person
            }
        }
    }
}
