/*
 * C4 Context Diagram: llm-d-routing-sidecar
 * Generated by: Claude Opus 4.6
 * Source: architecture/rhoai-3.0/llm-d-routing-sidecar.md
 */

workspace {
    model {
        client = person "Client" "Sends OpenAI-compatible chat completion or completion API requests"

        routingSidecar = softwareSystem "llm-d-routing-sidecar" "Reverse proxy sidecar that enables disaggregated prefill/decode inference by routing LLM requests between prefiller and decoder vLLM instances" {
            proxy = container "Reverse Proxy" "HTTP/HTTPS reverse proxy intercepting inference requests, routing between prefill and decode phases" "Go HTTP Server" "8000/TCP"
            tlsManager = container "TLS Manager" "Manages TLS certificates (self-signed or provided) for secure proxy operation" "Go TLS"
            allowlistValidator = container "AllowlistValidator" "SSRF protection: watches InferencePool CRs and pods to maintain allowlist of valid prefill targets" "Go Kubernetes Client"
            nixlV2Connector = container "NIXL v2 Connector" "Primary P/D protocol handler: sends prefill with kv_transfer_params, receives KV metadata, forwards to decoder" "Go Protocol Handler"
            nixlV1Connector = container "NIXL v1 Connector" "Legacy P/D protocol using do_remote_decode/do_remote_prefill fields (deprecated)" "Go Protocol Handler"
            lmcacheConnector = container "LMCache Connector" "Legacy P/D protocol: sends prefill with max_tokens=1, then forwards to decoder (deprecated)" "Go Protocol Handler"
        }

        decoderVLLM = softwareSystem "vLLM Decoder" "Local vLLM inference engine for decode phase" "External - Same Pod"
        prefillerVLLM = softwareSystem "vLLM Prefiller" "Remote vLLM instances for prefill phase (KV cache computation)" "External - Remote Pods"
        kubernetesAPI = softwareSystem "Kubernetes API Server" "Provides watch streams for InferencePool and Pod resources" "External - Cluster"
        gatewayAPIExt = softwareSystem "Gateway API Inference Extension" "Defines InferencePool v1alpha2 CRD for valid prefill targets" "Internal RHOAI"
        openshiftRoute = softwareSystem "OpenShift Route" "Edge TLS termination and external ingress" "External - Cluster"

        /* Relationships */
        client -> openshiftRoute "Sends inference requests" "HTTPS/443 TLS"
        openshiftRoute -> routingSidecar "Forwards to sidecar" "HTTP/8080 (edge-terminated)"
        client -> routingSidecar "Direct inference requests" "HTTPS/8000 TLS 1.2+"
        routingSidecar -> decoderVLLM "Forwards decode/passthrough requests" "HTTP(S)/8001 configurable TLS"
        routingSidecar -> prefillerVLLM "Forwards prefill requests with kv_transfer_params" "HTTP(S)/variable configurable TLS"
        routingSidecar -> kubernetesAPI "Watches InferencePool + Pod resources (SSRF)" "HTTPS/443 TLS 1.2+ SA Token"
        gatewayAPIExt -> routingSidecar "Provides InferencePool CRD" "CRD dependency"

        /* Internal container relationships */
        proxy -> tlsManager "Uses for TLS configuration"
        proxy -> allowlistValidator "Validates prefiller targets"
        proxy -> nixlV2Connector "Routes P/D requests (primary)"
        proxy -> nixlV1Connector "Routes P/D requests (deprecated)"
        proxy -> lmcacheConnector "Routes P/D requests (deprecated)"
        allowlistValidator -> kubernetesAPI "Watches InferencePool + Pods" "HTTPS/443"
        nixlV2Connector -> prefillerVLLM "Sends prefill request" "HTTP(S)"
        nixlV2Connector -> decoderVLLM "Sends decode request with KV metadata" "HTTP(S)"
    }

    views {
        systemContext routingSidecar "SystemContext" {
            include *
            autoLayout
        }

        container routingSidecar "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438dd5
                color #ffffff
            }
            element "External - Same Pod" {
                background #7ed321
                color #ffffff
            }
            element "External - Remote Pods" {
                background #f5a623
                color #ffffff
            }
            element "External - Cluster" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Person" {
                shape person
                background #08427b
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
