/*
 * C4 Context Diagram - Notebooks (Workbench Images)
 * Generated by: Claude Opus 4.6
 */

workspace {
    model {
        dataScientist = person "Data Scientist" "Creates and uses interactive workbenches for ML/AI development"
        clusterAdmin = person "Cluster Admin" "Deploys and manages RHOAI platform"

        notebooks = softwareSystem "Notebooks (Workbench Images)" "Pre-built container images for interactive data science workbenches (Jupyter, Code Server, RStudio) and pipeline runtime environments" {
            jupyterImages = container "Jupyter Workbench Images" "JupyterLab 4.4 with CPU/CUDA/ROCm variants, PyTorch, TensorFlow, TrustyAI, LLM Compressor" "Container Images (UBI 9)"
            codeServerImages = container "Code Server Images" "VS Code web IDE (code-server 4.104) with data science libraries" "Container Images (UBI 9)"
            rstudioImages = container "RStudio Server Images" "RStudio Server 2025.09 with R 4.5, built via OpenShift BuildConfig" "Container Images (UBI 9)"
            runtimeImages = container "Pipeline Runtime Images" "Elyra pipeline runtime images for Minimal, Data Science, PyTorch, TensorFlow" "Container Images (UBI 9)"
            manifests = container "Kustomize Manifests" "ImageStream and ConfigMap definitions for 18 ImageStreams and 2 BuildConfigs" "YAML Manifests"
            tektonPipelines = container "Tekton Pipelines" "63 Konflux pipeline definitions for multi-arch container image builds" "Tekton PipelineRuns"
        }

        rhodsOperator = softwareSystem "rhods-operator" "Deploys RHOAI components via kustomize overlays" "Internal RHOAI"
        odhDashboard = softwareSystem "ODH Dashboard" "Web UI for RHOAI - displays available workbench images" "Internal RHOAI"
        notebookController = softwareSystem "odh-notebook-controller" "Creates workbench pods with kube-rbac-proxy sidecars" "Internal RHOAI"
        kfNotebookController = softwareSystem "kubeflow-notebook-controller" "Manages notebook pod lifecycle" "Internal RHOAI"

        ocp = softwareSystem "OpenShift Container Platform" "Target deployment platform (v4.19-v4.20)" "External"
        konflux = softwareSystem "Konflux CI/CD" "Builds and pushes multi-arch container images" "External"
        registryRedHat = softwareSystem "registry.redhat.io" "Production container image registry (N-1 versions)" "External"
        quayIO = softwareSystem "quay.io" "Upstream container image registry (N-2 through N-6 versions)" "External"
        github = softwareSystem "GitHub" "Source code repository for RStudio BuildConfig" "External"

        # Relationships
        clusterAdmin -> rhodsOperator "Configures RHOAI deployment"
        dataScientist -> odhDashboard "Selects workbench image and creates workbench"

        rhodsOperator -> notebooks "Deploys ImageStream/BuildConfig manifests" "Kustomize"
        odhDashboard -> notebooks "Reads ImageStream metadata for workbench selection UI" "HTTPS/6443"
        notebookController -> notebooks "Resolves image references from ImageStream tags" "HTTPS/6443"
        kfNotebookController -> notebooks "Manages notebook pod lifecycle using images" "HTTPS/6443"
        konflux -> notebooks "Builds multi-arch container images" "Tekton Pipelines"

        notebooks -> ocp "Deployed as ImageStreams and BuildConfigs" "HTTPS/6443"
        notebooks -> registryRedHat "Production images pulled from" "HTTPS/443"
        notebooks -> quayIO "Upstream images pulled from" "HTTPS/443"
        notebooks -> github "RStudio source code cloned from" "HTTPS/443"
    }

    views {
        systemContext notebooks "SystemContext" {
            include *
            autoLayout
        }

        container notebooks "Containers" {
            include *
            autoLayout
        }

        styles {
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Person" {
                shape Person
                background #4a90e2
                color #ffffff
            }
            element "Software System" {
                background #4a90e2
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
