// ODH Dashboard - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6

workspace {
    model {
        // People
        dataScientist = person "Data Scientist" "Creates and manages data science projects, notebooks, and model deployments"
        platformAdmin = person "Platform Administrator" "Configures RHOAI platform settings and manages cluster resources"

        // Primary System
        odhDashboard = softwareSystem "ODH Dashboard" "Primary web UI for Red Hat OpenShift AI - manages projects, notebooks, model serving, pipelines, and platform configuration" {
            frontend = container "React SPA Frontend" "PatternFly-based UI with Webpack Module Federation for plugin loading" "TypeScript/React"
            backend = container "Fastify BFF Backend" "API proxy to Kubernetes, serves frontend assets, handles WebSocket connections" "Node.js/TypeScript"
            kubeRbacProxy = container "kube-rbac-proxy" "TLS termination and Kubernetes RBAC-based authentication sidecar" "Go"
            modelRegistryUI = container "Model Registry UI" "Module Federation remote for Model Registry management" "TypeScript/React"
            genAiUI = container "Gen AI UI" "Module Federation remote for Gen AI features" "TypeScript/React"
        }

        // Internal ODH Systems
        rhodsOperator = softwareSystem "RHODS Operator" "Deploys and manages ODH Dashboard via kustomize overlays" "Internal ODH"
        kserve = softwareSystem "KServe" "ML model inference serving platform" "Internal ODH"
        modelRegistry = softwareSystem "Model Registry Operator" "Manages model registry instances and metadata" "Internal ODH"
        kubeflowNotebooks = softwareSystem "Kubeflow Notebook Controller" "Manages Jupyter notebook (workbench) lifecycle" "Internal ODH"
        dscController = softwareSystem "DSC Controller" "Manages DataScienceCluster and DSCInitialization resources" "Internal ODH"
        llamaStack = softwareSystem "Llama Stack" "Large language model stack management" "Internal ODH"
        feast = softwareSystem "Feast" "Feature store management" "Internal ODH"

        // External / Platform Systems
        gateway = softwareSystem "data-science-gateway" "Gateway API for external traffic ingress" "Platform"
        k8sAPI = softwareSystem "Kubernetes API Server" "Cluster API for all resource operations" "Platform"
        thanosQuerier = softwareSystem "Thanos Querier" "Prometheus metrics aggregation and querying" "Platform"
        openshiftConsole = softwareSystem "OpenShift Console" "OpenShift web console with application launcher" "Platform"
        openshiftOAuth = softwareSystem "OpenShift OAuth" "User authentication via OAuth flow" "Platform"
        serviceCa = softwareSystem "OpenShift service-ca" "Automatic TLS certificate provisioning and rotation" "Platform"

        // Relationships - Users
        dataScientist -> odhDashboard "Manages projects, notebooks, models, pipelines via" "HTTPS/443"
        platformAdmin -> odhDashboard "Configures platform settings and manages resources via" "HTTPS/443"

        // Relationships - Internal Container
        frontend -> backend "API calls and WebSocket connections" "HTTP/8080"
        kubeRbacProxy -> backend "Authenticated requests forwarded" "HTTP/8080 (loopback)"
        backend -> modelRegistryUI "Module Federation proxy" "HTTPS/8043"
        backend -> genAiUI "Module Federation proxy" "HTTPS/8143"

        // Relationships - External
        gateway -> odhDashboard "Routes external traffic via HTTPRoute" "HTTPS/8443"
        odhDashboard -> k8sAPI "CRD CRUD, resource watch, SubjectAccessReview" "HTTPS/443"
        odhDashboard -> thanosQuerier "Prometheus metrics queries" "HTTPS/9092"
        odhDashboard -> openshiftOAuth "User authentication flow" "HTTPS"
        odhDashboard -> openshiftConsole "ConsoleLink CR for app launcher" ""
        serviceCa -> odhDashboard "Provisions and rotates TLS certificates" ""

        // Relationships - ODH Components
        rhodsOperator -> odhDashboard "Deploys via kustomize overlay"
        odhDashboard -> kserve "Manages InferenceService and ServingRuntime CRs" "HTTPS/443"
        odhDashboard -> modelRegistry "Manages ModelRegistry CRs" "HTTPS/443"
        odhDashboard -> kubeflowNotebooks "Manages Notebook CRs" "HTTPS/443"
        odhDashboard -> dscController "Reads DataScienceCluster and DSCI status" "HTTPS/443"
        odhDashboard -> llamaStack "Reads LlamaStackDistribution CRs" "HTTPS/443"
        odhDashboard -> feast "Reads FeatureStore CRs" "HTTPS/443"
    }

    views {
        systemContext odhDashboard "SystemContext" {
            include *
            autoLayout
        }

        container odhDashboard "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438dd5
                color #ffffff
            }
            element "Person" {
                shape person
                background #08427b
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
            element "Internal ODH" {
                background #7ed321
                color #ffffff
            }
            element "Platform" {
                background #999999
                color #ffffff
            }
        }
    }
}
