/*
 * Training Operator (KFTO) - C4 Context Diagram
 * Generated by: Claude Opus 4.6
 */

workspace {
    model {
        user = person "Data Scientist" "Creates and manages distributed ML training jobs via kubectl or API"

        trainingOperator = softwareSystem "Training Operator (KFTO)" "Kubernetes operator managing distributed ML training jobs across PyTorch, TensorFlow, XGBoost, MPI, PaddlePaddle, and JAX frameworks" {
            controller = container "Training Operator Controller" "Reconciles 6 training job CRDs; creates Pods, Services, NetworkPolicies, HPAs, PodGroups" "Go (controller-runtime)"
            webhookServer = container "Webhook Server" "Validates training job CRs on CREATE/UPDATE for all 6 frameworks" "Go (9443/TCP HTTPS)"
            certRotator = container "Certificate Rotator" "Self-manages TLS certificates for webhook server" "Go (cert-controller)"
        }

        k8sAPI = softwareSystem "Kubernetes API Server" "Core Kubernetes API for resource management" "External"
        prometheus = softwareSystem "Prometheus / OpenShift Monitoring" "Metrics collection and monitoring" "Internal ODH"
        rhodsOperator = softwareSystem "RHODS Operator" "Deploys and manages Training Operator via kustomize overlays" "Internal ODH"
        volcano = softwareSystem "Volcano Scheduler" "Optional gang scheduling via PodGroups" "External (Optional)"
        schedulerPlugins = softwareSystem "Scheduler Plugins" "Optional gang scheduling via scheduler-plugins PodGroups" "External (Optional)"
        kueue = softwareSystem "Kueue (MultiKueue)" "Optional multi-cluster job delegation" "External (Optional)"

        // User interactions
        user -> trainingOperator "Creates training jobs (PyTorchJob, TFJob, etc.) via kubectl" "HTTPS/443"

        // Internal interactions
        controller -> k8sAPI "CRUD on Pods, Services, Events, NetworkPolicies, HPAs, PodGroups, CRDs" "HTTPS/443"
        certRotator -> k8sAPI "Manages webhook TLS certificates (Secrets, WebhookConfigurations)" "HTTPS/443"
        k8sAPI -> webhookServer "Sends admission review requests for training job validation" "HTTPS/9443"

        // ODH Internal
        rhodsOperator -> trainingOperator "Deploys via kustomize overlay" "Kustomize"
        prometheus -> trainingOperator "Scrapes metrics (job counts, pod groups, services)" "HTTP/8080"

        // Optional integrations
        trainingOperator -> volcano "Creates PodGroups for gang scheduling" "CRD"
        trainingOperator -> schedulerPlugins "Creates PodGroups for gang scheduling" "CRD"
        trainingOperator -> kueue "Delegates jobs via ManagedBy field" "CRD"
    }

    views {
        systemContext trainingOperator "SystemContext" {
            include *
            autoLayout
        }

        container trainingOperator "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #4a90e2
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "External (Optional)" {
                background #cccccc
                color #333333
                border dashed
            }
            element "Internal ODH" {
                background #7ed321
                color #ffffff
            }
            element "Person" {
                shape person
                background #08427b
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
