// TrustyAI Explainability - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6
// Source: architecture/rhoai-3.0/trustyai-explainability.md

workspace {
    model {
        dataScientist = person "Data Scientist" "Configures fairness metrics and drift detection for ML models"
        platformAdmin = person "Platform Admin" "Deploys and manages TrustyAI via the Operator"

        trustyai = softwareSystem "TrustyAI Explainability" "AI fairness metrics, explainability algorithms, and data drift detection service" {
            service = container "Explainability Service" "Quarkus REST service exposing fairness, drift, and explainer APIs; consumes inference payloads" "Java 17 / Quarkus 3.8.5"
            core = container "Explainability Core" "Core library: fairness metrics (SPD, DIR), explainers (LIME, SHAP, CF), drift detectors (KS, MMD)" "Java Library"
            connectors = container "Explainability Connectors" "KServe v1/v2 HTTP and gRPC prediction providers, protobuf definitions" "Java Library"
            prometheusPublisher = container "Prometheus Publisher" "Registers and updates Micrometer gauges (trustyai_*) for scheduled metrics" "Internal Component"
            cloudEventConsumer = container "CloudEvent Consumer" "Consumes Knative CloudEvents from KServe inference logger" "Internal Component"
            consumerEndpoint = container "Consumer Endpoint" "Receives ModelMesh partial inference payloads via HTTP POST" "Internal Component"
            reconciler = container "Inference Payload Reconciler" "Reconciles partial input/output payloads into complete prediction records" "Internal Component"
        }

        trustyaiOperator = softwareSystem "TrustyAI Service Operator" "Deploys and manages TrustyAI Service instances, configures storage, TLS, and auth proxy" "Internal RHOAI"
        modelmesh = softwareSystem "ModelMesh Serving" "Multi-model serving platform sending inference payloads" "Internal RHOAI"
        kserve = softwareSystem "KServe" "Single-model serverless inference platform with inference logger" "Internal RHOAI"
        prometheus = softwareSystem "Prometheus / OpenShift Monitoring" "Metrics collection and alerting platform" "External"
        odhDashboard = softwareSystem "ODH Dashboard" "Web UI for managing AI/ML workloads" "Internal RHOAI"

        mariadb = softwareSystem "MariaDB/MySQL" "Relational database for inference data storage" "External"
        minio = softwareSystem "MinIO" "S3-compatible object storage for inference data" "External"
        pvc = softwareSystem "PersistentVolumeClaim" "Kubernetes persistent storage for CSV inference data" "External"

        // User relationships
        dataScientist -> trustyai "Configures fairness/drift metrics via REST API"
        platformAdmin -> trustyaiOperator "Deploys TrustyAI instances via TrustyAIService CR"

        // Operator manages TrustyAI
        trustyaiOperator -> trustyai "Deploys and manages Deployment, Service, Route, ConfigMap, PVC"

        // Inbound data flows
        modelmesh -> trustyai "Sends inference payloads via HTTP POST /consumer/kserve/v2" "HTTP/80"
        kserve -> trustyai "Sends inference CloudEvents (request/response)" "HTTP/8080"
        prometheus -> trustyai "Scrapes /q/metrics for trustyai_* gauges" "HTTP/80"
        odhDashboard -> trustyai "UI management of fairness metrics" "HTTPS/443"

        // Outbound data flows
        trustyai -> kserve "Invokes model inference for explainer computation" "gRPC/HTTP"
        trustyai -> modelmesh "Invokes model inference for explainer computation" "gRPC/HTTP"
        trustyai -> mariadb "Persists inference data (DATABASE mode)" "MySQL/3306"
        trustyai -> minio "Persists inference data (MINIO mode)" "HTTP(S)/9000"
        trustyai -> pvc "Persists inference data (PVC mode, default)" "Filesystem"

        // Internal container relationships
        service -> core "Uses fairness, explainer, and drift algorithms"
        service -> connectors "Uses for KServe v1/v2 inference calls"
        consumerEndpoint -> reconciler "Forwards partial payloads"
        cloudEventConsumer -> reconciler "Forwards parsed events"
        reconciler -> service "Stores reconciled predictions"
        service -> prometheusPublisher "Publishes metric gauges"
    }

    views {
        systemContext trustyai "SystemContext" {
            include *
            autoLayout
        }

        container trustyai "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Person" {
                shape Person
                background #4a90e2
                color #ffffff
            }
            element "Software System" {
                background #4a90e2
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
