// Data Science Pipelines Operator - C4 Context Diagram
// Generated by: Claude Opus 4.6

workspace {
    model {
        datascientist = person "Data Scientist" "Creates and manages ML pipelines via Dashboard or CLI"
        admin = person "Platform Admin" "Deploys and configures DSPA instances"

        dspo = softwareSystem "Data Science Pipelines Operator" "Manages lifecycle of DSP infrastructure by reconciling DSPA custom resources" {
            controller = container "DSPO Controller Manager" "Reconciles DSPA CRs, deploys all DSP sub-components via Go templates" "Go Operator (controller-runtime)"
            webhook = container "DS Pipelines Webhook" "Validates/mutates Pipeline and PipelineVersion CRs" "Admission Webhook"
            apiServer = container "DS Pipeline API Server" "Kubeflow Pipelines V2 API with HTTP (8888) and gRPC (8887)" "Go Service"
            kubeRbacProxy = container "kube-rbac-proxy" "Authenticates API requests via K8s SubjectAccessReview" "Sidecar (port 8443)"
            persistenceAgent = container "Persistence Agent" "Syncs pipeline run status from Argo Workflows to DB" "Go Service"
            scheduledWorkflow = container "Scheduled Workflow" "Manages cron-scheduled pipeline runs" "Go Service"
            workflowController = container "Workflow Controller" "Argo Workflow controller for pipeline execution" "Argo Controller"
            mlmdServer = container "MLMD gRPC Server" "ML Metadata service for artifact/execution lineage" "gRPC Service (8080)"
            mlmdEnvoy = container "MLMD Envoy Proxy" "Proxies MLMD gRPC with kube-rbac-proxy auth" "Envoy (9090)"
            mariadb = container "MariaDB" "Pipeline metadata database" "MariaDB (3306)"
            minio = container "Minio" "Pipeline artifact object storage" "S3-compatible (9000)"
        }

        rhodsOperator = softwareSystem "rhods-operator" "Deploys DSPO via kustomize overlays" "Internal RHOAI"
        openshiftRouter = softwareSystem "OpenShift Router" "Ingress for external access via Routes" "Platform"
        openshiftServiceCA = softwareSystem "OpenShift service-ca" "Auto-generates TLS certificates" "Platform"
        kubernetesAPI = softwareSystem "Kubernetes API" "CRD operations and RBAC checks" "Platform"
        prometheus = softwareSystem "Prometheus" "Metrics collection via ServiceMonitor" "Platform"
        argoWorkflows = softwareSystem "Argo Workflows" "Pipeline workflow execution engine" "External"
        kserve = softwareSystem "KServe" "ML model serving (InferenceService)" "Internal RHOAI"
        codeflare = softwareSystem "CodeFlare" "Distributed computing (AppWrappers)" "Internal RHOAI"
        ray = softwareSystem "Ray" "Distributed compute (RayCluster/RayJob)" "Internal RHOAI"
        externalDB = softwareSystem "External Database" "MySQL-compatible database (optional)" "External"
        externalS3 = softwareSystem "External S3 Storage" "S3-compatible object storage (optional)" "External"

        // User interactions
        datascientist -> dspo "Creates/manages pipelines via API" "HTTPS/443"
        admin -> dspo "Creates DSPA CRs via kubectl" "kubectl"

        // Internal container relationships
        controller -> apiServer "Deploys and manages" "Kubernetes API"
        controller -> persistenceAgent "Deploys" "Kubernetes API"
        controller -> scheduledWorkflow "Deploys" "Kubernetes API"
        controller -> workflowController "Deploys" "Kubernetes API"
        controller -> mlmdServer "Deploys" "Kubernetes API"
        controller -> mlmdEnvoy "Deploys" "Kubernetes API"
        controller -> mariadb "Deploys and health-checks" "MySQL/3306"
        controller -> minio "Deploys and health-checks" "S3 API"
        kubeRbacProxy -> apiServer "Proxies authorized requests" "HTTP/8888 TLS"
        kubeRbacProxy -> kubernetesAPI "SubjectAccessReview" "HTTPS/443"
        apiServer -> mariadb "Stores pipeline metadata" "MySQL/3306 TLS"
        apiServer -> minio "Stores pipeline artifacts" "S3 API TLS"
        persistenceAgent -> apiServer "Updates run status" "HTTP/8888 TLS"
        mlmdServer -> mariadb "Stores lineage metadata" "MySQL/3306 TLS"
        mlmdEnvoy -> mlmdServer "Forwards gRPC requests" "gRPC/8080 TLS"

        // Platform dependencies
        rhodsOperator -> dspo "Deploys DSPO via kustomize" "Kustomize overlays"
        dspo -> openshiftRouter "Creates Routes for external access" "HTTPS/443 reencrypt"
        dspo -> openshiftServiceCA "Uses for pod-to-pod TLS certs" "Annotation-triggered"
        dspo -> kubernetesAPI "Manages CRDs and resources" "HTTPS/443"
        dspo -> argoWorkflows "Creates Workflow CRs for execution" "Kubernetes API"
        prometheus -> dspo "Scrapes operator and component metrics" "HTTP/8080, 9090"

        // Integration points
        dspo -> kserve "Pipeline steps create InferenceServices" "Kubernetes API"
        dspo -> codeflare "Pipeline steps use AppWrappers" "Kubernetes API"
        dspo -> ray "Pipeline steps use Ray clusters" "Kubernetes API"

        // External services (optional)
        dspo -> externalDB "Alternative to built-in MariaDB" "MySQL/3306 TLS"
        dspo -> externalS3 "Alternative to built-in Minio" "HTTPS/443"
    }

    views {
        systemContext dspo "SystemContext" {
            include *
            autoLayout
        }

        container dspo "Containers" {
            include *
            autoLayout
        }

        styles {
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Platform" {
                background #4a90e2
                color #ffffff
            }
            element "Person" {
                shape person
                background #08427b
                color #ffffff
            }
            element "Software System" {
                background #1168bd
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
