// Data Science Pipelines - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6
// Source: architecture/rhoai-3.2/data-science-pipelines.md

workspace {
    model {
        user = person "Data Scientist" "Creates and manages ML pipelines, experiments, and runs"

        dsp = softwareSystem "Data Science Pipelines" "Kubeflow Pipelines - End-to-end ML workflow orchestration on Kubernetes" {
            apiServer = container "ml-pipeline (API Server)" "REST/gRPC API server for pipeline management; v1beta1 and v2beta1 APIs" "Go Service" {
                tags "Core"
            }
            ui = container "ml-pipeline-ui" "Web UI for pipeline visualization, experiment management, and run monitoring" "React/Node.js Frontend" {
                tags "Core"
            }
            persistenceAgent = container "ml-pipeline-persistenceagent" "Watches Argo Workflows and ScheduledWorkflows, reports status back to API server" "Go Service" {
                tags "Core"
            }
            scheduledWorkflow = container "ml-pipeline-scheduledworkflow" "Kubernetes controller for ScheduledWorkflow CRD; creates Argo Workflows on schedule" "Go Controller" {
                tags "Core"
            }
            viewerCRD = container "ml-pipeline-viewer-crd" "Kubernetes controller for Viewer CRD; manages visualization deployments" "Go Controller" {
                tags "Core"
            }
            cacheServer = container "cache-server" "Admission webhook server for pipeline execution caching" "Go Service" {
                tags "Core"
            }
            mlmdServer = container "metadata-grpc-server (MLMD)" "ML Metadata gRPC server for artifact and execution lineage tracking" "C++ Service" {
                tags "Metadata"
            }
            metadataEnvoy = container "metadata-envoy" "Envoy proxy for MLMD gRPC-Web access" "Envoy Proxy" {
                tags "Metadata"
            }
            metadataWriter = container "metadata-writer" "Watches Argo Workflows and writes execution metadata to MLMD" "Python Service" {
                tags "Metadata"
            }
            vizServer = container "ml-pipeline-visualizationserver" "Generates pipeline run visualizations" "Python Service" {
                tags "Core"
            }
            driver = container "kfp-driver" "V2 pipeline DAG driver; orchestrates pipeline steps within Argo Workflow pods" "Go Binary" {
                tags "V2Runtime"
            }
            launcher = container "kfp-launcher" "V2 pipeline task launcher; executes individual pipeline tasks within pods" "Go Binary" {
                tags "V2Runtime"
            }
        }

        argoWorkflows = softwareSystem "Argo Workflows" "Workflow execution engine for pipeline runs (v3.5-v3.7)" {
            tags "External"
        }
        database = softwareSystem "Database (MySQL/PostgreSQL)" "Primary relational database for pipeline metadata" {
            tags "External"
        }
        objectStore = softwareSystem "Object Store (MinIO/S3)" "Object storage for pipeline artifacts and logs" {
            tags "External"
        }
        k8sAPI = softwareSystem "Kubernetes API Server" "Cluster API for CRD operations, pod lifecycle, RBAC" {
            tags "External"
        }
        istio = softwareSystem "Istio Service Mesh" "Service mesh for traffic management, mTLS, AuthorizationPolicy" {
            tags "External"
        }
        certManager = softwareSystem "cert-manager" "TLS certificate management for webhooks" {
            tags "External"
        }
        dspOperator = softwareSystem "data-science-pipelines-operator" "Deploys and configures all DSP components in RHOAI" {
            tags "Internal ODH"
        }

        // User interactions
        user -> dsp "Creates pipelines, experiments, runs via UI/SDK"
        user -> ui "Browses pipelines, monitors runs" "HTTPS/443"

        // Internal container relationships
        ui -> apiServer "Pipeline operations" "HTTP/8888 (Istio mTLS)"
        ui -> metadataEnvoy "Query metadata" "gRPC-Web/9090"
        persistenceAgent -> apiServer "Report workflow status" "gRPC/8887"
        metadataEnvoy -> mlmdServer "Forward metadata queries" "gRPC/8080"
        metadataWriter -> mlmdServer "Write execution metadata" "gRPC/8080"
        driver -> launcher "Orchestrate task execution"

        // External dependencies
        apiServer -> database "Store pipeline metadata" "SQL/3306 or 5432"
        apiServer -> objectStore "Store pipeline artifacts" "S3 API/9000 or 443"
        apiServer -> k8sAPI "Create Argo Workflows, manage CRDs" "HTTPS/443"
        cacheServer -> database "Check/store execution cache" "SQL/3306 or 5432"
        mlmdServer -> database "Store artifact/execution lineage" "SQL/3306 or 5432"
        persistenceAgent -> k8sAPI "Watch Workflows" "HTTPS/443"
        scheduledWorkflow -> k8sAPI "Watch ScheduledWorkflows, create Workflows" "HTTPS/443"
        metadataWriter -> k8sAPI "Watch Workflows" "HTTPS/443"
        k8sAPI -> argoWorkflows "Execute pipeline workflows"
        dsp -> istio "Uses for traffic routing and mTLS"
        dsp -> certManager "TLS certificate provisioning for webhooks"

        // Operator relationship
        dspOperator -> dsp "Deploys and configures all components"
    }

    views {
        systemContext dsp "SystemContext" {
            include *
            autoLayout
        }

        container dsp "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438dd5
                color #ffffff
            }
            element "Person" {
                background #08427b
                color #ffffff
                shape Person
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal ODH" {
                background #7ed321
                color #ffffff
            }
            element "Core" {
                background #4a90e2
                color #ffffff
            }
            element "Metadata" {
                background #9b59b6
                color #ffffff
            }
            element "V2Runtime" {
                background #e67e22
                color #ffffff
            }
        }
    }
}
