// C4 Context Diagram - Distributed Workloads
// Generated by: Claude Opus 4.6
// Source: architecture/rhoai-3.2/distributed-workloads.md

workspace {
    model {
        // Actors
        datascientist = person "Data Scientist" "Develops and runs distributed ML training workloads"
        mlEngineer = person "ML Engineer" "Configures training runtimes and manages job queues"
        cicd = person "CI/CD Pipeline" "Automated Konflux/Tekton pipeline builds"

        // Main system
        distributedWorkloads = softwareSystem "Distributed Workloads" "Training runtime images and integration test suite for RHOAI distributed training stack" {
            trainingImages = container "Training Runtime Images" "UBI9-based container images with CUDA/ROCm, PyTorch, Flash Attention, NCCL, RDMA" "Container Images"
            rayImages = container "Ray Runtime Images" "Ray 2.52.1 images with CUDA/ROCm GPU support" "Container Images"
            universalImages = container "Universal Training Images" "Combined Jupyter workbench + ML runtime images" "Container Images"
            testSuite = container "Integration Test Suite" "End-to-end Go tests validating distributed workloads lifecycle" "Go Test Framework"
            notebooks = container "Example Notebooks" "LLM fine-tuning, DreamBooth, HPO demonstrations" "Jupyter Notebooks"
            pipelines = container "Tekton/Konflux Pipelines" "Automated image build pipelines" "CI/CD"
        }

        // Internal RHOAI dependencies
        kueue = softwareSystem "Kueue" "Job queuing and resource quota management" "Internal RHOAI"
        kuberay = softwareSystem "KubeRay" "Ray cluster lifecycle management" "Internal RHOAI"
        trainingOperator = softwareSystem "Training Operator v1" "PyTorchJob distributed training orchestration" "Internal RHOAI"
        trainerV2 = softwareSystem "Kubeflow Trainer v2" "TrainJob and ClusterTrainingRuntime orchestration" "Internal RHOAI"
        jobsetController = softwareSystem "JobSet Controller" "Multi-job coordination for Trainer v2" "Internal RHOAI"
        rhoaiOperator = softwareSystem "RHOAI Operator" "Platform component lifecycle management" "Internal RHOAI"

        // External dependencies
        kubernetes = softwareSystem "Kubernetes/OpenShift" "Container orchestration platform" "External"
        s3Storage = softwareSystem "S3 Storage" "Model artifact and dataset storage (AWS/MinIO)" "External"
        huggingface = softwareSystem "HuggingFace Hub" "Pre-trained model repository" "External"
        prometheus = softwareSystem "OpenShift Prometheus" "GPU utilization metrics monitoring" "External"
        containerRegistries = softwareSystem "Container Registries" "quay.io, registry.redhat.io" "External"

        // Relationships - Users
        datascientist -> distributedWorkloads "Runs distributed training jobs using training runtime images"
        mlEngineer -> distributedWorkloads "Configures ClusterQueues, training runtimes, and resource quotas"
        cicd -> pipelines "Triggers automated image builds"

        // Relationships - Internal
        testSuite -> kueue "Creates ClusterQueue/LocalQueue CRs via Kubernetes API" "HTTPS/6443"
        testSuite -> kuberay "Creates RayCluster/RayJob CRs via Kubernetes API" "HTTPS/6443"
        testSuite -> trainingOperator "Creates PyTorchJob CRs via Kubernetes API" "HTTPS/6443"
        testSuite -> trainerV2 "Creates TrainJob CRs via Kubernetes API" "HTTPS/6443"
        testSuite -> prometheus "Queries GPU metrics (DCGM_FI_DEV_GPU_UTIL)" "HTTPS/443"
        testSuite -> rhoaiOperator "Reads DataScienceCluster CR for component state" "HTTPS/6443"

        trainingImages -> trainingOperator "Used as worker pod images for PyTorchJob"
        trainingImages -> trainerV2 "Used as worker pod images for TrainJob"
        rayImages -> kuberay "Used as Ray head/worker pod images"

        trainerV2 -> jobsetController "Creates JobSet CRs for multi-job coordination"
        kueue -> trainingOperator "Admits/suspends PyTorchJob workloads"
        kueue -> kuberay "Admits/suspends RayJob workloads"
        kueue -> trainerV2 "Admits/suspends TrainJob workloads"

        pipelines -> trainingImages "Builds CUDA/ROCm/CPU training images"
        pipelines -> rayImages "Builds Ray runtime images"
        pipelines -> universalImages "Builds universal training images"

        // Relationships - External
        distributedWorkloads -> kubernetes "Deploys workloads, manages pods" "HTTPS/6443"
        distributedWorkloads -> s3Storage "Downloads datasets, uploads models" "HTTPS/443"
        distributedWorkloads -> huggingface "Downloads pre-trained models" "HTTPS/443"
        pipelines -> containerRegistries "Pushes/pulls container images" "HTTPS/443"
    }

    views {
        systemContext distributedWorkloads "SystemContext" {
            include *
            autoLayout
        }

        container distributedWorkloads "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438DD5
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Container" {
                background #4a90e2
                color #ffffff
            }
            element "Person" {
                shape Person
                background #08427B
                color #ffffff
            }
        }
    }
}
