/*
 * KubeRay Operator - C4 Context Diagram (Structurizr DSL)
 * Generated by: Claude Opus 4.6
 */

workspace {
    model {
        user = person "Data Scientist" "Creates and manages Ray clusters, jobs, and services on OpenShift"

        kuberay = softwareSystem "KubeRay Operator" "Manages lifecycle of Ray clusters, jobs, and services on Kubernetes/OpenShift" {
            rcController = container "RayCluster Controller" "Creates/manages head pods, worker pods, services, ingress, autoscaler RBAC" "Go (controller-runtime)"
            rjController = container "RayJob Controller" "Manages RayJob lifecycle, creates RayClusters, submits jobs via K8s Job" "Go (controller-runtime)"
            rsController = container "RayService Controller" "Manages RayService lifecycle with blue-green upgrade strategy" "Go (controller-runtime)"
            authController = container "Authentication Controller" "Manages kube-rbac-proxy sidecars, HTTPRoutes, ReferenceGrants per RayCluster" "Go (controller-runtime)"
            npController = container "NetworkPolicy Controller" "Creates head and worker NetworkPolicies per RayCluster" "Go (controller-runtime)"
            mtlsController = container "mTLS Controller" "Creates cert-manager Issuers and Certificates for head/worker TLS" "Go (controller-runtime)"
            webhook = container "Mutating Webhook" "Validates and defaults RayCluster resources on CREATE/UPDATE" "Go Webhook Server" "9443/TCP"
        }

        rayCluster = softwareSystem "Ray Cluster" "Distributed computing cluster (head + workers)" "Managed Workload" {
            headPod = container "Ray Head Pod" "Ray head node with dashboard, GCS server, and auth proxy sidecar" "Ray + kube-rbac-proxy"
            workerPods = container "Ray Worker Pods" "Ray worker nodes for distributed computation" "Ray"
        }

        # External Dependencies
        openshift = softwareSystem "OpenShift Platform" "Container orchestration platform with Routes, SCC, serving certs" "External"
        certManager = softwareSystem "cert-manager" "X.509 certificate management for Kubernetes" "External"
        gatewayAPI = softwareSystem "Gateway API" "HTTPRoute-based ingress via data-science-gateway" "External"
        volcano = softwareSystem "Volcano / Yunikorn" "Batch and gang scheduling for Kubernetes" "External"
        redis = softwareSystem "Redis" "External storage for GCS fault tolerance" "External"

        # Internal ODH Dependencies
        rhodsOperator = softwareSystem "rhods-operator" "Deploys KubeRay operator via kustomize openshift overlay" "Internal ODH"
        dsgGateway = softwareSystem "data-science-gateway" "Platform gateway for authenticated access to Ray dashboards" "Internal ODH"
        kubeRBACProxy = softwareSystem "ose-kube-rbac-proxy" "Authentication proxy sidecar injected into Ray head pods" "Internal ODH"
        prometheus = softwareSystem "Prometheus" "Monitoring and metrics collection" "Internal ODH"

        # Relationships - User
        user -> kuberay "Creates RayCluster/RayJob/RayService via kubectl/API"
        user -> dsgGateway "Accesses Ray Dashboard" "HTTPS/443"

        # Relationships - Operator
        kuberay -> openshift "Manages Pods, Services, Routes, NetworkPolicies" "HTTPS/443"
        kuberay -> certManager "Creates Issuers and Certificates for mTLS" "HTTPS/443"
        kuberay -> gatewayAPI "Creates HTTPRoutes and ReferenceGrants" "HTTPS/443"

        # Relationships - Ray Cluster
        kuberay -> rayCluster "Creates and manages"
        rayCluster -> redis "GCS fault tolerance storage" "TCP/6379"
        rayCluster -> volcano "Batch/gang scheduling" "Scheduler plugin"

        # Relationships - Internal ODH
        rhodsOperator -> kuberay "Deploys via kustomize"
        dsgGateway -> kubeRBACProxy "Routes dashboard traffic" "HTTPS/8443"
        kubeRBACProxy -> openshift "SubjectAccessReview" "HTTPS/443"
        prometheus -> kuberay "Scrapes metrics" "HTTP/8080"

        # Container relationships
        rcController -> openshift "CRUD Pods, Services, Routes" "HTTPS/443"
        rjController -> rcController "Creates/reuses RayCluster"
        rsController -> rcController "Manages RayCluster lifecycle"
        authController -> gatewayAPI "Creates HTTPRoutes, ReferenceGrants" "HTTPS/443"
        mtlsController -> certManager "Creates Issuers, Certificates" "HTTPS/443"
    }

    views {
        systemContext kuberay "SystemContext" "KubeRay Operator in the RHOAI ecosystem" {
            include *
            autoLayout
        }

        container kuberay "Containers" "Internal structure of the KubeRay Operator" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #4a90e2
                color #ffffff
                shape RoundedBox
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal ODH" {
                background #7ed321
                color #ffffff
            }
            element "Managed Workload" {
                background #f5a623
                color #ffffff
            }
            element "Person" {
                background #08427b
                color #ffffff
                shape Person
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
