// C4 Context Diagram: llama-stack-k8s-operator
// Generated by: Claude Opus 4.6
// Source: architecture/rhoai-3.2/llama-stack-k8s-operator.md

workspace {
    model {
        user = person "Platform Admin / Data Scientist" "Creates and manages LlamaStackDistribution resources"

        llamaStackOperator = softwareSystem "LlamaStack K8s Operator" "Manages lifecycle of Llama Stack AI inference server deployments on OpenShift/Kubernetes" {
            controller = container "LlamaStackDistribution Reconciler" "Watches CRs and reconciles Deployments, Services, PVCs, SA, RoleBindings, NetworkPolicies, PDBs, HPAs" "Go Controller (controller-runtime)"
            kustomizeRenderer = container "Kustomize Renderer" "Renders Kubernetes manifests from embedded base templates with runtime transformations" "Go Library (pkg/deploy)"
            clusterInfo = container "Cluster Info" "Detects operator namespace, loads distribution image mappings, upgrade cleanup" "Go Library (pkg/cluster)"
            featureFlags = container "Feature Flags" "Manages operator feature flags via ConfigMap" "Go Library (pkg/featureflags)"
            rbacProxy = container "kube-rbac-proxy" "RBAC-authorized access to metrics endpoint" "Sidecar Container"
        }

        llamaStackServer = softwareSystem "Llama Stack Server" "AI inference server managed by the operator" "Managed"

        k8sApi = softwareSystem "Kubernetes API Server" "Cluster control plane for resource management" "External"
        rhodsOperator = softwareSystem "rhods-operator" "Deploys LlamaStack operator via kustomize overlays" "Internal RHOAI"
        prometheus = softwareSystem "Prometheus" "Metrics collection and monitoring" "External"
        odhTrustedCA = softwareSystem "ODH Trusted CA Bundle" "Platform CA certificates ConfigMap" "Internal RHOAI"

        // Relationships
        user -> llamaStackOperator "Creates LlamaStackDistribution CRs via kubectl"
        llamaStackOperator -> k8sApi "Manages resources (Deployments, Services, etc.)" "HTTPS/443 TLS 1.2+"
        llamaStackOperator -> llamaStackServer "Health checks, provider queries, version info" "HTTP/8321 plaintext"
        rhodsOperator -> llamaStackOperator "Deploys via config/overlays/rhoai" "Kustomize"
        prometheus -> llamaStackOperator "Scrapes metrics" "HTTPS/8443 TLS"
        llamaStackOperator -> odhTrustedCA "Auto-detects platform CA certificates" "ConfigMap read"

        // Internal relationships
        controller -> kustomizeRenderer "Renders manifests"
        controller -> clusterInfo "Detects namespace, image mappings"
        controller -> featureFlags "Checks feature flags"
        rbacProxy -> controller "Proxies metrics requests"
    }

    views {
        systemContext llamaStackOperator "SystemContext" {
            include *
            autoLayout
        }

        container llamaStackOperator "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438dd5
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Managed" {
                background #f5a623
                color #ffffff
            }
            element "Person" {
                shape person
                background #08427b
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
