// C4 Context Diagram: llm-d-routing-sidecar
// Generated by: Claude Opus 4.6

workspace {
    model {
        client = person "Client / Gateway" "Sends OpenAI-compatible inference requests"

        routingSidecar = softwareSystem "llm-d-routing-sidecar" "Reverse proxy sidecar enabling disaggregated prefill/decode inference routing" {
            proxy = container "Reverse Proxy" "Intercepts and routes inference requests between prefiller and decoder" "Go HTTP/HTTPS Server" "8000/TCP"
            nixlv2 = container "NIXL v2 Connector" "Default protocol handler for KV-cache transfer parameters" "Go Module"
            nixlv1 = container "NIXL v1 Connector" "Legacy NIXL v1 protocol handler (deprecated)" "Go Module"
            lmcache = container "LMCache Connector" "LMCache-based KV transfer protocol handler (deprecated)" "Go Module"
            allowlist = container "AllowlistValidator" "SSRF protection via InferencePool-based pod allowlisting" "Go Module"
            tlsMgr = container "TLS Manager" "Self-signed or user-provided TLS certificate management" "Go Module"
        }

        vllmDecoder = softwareSystem "vLLM Decoder (Local)" "Local vLLM instance for decode phase" "Internal"
        vllmPrefiller = softwareSystem "vLLM Prefiller (Remote)" "Remote vLLM instances for prefill phase" "Internal"
        k8sAPI = softwareSystem "Kubernetes API" "Cluster API server for resource watches" "External"
        gatewayAPIExt = softwareSystem "Gateway API Inference Extension" "InferencePool CRD for pod selector discovery" "External"

        // Relationships
        client -> routingSidecar "POST /v1/chat/completions, /v1/completions" "HTTPS/8000 TLS 1.2+"
        routingSidecar -> vllmDecoder "Forwards decode & passthrough requests" "HTTP or HTTPS/8001"
        routingSidecar -> vllmPrefiller "Forwards prefill requests (SSRF validated)" "HTTP or HTTPS/Dynamic"
        routingSidecar -> k8sAPI "Watch InferencePool and Pod resources" "HTTPS/443 SA Token"
        routingSidecar -> gatewayAPIExt "Watch InferencePool CR for pod selectors" "HTTPS/443"

        // Container-level relationships
        proxy -> nixlv2 "Selects for P/D routing"
        proxy -> allowlist "Validates prefill targets"
        tlsMgr -> proxy "Provides TLS certificates"
        allowlist -> k8sAPI "Watch/List Pods and InferencePool" "HTTPS/443"
    }

    views {
        systemContext routingSidecar "SystemContext" {
            include *
            autoLayout
        }

        container routingSidecar "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438dd5
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal" {
                background #7ed321
                color #ffffff
            }
            element "Person" {
                background #08427b
                color #ffffff
                shape person
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
