// MLflow Operator - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6

workspace {
    model {
        admin = person "Platform Admin" "Creates and manages MLflow instances via MLflow CRs"
        dataScientist = person "Data Scientist" "Uses MLflow tracking API and UI for experiment tracking"

        mlflowOperator = softwareSystem "MLflow Operator" "Kubernetes operator managing MLflow tracking server lifecycle on OpenShift" {
            controller = container "MLflow Controller" "Watches MLflow CRs, renders Helm chart, applies resources via SSA" "Go (controller-runtime)"
            helmRenderer = container "Helm Renderer" "Converts MLflow CR spec to Helm values and renders chart templates" "Go (Helm v3 SDK)"
            routingController = container "Routing Controller" "Creates HTTPRoute and ConsoleLink resources conditionally" "Go"
        }

        mlflowServer = softwareSystem "MLflow Tracking Server" "MLflow v3.6.0 with kubernetes-auth, serves REST API and UI over HTTPS" {
            trackingAPI = container "MLflow REST API" "Experiment tracking, model registry, artifact management" "Python (uvicorn + SSL)"
            kubeAuth = container "Kubernetes Auth App" "SubjectAccessReview-based authentication/authorization" "Python"
        }

        k8sAPI = softwareSystem "Kubernetes API" "Cluster API server for CRD management, RBAC, and resource lifecycle" "Infrastructure"
        rhodsOperator = softwareSystem "rhods-operator" "Deploys MLflow operator via kustomize overlays; injects image references" "Internal RHOAI"
        gateway = softwareSystem "data-science-gateway" "Gateway API gateway in openshift-ingress namespace for external access" "Infrastructure"
        openshiftConsole = softwareSystem "OpenShift Console" "Web console with Application Menu integration via ConsoleLink" "Infrastructure"
        serviceCA = softwareSystem "OpenShift service-ca" "Automatic TLS certificate generation and rotation for services" "Infrastructure"
        prometheus = softwareSystem "Prometheus" "Metrics collection via ServiceMonitor" "Monitoring"
        backendStore = softwareSystem "Backend Store (PostgreSQL/MySQL)" "MLflow metadata storage for experiments, runs, metrics" "External Database"
        artifactStore = softwareSystem "Artifact Store (S3/GCS/Azure)" "MLflow artifact storage for models and datasets" "External Storage"

        // Admin interactions
        admin -> mlflowOperator "Creates MLflow CRs" "kubectl / YAML"
        admin -> openshiftConsole "Accesses MLflow via console link"

        // Data scientist interactions
        dataScientist -> mlflowServer "Uses MLflow API and UI" "HTTPS/8443"
        dataScientist -> gateway "Accesses MLflow externally" "HTTPS/443"

        // Operator interactions
        mlflowOperator -> k8sAPI "Watches CRDs, SSA apply, Discovery API" "HTTPS/443"
        mlflowOperator -> mlflowServer "Deploys and manages lifecycle" "Kubernetes Resources"

        // Controller internal
        controller -> helmRenderer "Renders CR spec to manifests"
        controller -> routingController "Manages HTTPRoute and ConsoleLink"

        // Gateway routing
        gateway -> mlflowServer "Routes traffic (TLS passthrough)" "HTTPS/8443"
        routingController -> gateway "Creates HTTPRoute resources" "Gateway API v1"
        routingController -> openshiftConsole "Creates ConsoleLink resources"

        // MLflow server interactions
        mlflowServer -> k8sAPI "SubjectAccessReview for auth" "HTTPS/443"
        mlflowServer -> backendStore "Metadata queries" "TCP/5432 or 3306"
        mlflowServer -> artifactStore "Artifact read/write" "HTTPS/443"

        // Infrastructure
        rhodsOperator -> mlflowOperator "Deploys via kustomize overlay"
        serviceCA -> mlflowServer "Provisions TLS certificates" "service annotation"
        serviceCA -> mlflowOperator "Provisions metrics TLS certificates"
        prometheus -> mlflowOperator "Scrapes metrics" "HTTPS/8443"
    }

    views {
        systemContext mlflowOperator "SystemContext" {
            include *
            autoLayout
        }

        container mlflowOperator "OperatorContainers" {
            include *
            autoLayout
        }

        container mlflowServer "ServerContainers" {
            include *
            autoLayout
        }

        styles {
            element "Person" {
                shape Person
                background #4a90e2
                color #ffffff
            }
            element "Software System" {
                background #1168bd
                color #ffffff
            }
            element "Infrastructure" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Monitoring" {
                background #9673a6
                color #ffffff
            }
            element "External Database" {
                background #f5a623
                color #ffffff
            }
            element "External Storage" {
                background #f5a623
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
