/*
 * C4 Context Diagram: KServe V2 REST Proxy
 * Generated by: Claude Opus 4.6
 * Source: architecture/rhoai-3.2/rest-proxy.md
 */

workspace {
    model {
        client = person "Inference Client" "Sends KServe V2 REST inference requests to deployed models"

        restProxy = softwareSystem "KServe V2 REST Proxy" "Reverse-proxy sidecar translating KServe V2 REST requests into gRPC calls for ModelMesh Serving" {
            proxyServer = container "REST Proxy Server" "Accepts HTTP/HTTPS requests on port 8008 and proxies to gRPC" "Go HTTP Server"
            grpcGateway = container "gRPC-Gateway" "Auto-generated reverse proxy translating HTTP/JSON to gRPC/protobuf" "Go Library (v2.15.0)"
            jsonMarshaler = container "Custom JSON Marshaler" "Handles tensor data serialization with multi-dimensional array and base64 byte support" "Go Module"
            protoDefs = container "Protobuf Definitions" "Defines GRPCInferenceService API (ModelMetadata, ModelInfer)" "Proto3"
        }

        modelMesh = softwareSystem "ModelMesh Serving" "Multi-model serving platform providing gRPC inference service" "Internal RHOAI"
        certManager = softwareSystem "cert-manager" "TLS certificate provisioning and management" "External"
        modelServingConfig = softwareSystem "model-serving-config ConfigMap" "Configuration for ModelMesh Serving including REST proxy image reference" "Internal RHOAI"

        # Relationships
        client -> restProxy "Sends inference requests" "HTTP/HTTPS on 8008/TCP"
        restProxy -> modelMesh "Forwards as gRPC calls" "gRPC on 8033/TCP (localhost)"
        certManager -> restProxy "Provisions TLS certificates" "TLS cert/key files"
        modelServingConfig -> restProxy "Configures proxy image" "restProxy.image field"

        # Internal container relationships
        proxyServer -> grpcGateway "Routes HTTP requests"
        grpcGateway -> jsonMarshaler "Serializes/deserializes tensor data"
        grpcGateway -> protoDefs "Uses proto definitions"
    }

    views {
        systemContext restProxy "SystemContext" {
            include *
            autoLayout
        }

        container restProxy "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #4a90e2
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Person" {
                background #f5a623
                color #ffffff
                shape person
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
