// RHOAI Build Config - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6
// Source: architecture/rhoai-3.2/RHOAI-Build-Config.md

workspace {
    model {
        // People
        developer = person "Release Engineer" "Manages RHOAI build configuration, image pins, and release artifacts"
        securityEngineer = person "Security Engineer" "Validates container image compliance via Enterprise Contract"

        // Primary System
        buildConfig = softwareSystem "RHOAI-Build-Config" "Central build configuration repository defining RHOAI 3.2 operator bundle, FBC catalog fragments, and 78 container image references" {
            bundlePatchSystem = container "Bundle Patch System" "Pins 78 RELATED_IMAGE references with SHA256 digests for disconnected support" "YAML Configuration"
            additionalImagesPatch = container "Additional Images Patch" "Adds OpenShift infrastructure images (oauth-proxy, etcd, CLI, etc.)" "YAML Configuration"
            csvPatch = container "CSV Patch" "Adds operator metadata, arch support labels, feature annotations" "YAML Configuration"
            catalogPatch = container "Catalog Patch" "Defines OLM package name, channels (fast-3.x), upgrade path" "YAML Configuration"
            buildArgsMap = container "Build Args Map" "Maps component names to upstream Git URLs and pinned commit SHAs" "Key-Value Map"
            csv = container "ClusterServiceVersion" "Operator installation manifest with CRDs, RBAC, and image references" "OLM Manifest"
            bundleDockerfile = container "Bundle Dockerfile" "Packages CSV, CRDs, and metadata into OLM-installable bundle image" "Dockerfile"
            fbcDockerfile = container "FBC Dockerfile" "Per-OCP-version catalog images with operator package/channel/bundle entries" "Dockerfile"
            tektonBundlePipeline = container "Tekton Bundle Pipeline" "odh-operator-bundle-v3-2-push PipelineRun for hermetic builds" "Tekton PipelineRun"
            tektonFBCPipeline = container "Tekton FBC Pipeline" "rhoai-fbc-fragment-v3-2-push PipelineRun for FBC builds" "Tekton PipelineRun"
            ghProcessBundle = container "Process Bundle Workflow" "Automates bundle CSV regeneration on patch file changes" "GitHub Actions"
            ghProcessFBC = container "Process FBC Workflow" "Automates FBC catalog regeneration on catalog patch changes" "GitHub Actions"
            ecTest = container "Enterprise Contract Test" "Validates container image signatures and policy compliance" "Tekton Pipeline"
        }

        // External Systems
        github = softwareSystem "GitHub" "Source code hosting, webhooks, and CI triggers" "External"
        konflux = softwareSystem "Konflux / RHTAP" "CI/CD build system for hermetic container image builds" "External"
        quay = softwareSystem "quay.io/rhoai" "Development and staging container image registry" "External"
        registryRedhat = softwareSystem "registry.redhat.io" "Production Red Hat container image distribution" "External"
        brewRegistry = softwareSystem "brew.registry.redhat.io" "OCP base images for FBC catalog builds" "External"
        olm = softwareSystem "Operator Lifecycle Manager" "Installs and manages operators via CSV and catalog" "External"
        ocp = softwareSystem "OpenShift Container Platform" "Target deployment platform (v4.19, v4.20)" "External"
        konfluxAutomation = softwareSystem "RHOAI-Konflux-Automation" "Shared utilities for bundle/FBC processing workflows" "Internal RHOAI"
        pnc = softwareSystem "PNC (Product Newcastle)" "Maven build system for TrustyAI service artifacts" "External"

        // Internal RHOAI component (deployed by bundle)
        rhodsOperator = softwareSystem "rhods-operator" "Red Hat OpenShift AI operator managing all RHOAI components" "Internal RHOAI"

        // Relationships - People
        developer -> buildConfig "Updates image pins, patch files, and release artifacts"
        securityEngineer -> buildConfig "Reviews Enterprise Contract validation results"

        // Relationships - Build flows
        buildConfig -> github "Stores source code and triggers CI/CD" "HTTPS/443"
        buildConfig -> konflux "Runs hermetic builds for bundle and FBC images" "HTTPS/443"
        buildConfig -> konfluxAutomation "Uses shared scripts for bundle/FBC processing" "HTTPS/443"
        buildConfig -> quay "Pushes built bundle and FBC images" "HTTPS/443"
        buildConfig -> brewRegistry "Pulls OCP base images for FBC builds" "HTTPS/443"
        buildConfig -> pnc "Builds TrustyAI Maven artifacts via Bacon/PIG" "HTTPS/443"
        quay -> registryRedhat "Images promoted after EC validation" "HTTPS/443"

        // Relationships - Installation flow
        olm -> registryRedhat "Pulls FBC catalog and bundle images" "HTTPS/443"
        olm -> rhodsOperator "Installs and manages operator lifecycle"
        rhodsOperator -> ocp "Deploys and manages all RHOAI components"

        // Internal container relationships
        bundlePatchSystem -> csv "Pins images into CSV"
        additionalImagesPatch -> csv "Adds infrastructure images"
        csvPatch -> csv "Adds metadata and annotations"
        buildArgsMap -> bundlePatchSystem "Tracks upstream SHAs"
        csv -> bundleDockerfile "Packaged into bundle image"
        catalogPatch -> fbcDockerfile "Defines OLM channels"
        tektonBundlePipeline -> bundleDockerfile "Builds bundle image"
        tektonFBCPipeline -> fbcDockerfile "Builds FBC image"
        ghProcessBundle -> csv "Regenerates CSV"
        ecTest -> quay "Validates image signatures" "HTTPS/443 Cosign"
    }

    views {
        systemContext buildConfig "SystemContext" {
            include *
            autoLayout
        }

        container buildConfig "Containers" {
            include *
            autoLayout
        }

        styles {
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Software System" {
                background #4a90e2
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
            element "Person" {
                background #08427b
                color #ffffff
                shape Person
            }
        }
    }
}
