/*
 * vLLM ROCm - C4 Context Diagram (Structurizr DSL)
 * Generated by: Claude Opus 4.6
 * Source: architecture/rhoai-3.2/vllm-rocm.md
 */

workspace {
    model {
        user = person "Data Scientist / ML Engineer" "Deploys and queries LLM inference endpoints"

        vllmRocm = softwareSystem "vLLM ROCm" "GPU-accelerated LLM inference serving runtime for AMD ROCm GPUs" {
            vllmContainer = container "vLLM Container" "Runs vLLM engine with ROCm GPU acceleration, serves OpenAI-compatible HTTP API" "Python / ROCm"
            tgisAdapter = container "TGIS Adapter" "Bridges vLLM engine to TGIS gRPC protocol for ModelMesh compatibility" "Python"
        }

        kserve = softwareSystem "KServe" "Orchestrates model serving via InferenceService CRs" "Internal RHOAI"
        modelMesh = softwareSystem "ModelMesh" "Alternative model serving orchestration via ServingRuntime CRs" "Internal RHOAI"
        modelController = softwareSystem "Model Controller" "Manages lifecycle of inference runtime deployments" "Internal RHOAI"
        rhoaiGateway = softwareSystem "RHOAI Gateway" "Envoy-based gateway providing ingress, TLS, and auth" "Internal RHOAI"
        kubeRbacProxy = softwareSystem "kube-rbac-proxy" "Sidecar providing auth enforcement via SubjectAccessReview" "Internal RHOAI"
        serviceMesh = softwareSystem "Service Mesh / Gateway API" "Provides mTLS, authentication, and routing" "Internal RHOAI"
        prometheus = softwareSystem "Prometheus" "Metrics collection and monitoring" "Internal RHOAI"

        s3 = softwareSystem "S3 / Object Storage" "Stores model weight artifacts" "External"
        hfHub = softwareSystem "Hugging Face Hub" "Model and tokenizer configuration repository" "External"
        konflux = softwareSystem "Konflux CI/CD" "Tekton-based build system for container images" "External"

        # User interactions
        user -> rhoaiGateway "Sends inference requests" "HTTPS/443"
        user -> kserve "Creates InferenceService CRs" "kubectl"

        # Platform orchestration
        kserve -> vllmRocm "Deploys as ServingRuntime" "Container Runtime"
        modelMesh -> vllmRocm "Deploys as ServingRuntime" "Container Runtime"
        modelController -> vllmRocm "Manages deployment lifecycle"

        # Ingress flow
        rhoaiGateway -> kubeRbacProxy "Routes authenticated requests" "HTTPS/8443"
        kubeRbacProxy -> vllmContainer "Proxies to inference API" "HTTP/8000"
        modelMesh -> tgisAdapter "Sends gRPC inference requests" "gRPC/8033 mTLS"

        # Egress
        vllmRocm -> s3 "Downloads model weights" "HTTPS/443"
        vllmRocm -> hfHub "Downloads model config" "HTTPS/443"

        # Monitoring
        prometheus -> vllmContainer "Scrapes metrics" "HTTP/8000"

        # Build
        konflux -> vllmRocm "Builds container image" "Tekton Pipeline"
    }

    views {
        systemContext vllmRocm "SystemContext" {
            include *
            autoLayout
        }

        container vllmRocm "Containers" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #438dd5
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Person" {
                background #08427b
                color #ffffff
                shape Person
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
        }
    }
}
