// vLLM CPU - C4 Context Diagram (Structurizr DSL)
// Generated by: Claude Opus 4.6

workspace {
    model {
        user = person "Data Scientist / Developer" "Sends inference requests to vLLM CPU"

        vllmCpu = softwareSystem "vLLM CPU" "CPU-optimized LLM inference engine with OpenAI-compatible REST API and gRPC (TGIS) support" {
            apiServer = container "OpenAI API Server" "FastAPI/Uvicorn HTTP server exposing OpenAI-compatible REST endpoints" "Python (FastAPI)" "Port 8000/TCP"
            tgisAdapter = container "vllm-tgis-adapter" "gRPC adapter providing KServe/TGIS-compatible inference protocol" "Python" "Port 8033/TCP"
            engine = container "vLLM Engine v1" "Core inference engine with PagedAttention, scheduling, and model execution" "Python"
            cpuKernels = container "CPU C++ Extensions" "Optimized CPU kernels for attention, activation, layernorm, positional encoding, MLA decode" "C++17"
            structuredOutput = container "Structured Output" "Constrained generation via xgrammar, outlines_core, lm-format-enforcer" "Python"
            metrics = container "Prometheus Metrics" "Metrics exporter at /metrics endpoint" "Python (prometheus_client)"
            tracing = container "OpenTelemetry Tracing" "Distributed tracing via OTLP exporters" "Python"
        }

        kserve = softwareSystem "KServe" "Inference serving framework managing vLLM as InferenceService runtime" "Internal RHOAI"
        modelMesh = softwareSystem "Model Mesh" "Optional model serving infrastructure" "Internal RHOAI"
        prometheus = softwareSystem "Prometheus" "Metrics collection and monitoring" "Internal"
        otelCollector = softwareSystem "OpenTelemetry Collector" "Distributed trace collection" "Internal"
        hfHub = softwareSystem "HuggingFace Hub" "Model weights repository" "External"
        s3Storage = softwareSystem "S3-Compatible Storage" "Model artifact storage" "External"
        pytorch = softwareSystem "PyTorch / IPEX" "Tensor computation framework" "External Library"

        // User interactions
        user -> vllmCpu "Sends inference requests via HTTP/gRPC"

        // Internal container relationships
        apiServer -> engine "Forwards inference requests" "IPC"
        tgisAdapter -> engine "Forwards gRPC requests" "IPC"
        engine -> cpuKernels "Executes optimized kernels" "In-process"
        engine -> structuredOutput "Constrained generation" "In-process"
        apiServer -> metrics "Exposes metrics" "/metrics"
        apiServer -> tracing "Sends traces" "OTLP"

        // External integrations
        kserve -> vllmCpu "Manages as InferenceService runtime" "HTTP/8000, gRPC/8033"
        modelMesh -> vllmCpu "Optional model serving" "gRPC"
        prometheus -> vllmCpu "Scrapes metrics" "HTTP GET /metrics, 8000/TCP"
        vllmCpu -> otelCollector "Exports traces" "gRPC/4317 or HTTP/4318"
        vllmCpu -> hfHub "Downloads model weights" "HTTPS/443, HF Token"
        vllmCpu -> s3Storage "Downloads model artifacts" "HTTPS/443, S3 IAM"
        engine -> pytorch "Tensor computation" "In-process"
    }

    views {
        systemContext vllmCpu "SystemContext" {
            include *
            autoLayout
        }

        container vllmCpu "Containers" {
            include *
            autoLayout
        }

        styles {
            element "External" {
                background #999999
                color #ffffff
            }
            element "Internal RHOAI" {
                background #7ed321
                color #ffffff
            }
            element "Internal" {
                background #4a90e2
                color #ffffff
            }
            element "External Library" {
                background #f5a623
                color #ffffff
            }
            element "Person" {
                shape Person
                background #08427b
                color #ffffff
            }
            element "Software System" {
                shape RoundedBox
            }
            element "Container" {
                shape RoundedBox
            }
        }
    }
}
